export interface FlagCard {
    id: string;
    scenario: string;
}

// 100+ flag scenarios - mix of potential red, green, and beige flags
export const flagCards: FlagCard[] = [

    // ❤️ RELATIONSHIP BEHAVIORS
    { id: "f1", scenario: "They remember your coffee order without being told" },
    { id: "f2", scenario: "They still talk about their ex in the first 5 minutes of meeting" },
    { id: "f3", scenario: "They say 'I love you' on the first date" },
    { id: "f4", scenario: "They plan dates weeks in advance with a full itinerary" },
    { id: "f5", scenario: "They're still close friends with all their exes" },
    { id: "f6", scenario: "They introduce you to their parents after two weeks" },
    { id: "f7", scenario: "They remember the exact date you first met" },
    { id: "f8", scenario: "They check in with a text every morning without being asked" },
    { id: "f9", scenario: "They buy you small gifts for no reason at all" },
    { id: "f10", scenario: "They use 'we' within days of meeting you" },
    { id: "f11", scenario: "They already follow your family on Instagram" },
    { id: "f12", scenario: "They never make any plans — always wait for you" },
    { id: "f13", scenario: "They treat every argument like it needs a resolution before bed" },
    { id: "f14", scenario: "They keep every card you've ever given them" },
    { id: "f15", scenario: "They have a photo of you as their phone wallpaper early on" },
    { id: "f16", scenario: "They bring up marriage casually on the third date" },
    { id: "f17", scenario: "They cry when you leave after a visit" },
    { id: "f18", scenario: "They make a playlist for you after the first date" },
    { id: "f19", scenario: "They know your order at every restaurant you've been to together" },
    { id: "f20", scenario: "They plan a trip with you before you're even official" },

    // 💬 COMMUNICATION STYLE
    { id: "f21", scenario: "They double text without waiting for a reply" },
    { id: "f22", scenario: "They take 3+ days to respond to texts" },
    { id: "f23", scenario: "They send good morning texts every single day" },
    { id: "f24", scenario: "They respond with 'K' to long heartfelt messages" },
    { id: "f25", scenario: "They call instead of texting, always" },
    { id: "f26", scenario: "They leave voicemails instead of texting" },
    { id: "f27", scenario: "They never use emojis — ever" },
    { id: "f28", scenario: "They only communicate through memes" },
    { id: "f29", scenario: "They screenshot conversations to show friends" },
    { id: "f30", scenario: "They bring up feelings through text instead of in person" },
    { id: "f31", scenario: "They go quiet for a full day with no explanation" },
    { id: "f32", scenario: "They send essay-length texts to explain their feelings" },
    { id: "f33", scenario: "They reply instantly no matter what time it is" },
    { id: "f34", scenario: "They use full sentences and punctuation in every text" },
    { id: "f35", scenario: "They end every call with 'I love you' no matter who's listening" },
    { id: "f36", scenario: "They check their phone during dinner together" },
    { id: "f37", scenario: "They never bring up what's bothering them — just go quiet" },
    { id: "f38", scenario: "They bring up an issue days after it happened instead of in the moment" },
    { id: "f39", scenario: "They talk about their problems to everyone except you" },
    { id: "f40", scenario: "They need to debrief every social event after it happens" },

    // 🏠 HOME & LIVING TOGETHER
    { id: "f41", scenario: "They've never made their bed a day in their life" },
    { id: "f42", scenario: "They iron their clothes the night before" },
    { id: "f43", scenario: "They have a designated place for everything in the kitchen" },
    { id: "f44", scenario: "They have a 'chair' for clothes instead of using the closet" },
    { id: "f45", scenario: "They own more candles than furniture" },
    { id: "f46", scenario: "They have a shoe-free home policy — no exceptions" },
    { id: "f47", scenario: "They clean when they're stressed" },
    { id: "f48", scenario: "They've never cleaned their bathroom mirror" },
    { id: "f49", scenario: "They don't own a single book" },
    { id: "f50", scenario: "They reorganize the whole house every few months" },
    { id: "f51", scenario: "Their bedroom looks like a Pinterest board" },
    { id: "f52", scenario: "They keep every surface completely clear — nothing on the counters" },
    { id: "f53", scenario: "They have 6 different throw pillows on the bed" },
    { id: "f54", scenario: "They keep their place so clean it feels like no one lives there" },
    { id: "f55", scenario: "They have plants everywhere and they're all alive" },
    { id: "f56", scenario: "Their fridge is always completely full and organized" },
    { id: "f57", scenario: "They sleep with the TV on every night" },
    { id: "f58", scenario: "They make the bed immediately after getting up" },
    { id: "f59", scenario: "They leave dishes to 'soak' indefinitely" },
    { id: "f60", scenario: "They have a junk drawer that's completely out of control" },

    // 🍕 FOOD & EATING
    { id: "f61", scenario: "They eat pizza with a fork and knife" },
    { id: "f62", scenario: "They put ketchup on everything" },
    { id: "f63", scenario: "They order the exact same thing every time at every restaurant" },
    { id: "f64", scenario: "They take photos of every meal before eating" },
    { id: "f65", scenario: "They mix all their food together on the plate" },
    { id: "f66", scenario: "They season food before tasting it" },
    { id: "f67", scenario: "They dip fries in their milkshake" },
    { id: "f68", scenario: "They eat dessert before the main course" },
    { id: "f69", scenario: "They don't like chocolate — at all" },
    { id: "f70", scenario: "They meal prep every single Sunday without fail" },
    { id: "f71", scenario: "They refuse to share food off their plate" },
    { id: "f72", scenario: "They always order something different to try everything" },
    { id: "f73", scenario: "They eat the same breakfast every single day" },
    { id: "f74", scenario: "They take forever to decide what they want at a restaurant" },
    { id: "f75", scenario: "They ask the waiter 10 questions before ordering" },
    { id: "f76", scenario: "They can eat the same leftovers for a week without complaining" },
    { id: "f77", scenario: "They smell their food before every bite" },
    { id: "f78", scenario: "They won't eat anything green" },
    { id: "f79", scenario: "They treat cooking dinner like a full production" },
    { id: "f80", scenario: "They clean the kitchen while cooking so there's no mess after" },

    // 💸 MONEY & SPENDING
    { id: "f81", scenario: "They split the bill down to the exact cent" },
    { id: "f82", scenario: "They always insist on paying — won't hear otherwise" },
    { id: "f83", scenario: "They have no savings in their 30s" },
    { id: "f84", scenario: "They use a spreadsheet to track every personal expense" },
    { id: "f85", scenario: "They buy designer items but stress about rent" },
    { id: "f86", scenario: "They tip generously every single time" },
    { id: "f87", scenario: "They tip exactly 15% — no more, no less, no matter what" },
    { id: "f88", scenario: "They have 4 different investing apps" },
    { id: "f89", scenario: "They borrow money and never bring it up again" },
    { id: "f90", scenario: "They research every purchase for weeks before buying" },
    { id: "f91", scenario: "They buy something, feel guilty, and return it" },
    { id: "f92", scenario: "They never look at prices on a menu" },
    { id: "f93", scenario: "They know exactly how much is in their account at all times" },
    { id: "f94", scenario: "They split everything 50/50 — no exceptions, no compromises" },
    { id: "f95", scenario: "They're extremely generous with others but frugal with themselves" },
    { id: "f96", scenario: "They keep every receipt for months" },
    { id: "f97", scenario: "They have a 'fun money' budget they never feel guilty spending" },
    { id: "f98", scenario: "They panic when their savings dip even slightly" },
    { id: "f99", scenario: "They invest in things they genuinely don't understand" },
    { id: "f100", scenario: "They still use cash for everything" },

    // 📱 SOCIAL MEDIA & PHONE
    { id: "f101", scenario: "They post couple photos on day one" },
    { id: "f102", scenario: "They have no social media whatsoever" },
    { id: "f103", scenario: "They still have photos up with their ex" },
    { id: "f104", scenario: "They like posts from 3 years ago on your profile" },
    { id: "f105", scenario: "They check your following list regularly" },
    { id: "f106", scenario: "They post every single meal they eat" },
    { id: "f107", scenario: "They unfollow people who don't follow back" },
    { id: "f108", scenario: "They comment on all your posts within seconds" },
    { id: "f109", scenario: "They use speakerphone in public without warning" },
    { id: "f110", scenario: "They have a finsta nobody knows about" },
    { id: "f111", scenario: "They go live on Instagram randomly" },
    { id: "f112", scenario: "Their phone is always face-down" },
    { id: "f113", scenario: "They never post anything — completely private online" },
    { id: "f114", scenario: "They keep their phone on Do Not Disturb all day" },
    { id: "f115", scenario: "They post Stories every single day without fail" },
    { id: "f116", scenario: "They share everything to their Close Friends story — you're on it" },
    { id: "f117", scenario: "They get annoyed when you don't watch their Stories" },
    { id: "f118", scenario: "They have notifications off for everything including you" },
    { id: "f119", scenario: "They subtweet about their feelings instead of talking" },
    { id: "f120", scenario: "They pretend to text to avoid social situations" },

    // 😴 SLEEP & MORNING ROUTINE
    { id: "f121", scenario: "They wake up at 5am to work out every day" },
    { id: "f122", scenario: "They set 7 alarms and sleep through all of them" },
    { id: "f123", scenario: "They sleep with socks on even in summer" },
    { id: "f124", scenario: "They need complete silence to fall asleep" },
    { id: "f125", scenario: "They talk in their sleep" },
    { id: "f126", scenario: "They steal the covers every single night" },
    { id: "f127", scenario: "They wake up and immediately check their phone" },
    { id: "f128", scenario: "They need at least 9 hours to function" },
    { id: "f129", scenario: "They're fully awake and cheerful the second they open their eyes" },
    { id: "f130", scenario: "They can fall asleep anywhere within minutes" },
    { id: "f131", scenario: "They need 30 minutes of silence in the morning before talking" },
    { id: "f132", scenario: "They make bed-time a full wind-down ritual with skincare, tea, and reading" },
    { id: "f133", scenario: "They snore but will never believe you" },
    { id: "f134", scenario: "They sleep with a fan on regardless of weather" },
    { id: "f135", scenario: "They're a blanket hog but refuse to acknowledge it" },
    { id: "f136", scenario: "They do their best thinking at 2am and want to talk" },
    { id: "f137", scenario: "They nap for exactly 20 minutes and wake up refreshed" },
    { id: "f138", scenario: "They cannot function without a full morning routine" },
    { id: "f139", scenario: "They go to bed at 9pm and are completely at peace with that" },
    { id: "f140", scenario: "They check the door is locked three times before bed" },

    // 🧍 PERSONALITY & SOCIAL BEHAVIOR
    { id: "f141", scenario: "They treat every waiter like an old friend" },
    { id: "f142", scenario: "They remember every person's name they've ever met" },
    { id: "f143", scenario: "They laugh at their own jokes before finishing them" },
    { id: "f144", scenario: "They cry during every emotional movie — every time" },
    { id: "f145", scenario: "They remember everyone's birthday without a reminder" },
    { id: "f146", scenario: "They over-apologize for everything including things that aren't their fault" },
    { id: "f147", scenario: "They correct people's grammar mid-conversation" },
    { id: "f148", scenario: "They're always 15 minutes early to everything" },
    { id: "f149", scenario: "They're always exactly 10-15 minutes late, every time" },
    { id: "f150", scenario: "They talk to strangers like they've known them for years" },
    { id: "f151", scenario: "They wave at dogs but completely ignore their owners" },
    { id: "f152", scenario: "They narrate what they're doing out loud while doing it" },
    { id: "f153", scenario: "They dance when they think nobody's watching" },
    { id: "f154", scenario: "They have a podcast in their head about their own life" },
    { id: "f155", scenario: "They romanticize every moment of their own life" },
    { id: "f156", scenario: "They take notes during arguments to stay accurate" },
    { id: "f157", scenario: "They can't make a decision without asking 4 people's opinions" },
    { id: "f158", scenario: "They give unsolicited but extremely accurate advice" },
    { id: "f159", scenario: "They always play devil's advocate in every conversation" },
    { id: "f160", scenario: "They cry when they're frustrated instead of angry" },

    // 🎭 QUIRKS & HABITS
    { id: "f161", scenario: "They talk to their plants like they're people" },
    { id: "f162", scenario: "They name their car and use the name seriously" },
    { id: "f163", scenario: "They believe in astrology completely unironically" },
    { id: "f164", scenario: "They've memorized their credit card number" },
    { id: "f165", scenario: "They collect something extremely specific and obscure" },
    { id: "f166", scenario: "They still watch cartoons as a full adult" },
    { id: "f167", scenario: "They have lucky underwear they genuinely believe works" },
    { id: "f168", scenario: "They eat only the crust of the pizza first" },
    { id: "f169", scenario: "They clap when the plane lands" },
    { id: "f170", scenario: "They have opinions on fonts and will share them" },
    { id: "f171", scenario: "They have a stuffed animal on the bed at 29" },
    { id: "f172", scenario: "They create Spotify playlists for every possible mood" },
    { id: "f173", scenario: "They have a vision board updated every January" },
    { id: "f174", scenario: "They journal every single day without skipping" },
    { id: "f175", scenario: "They refer to celebrities by first name only like they know them" },
    { id: "f176", scenario: "They have a 12-step skincare routine they never miss" },
    { id: "f177", scenario: "They refuse to kill any bug — they catch and release everything" },
    { id: "f178", scenario: "They have a dedicated reading nook they actually use" },
    { id: "f179", scenario: "They sing full songs in the shower every morning" },
    { id: "f180", scenario: "They can quote any movie but can't tell you what it was about" },

    // 💑 COUPLE-SPECIFIC COMPATIBILITY
    { id: "f181", scenario: "They want to spend every weekend together — no exceptions" },
    { id: "f182", scenario: "They need at least one night a week completely to themselves" },
    { id: "f183", scenario: "They tell their friends everything about your relationship" },
    { id: "f184", scenario: "They keep your relationship almost completely private" },
    { id: "f185", scenario: "They want to share every hobby with you" },
    { id: "f186", scenario: "They have completely separate friend groups and want to keep it that way" },
    { id: "f187", scenario: "They always want to go to bed at the same time" },
    { id: "f188", scenario: "They're fine going to events solo while you stay home" },
    { id: "f189", scenario: "They ask for your opinion on every single decision" },
    { id: "f190", scenario: "They never ask for your opinion and prefer to decide alone" },
    { id: "f191", scenario: "They want matching everything — phone cases, jackets, travel mugs" },
    { id: "f192", scenario: "They need their partner to be their best friend above everything else" },
    { id: "f193", scenario: "They think couples should have completely separate finances — always" },
    { id: "f194", scenario: "They think couples should combine finances fully once serious" },
    { id: "f195", scenario: "They want to talk about the relationship every few weeks intentionally" },
    { id: "f196", scenario: "They express love through acts of service, not words" },
    { id: "f197", scenario: "They need to hear 'I love you' said out loud regularly" },
    { id: "f198", scenario: "They show up unexpectedly with your favourite food after a bad day" },
    { id: "f199", scenario: "They research love languages and actually apply them" },
    { id: "f200", scenario: "They never say 'I love you' first — always waits for you" },

    // 🌍 TRAVEL & ADVENTURE
    { id: "f201", scenario: "They plan every hour of a trip in a shared doc" },
    { id: "f202", scenario: "They book flights the night before with no plan" },
    { id: "f203", scenario: "They always need a window seat — non-negotiable" },
    { id: "f204", scenario: "They overpack for a 3-day trip significantly" },
    { id: "f205", scenario: "They pack everything in a personal item to avoid baggage fees" },
    { id: "f206", scenario: "They eat only at local places — no chains while travelling" },
    { id: "f207", scenario: "They need to visit every museum in any city they go to" },
    { id: "f208", scenario: "They want to wake up early to avoid tourist crowds" },
    { id: "f209", scenario: "They want to sleep in on holiday — no alarms" },
    { id: "f210", scenario: "They take hundreds of photos and rarely look at them again" },
    { id: "f211", scenario: "They want to live like a local everywhere they go" },
    { id: "f212", scenario: "They get travel anxiety and need reassurance throughout" },
    { id: "f213", scenario: "They research a destination for months before going" },
    { id: "f214", scenario: "They want to go somewhere new every single trip" },
    { id: "f215", scenario: "They want to return to the same place they love every year" },
    { id: "f216", scenario: "They talk to every local they meet for recommendations" },
    { id: "f217", scenario: "They spend most of a trip in cafes and restaurants" },
    { id: "f218", scenario: "They need a beach trip at least once a year" },
    { id: "f219", scenario: "They refuse to take any guided tours — ever" },
    { id: "f220", scenario: "They rate every hotel and restaurant immediately after" },

    // 🧠 OPINIONS & WORLDVIEW
    { id: "f221", scenario: "They have a strong take on everything and love to debate it" },
    { id: "f222", scenario: "They have never once changed their mind in an argument" },
    { id: "f223", scenario: "They change their opinion immediately when challenged — too easily" },
    { id: "f224", scenario: "They genuinely don't have strong opinions about most things" },
    { id: "f225", scenario: "They fact-check things mid-conversation on their phone" },
    { id: "f226", scenario: "They believe everything they read online" },
    { id: "f227", scenario: "They can't stand small talk and will deep-dive immediately" },
    { id: "f228", scenario: "They're great at small talk and can talk to anyone about anything" },
    { id: "f229", scenario: "They talk about the future like it's completely planned" },
    { id: "f230", scenario: "They refuse to make any long-term plans — 'too much pressure'" },
    { id: "f231", scenario: "They have a strong ethical stance on what they consume and buy" },
    { id: "f232", scenario: "They have a theory about everything and it's usually interesting" },
    { id: "f233", scenario: "They never watch the news and are proud of it" },
    { id: "f234", scenario: "They follow the news obsessively and stress about it" },
    { id: "f235", scenario: "They think they're always the most logical person in the room" },
    { id: "f236", scenario: "They ask 'why' constantly about everything" },
    { id: "f237", scenario: "They believe in signs and synchronicities genuinely" },
    { id: "f238", scenario: "They're deeply spiritual but not religious" },
    { id: "f239", scenario: "They think therapy is something everyone should do" },
    { id: "f240", scenario: "They've never considered therapy and wouldn't" },

    // 🏃 HEALTH & BODY
    { id: "f241", scenario: "They track every workout and every calorie" },
    { id: "f242", scenario: "They work out 5 days a week no matter what" },
    { id: "f243", scenario: "They haven't exercised intentionally in years" },
    { id: "f244", scenario: "They take 15 supplements every morning" },
    { id: "f245", scenario: "They go to the gym but it's mostly a social event" },
    { id: "f246", scenario: "They walk everywhere — minimum 10k steps a day" },
    { id: "f247", scenario: "They need everything to be alcohol-free when they're sober" },
    { id: "f248", scenario: "They drink a litre of water before anything else every morning" },
    { id: "f249", scenario: "They think rest days are lazy days" },
    { id: "f250", scenario: "They recover from sickness in days because of their routine" },

    // 😅 SOCIAL SITUATIONS
    { id: "f251", scenario: "They RSVP yes and then cancel day-of regularly" },
    { id: "f252", scenario: "They always show up to things even if they're exhausted" },
    { id: "f253", scenario: "They're the last to leave every single event" },
    { id: "f254", scenario: "They leave social events exactly when they said they would" },
    { id: "f255", scenario: "They need 20 minutes in the car before entering any event" },
    { id: "f256", scenario: "They know everyone at every party somehow" },
    { id: "f257", scenario: "They stick to your side all night at social events" },
    { id: "f258", scenario: "They disappear at parties for an hour and you have no idea where they went" },
    { id: "f259", scenario: "They give a speech at every occasion whether asked or not" },
    { id: "f260", scenario: "They refuse to do anything embarrassing in public" },
    { id: "f261", scenario: "They'll do literally anything for a laugh" },
    { id: "f262", scenario: "They remember every embarrassing thing that happened at a party" },
    { id: "f263", scenario: "They host often and go all out every single time" },
    { id: "f264", scenario: "They show up to your place without warning but it's always welcome" },
    { id: "f265", scenario: "They cry when they drink — sometimes happy, sometimes not" },

    // 🔶 GREY ZONE — Things that are clearly one flag but you'd be surprised
    { id: "f266", scenario: "They tell you every single thing that's on their mind — always" },
    { id: "f267", scenario: "They keep a lot to themselves even in a serious relationship" },
    { id: "f268", scenario: "They drop everything when a friend is in crisis" },
    { id: "f269", scenario: "They put the relationship above all friendships completely" },
    { id: "f270", scenario: "They're honest to a fault — even when it's uncomfortable" },
    { id: "f271", scenario: "They avoid conflict at all costs and will never fight back" },
    { id: "f272", scenario: "They always fight to resolve things the same day" },
    { id: "f273", scenario: "They need space after conflict before they can talk" },
    { id: "f274", scenario: "They say exactly what they feel the moment they feel it" },
    { id: "f275", scenario: "They've never once raised their voice in any relationship" },
    { id: "f276", scenario: "They can go weeks without needing validation from you" },
    { id: "f277", scenario: "They need regular reassurance that everything is okay between you" },
    { id: "f278", scenario: "They notice small changes in your mood before you say anything" },
    { id: "f279", scenario: "They're completely unbothered by things that would upset most people" },
    { id: "f280", scenario: "They apologize the moment they realize they were wrong — immediately" },

    // 🌶️ SPICY BUT FAIR — Debatable even for couples
    { id: "f281", scenario: "They still follow people they've dated on social media" },
    { id: "f282", scenario: "They have a friendship with someone their ex was jealous of" },
    { id: "f283", scenario: "They text an ex to check in on their birthday" },
    { id: "f284", scenario: "They compare how you handle things to how others do — out loud" },
    { id: "f285", scenario: "They keep score of who did what in the relationship" },
    { id: "f286", scenario: "They bring up old arguments as evidence in new ones" },
    { id: "f287", scenario: "They shut down completely during conflict instead of engaging" },
    { id: "f288", scenario: "They test you without telling you they're testing you" },
    { id: "f289", scenario: "They need to win every argument — even small ones" },
    { id: "f290", scenario: "They hide how much things bother them until they completely overflow" },
    { id: "f291", scenario: "They share relationship problems on social media vaguely" },
    { id: "f292", scenario: "They ask to see your phone openly with nothing to hide themselves" },
    { id: "f293", scenario: "They flirt casually with people and see no issue with it" },
    { id: "f294", scenario: "They have a friendship their partner has never met after 2 years" },
    { id: "f295", scenario: "They get visibly uncomfortable when you talk to attractive people" },
    { id: "f296", scenario: "They tag you in things online without asking first" },
    { id: "f297", scenario: "They bring their phone everywhere including the bathroom" },
    { id: "f298", scenario: "They bring up your past relationship mistakes in unrelated arguments" },
    { id: "f299", scenario: "They go through a phase of being completely unavailable without explanation" },
    { id: "f300", scenario: "They're perfect on paper but something just feels slightly off" },
];

// Seeded random number generator (Mulberry32) for consistent shuffle across clients
function mulberry32(a: number) {
    return function () {
        let t = a += 0x6D2B79F5;
        t = Math.imul(t ^ t >>> 15, t | 1);
        t ^= t + Math.imul(t ^ t >>> 7, t | 61);
        return ((t ^ t >>> 14) >>> 0) / 4294967296;
    }
}

export function getFlagCards(count: number, seed?: number): FlagCard[] {
    const shuffled = [...flagCards];
    const currentSeed = seed ?? Math.floor(Math.random() * 1000000);
    const random = mulberry32(currentSeed);

    // Fisher-Yates shuffle with seeded random
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }

    // Return exactly the requested number of cards (no repeats)
    return shuffled.slice(0, Math.min(count, shuffled.length));
}
