export interface WhosMostLikelyCard {
    id: string;
    question: string;
    deck: string;
}

export type DeckType = "normal" | "awkward" | "lust";

export const DECKS: Record<DeckType, { name: string; emoji: string; description: string }> = {
    normal: {
        name: "Normal Mode 😇",
        emoji: "😇",
        description: "Fun & casual questions for everyone.",
    },
    awkward: {
        name: "Awkward Mode 😬",
        emoji: "😬",
        description: "Get ready for some uncomfortable truths.",
    },
    lust: {
        name: "Lust Mode 😈",
        emoji: "😈",
        description: "Spicy 18+ questions to heat things up.",
    },
};

// Normal Deck (100 cards)
const normalDeck: WhosMostLikelyCard[] = [
    { id: "n1", question: "Who is most likely to become famous?", deck: "normal" },
    { id: "n2", question: "Who is most likely to survive a zombie apocalypse?", deck: "normal" },
    { id: "n3", question: "Who is most likely to cry during a sad movie?", deck: "normal" },
    { id: "n4", question: "Who is most likely to win the lottery and lose the ticket?", deck: "normal" },
    { id: "n5", question: "Who is most likely to trip over nothing?", deck: "normal" },
    { id: "n6", question: "Who is most likely to adopt every stray animal they see?", deck: "normal" },
    { id: "n7", question: "Who is most likely to become a billionaire?", deck: "normal" },
    { id: "n8", question: "Who is most likely to talk their way out of a speeding ticket?", deck: "normal" },
    { id: "n9", question: "Who is most likely to forget your name the second you meet?", deck: "normal" },
    { id: "n10", question: "Who is most likely to spend their rent money on takeout?", deck: "normal" },
    { id: "n11", question: "Who is most likely to accidentally set something on fire cooking?", deck: "normal" },
    { id: "n12", question: "Who is most likely to join a cult by accident?", deck: "normal" },
    { id: "n13", question: "Who is most likely to get lost using Google Maps?", deck: "normal" },
    { id: "n14", question: "Who is most likely to become a stand-up comedian?", deck: "normal" },
    { id: "n15", question: "Who is most likely to binge an entire series instead of sleeping?", deck: "normal" },
    { id: "n16", question: "Who is most likely to drop their phone in the toilet?", deck: "normal" },
    { id: "n17", question: "Who is most likely to laugh at the worst possible moment?", deck: "normal" },
    { id: "n18", question: "Who is most likely to marry a stranger in Vegas?", deck: "normal" },
    { id: "n19", question: "Who is most likely to sleep through an earthquake?", deck: "normal" },
    { id: "n20", question: "Who is most likely to eat something off the floor without hesitation?", deck: "normal" },
    { id: "n21", question: "Who is most likely to go viral for something completely unintentional?", deck: "normal" },
    { id: "n22", question: "Who is most likely to get a tattoo they regret within a week?", deck: "normal" },
    { id: "n23", question: "Who is most likely to fall asleep in a meeting with their eyes open?", deck: "normal" },
    { id: "n24", question: "Who is most likely to be late to their own wedding?", deck: "normal" },
    { id: "n25", question: "Who is most likely to have a full conversation with their pet?", deck: "normal" },
    { id: "n26", question: "Who is most likely to scream and run from a spider?", deck: "normal" },
    { id: "n27", question: "Who is most likely to quit their job and move abroad with zero plan?", deck: "normal" },
    { id: "n28", question: "Who is most likely to win a dance battle they didn't ask to be in?", deck: "normal" },
    { id: "n29", question: "Who is most likely to get arrested for something embarrassingly minor?", deck: "normal" },
    { id: "n30", question: "Who is most likely to end up with 10 cats?", deck: "normal" },
    { id: "n31", question: "Who is most likely to buy something off an infomercial at 3am?", deck: "normal" },
    { id: "n32", question: "Who is most likely to write a best-selling book?", deck: "normal" },
    { id: "n33", question: "Who is most likely to spoil a movie in the first 5 minutes?", deck: "normal" },
    { id: "n34", question: "Who is most likely to hold a grudge for 10 years over something tiny?", deck: "normal" },
    { id: "n35", question: "Who is most likely to fake their own death to get out of plans?", deck: "normal" },
    { id: "n36", question: "Who is most likely to be the fun one when drunk?", deck: "normal" },
    { id: "n37", question: "Who is most likely to lock themselves out of the house twice in one week?", deck: "normal" },
    { id: "n38", question: "Who is most likely to invent something completely useless and try to sell it?", deck: "normal" },
    { id: "n39", question: "Who is most likely to go a week without showering and not notice?", deck: "normal" },
    { id: "n40", question: "Who is most likely to spontaneously move abroad with no plan?", deck: "normal" },
    { id: "n41", question: "Who is most likely to win a reality TV show?", deck: "normal" },
    { id: "n42", question: "Who is most likely to dramatically quit their job with a speech?", deck: "normal" },
    { id: "n43", question: "Who is most likely to be the life of the party?", deck: "normal" },
    { id: "n44", question: "Who is most likely to be a morning person who tells everyone about it?", deck: "normal" },
    { id: "n45", question: "Who is most likely to still be awake at 4am for no reason?", deck: "normal" },
    { id: "n46", question: "Who is most likely to cheat at Monopoly and deny it?", deck: "normal" },
    { id: "n47", question: "Who is most likely to forget their own birthday?", deck: "normal" },
    { id: "n48", question: "Who is most likely to win an argument even when they're wrong?", deck: "normal" },
    { id: "n49", question: "Who is most likely to lose their keys every single day?", deck: "normal" },
    { id: "n50", question: "Who is most likely to overpack for a weekend trip?", deck: "normal" },
    { id: "n51", question: "Who is most likely to get scammed by a Nigerian prince email?", deck: "normal" },
    { id: "n52", question: "Who is most likely to get lost in IKEA and give up?", deck: "normal" },
    { id: "n53", question: "Who is most likely to leave you on read for three days then reply 'lol'?", deck: "normal" },
    { id: "n54", question: "Who is most likely to have the messiest room but know where everything is?", deck: "normal" },
    { id: "n55", question: "Who is most likely to talk during a movie and not realize they're doing it?", deck: "normal" },
    { id: "n56", question: "Who is most likely to be the mom or dad of the group?", deck: "normal" },
    { id: "n57", question: "Who is most likely to cancel plans 10 minutes before?", deck: "normal" },
    { id: "n58", question: "Who is most likely to accidentally tell your secret with the best intentions?", deck: "normal" },
    { id: "n59", question: "Who is most likely to become a vegan and not shut up about it?", deck: "normal" },
    { id: "n60", question: "Who is most likely to run a marathon on zero training?", deck: "normal" },
    { id: "n61", question: "Who is most likely to own a snake or a lizard?", deck: "normal" },
    { id: "n62", question: "Who is most likely to survive in the wild for a week?", deck: "normal" },
    { id: "n63", question: "Who is most likely to be the first one on the dance floor?", deck: "normal" },
    { id: "n64", question: "Who is most likely to fall in love with someone they just met?", deck: "normal" },
    { id: "n65", question: "Who is most likely to make everyone laugh without even trying?", deck: "normal" },
    { id: "n66", question: "Who is most likely to plan the best party but stress-spiral while doing it?", deck: "normal" },
    { id: "n67", question: "Who is most likely to be unknowingly in a documentary?", deck: "normal" },
    { id: "n68", question: "Who is most likely to become obsessed with a niche hobby overnight?", deck: "normal" },
    { id: "n69", question: "Who is most likely to cry at a commercial?", deck: "normal" },
    { id: "n70", question: "Who is most likely to show up somewhere completely overdressed?", deck: "normal" },
    { id: "n71", question: "Who is most likely to show up somewhere massively underdressed?", deck: "normal" },
    { id: "n72", question: "Who is most likely to start a business that somehow works?", deck: "normal" },
    { id: "n73", question: "Who is most likely to be on a first-name basis with their Uber driver?", deck: "normal" },
    { id: "n74", question: "Who is most likely to get emotionally attached to a houseplant?", deck: "normal" },
    { id: "n75", question: "Who is most likely to send a text to the wrong person at the worst time?", deck: "normal" },
    { id: "n76", question: "Who is most likely to eat the last slice without asking?", deck: "normal" },
    { id: "n77", question: "Who is most likely to believe every conspiracy theory they read?", deck: "normal" },
    { id: "n78", question: "Who is most likely to turn a 5 minute story into a 45 minute story?", deck: "normal" },
    { id: "n79", question: "Who is most likely to adopt a weird accent after one trip abroad?", deck: "normal" },
    { id: "n80", question: "Who is most likely to get emotionally destroyed by a video game?", deck: "normal" },
    { id: "n81", question: "Who is most likely to show up to a potluck with store-bought food in a homemade dish?", deck: "normal" },
    { id: "n82", question: "Who is most likely to become a politician?", deck: "normal" },
    { id: "n83", question: "Who is most likely to start a podcast nobody asked for?", deck: "normal" },
    { id: "n84", question: "Who is most likely to get personally offended by a bad Wi-Fi connection?", deck: "normal" },
    { id: "n85", question: "Who is most likely to narrate their own life out loud?", deck: "normal" },
    { id: "n86", question: "Who is most likely to have 47 unread tabs open at all times?", deck: "normal" },
    { id: "n87", question: "Who is most likely to cry at a wedding even if they don't know the couple?", deck: "normal" },
    { id: "n88", question: "Who is most likely to jump off something they immediately regret?", deck: "normal" },
    { id: "n89", question: "Who is most likely to live to 100 just to spite everyone?", deck: "normal" },
    { id: "n90", question: "Who is most likely to give a TED Talk nobody asked for at dinner?", deck: "normal" },
    { id: "n91", question: "Who is most likely to show up to the wrong party and just stay anyway?", deck: "normal" },
    { id: "n92", question: "Who is most likely to have a color-coded calendar for their personal life?", deck: "normal" },
    { id: "n93", question: "Who is most likely to book a flight on impulse?", deck: "normal" },
    { id: "n94", question: "Who is most likely to go back for seconds before everyone has had firsts?", deck: "normal" },
    { id: "n95", question: "Who is most likely to stay in a haunted house just to prove a point?", deck: "normal" },
    { id: "n96", question: "Who is most likely to be the one everyone calls at 2am?", deck: "normal" },
    { id: "n97", question: "Who is most likely to become a professional napper?", deck: "normal" },
    { id: "n98", question: "Who is most likely to challenge a stranger to a bet and lose?", deck: "normal" },
    { id: "n99", question: "Who is most likely to get personally invested in a stranger's argument?", deck: "normal" },
    { id: "n100", question: "Who is most likely to end up on a wanted poster in another country?", deck: "normal" },

    // Batch 1 of Expansions
    { id: "n101", question: "Who is most likely to eat food that is definitely expired?", deck: "normal" },
    { id: "n102", question: "Who is most likely to accidentally join a cult without realizing it until the retreat?", deck: "normal" },
    { id: "n103", question: "Who is most likely to become a millionaire by complete accident?", deck: "normal" },
    { id: "n104", question: "Who is most likely to show up a full day early to an event and not notice?", deck: "normal" },
    { id: "n105", question: "Who is most likely to cry at a life insurance commercial?", deck: "normal" },
    { id: "n106", question: "Who is most likely to have 50 alarms set and still oversleep?", deck: "normal" },
    { id: "n107", question: "Who is most likely to keep a borrowed library book for 10 years and move with it?", deck: "normal" },
    { id: "n108", question: "Who is most likely to start a fistfight with an inanimate object and lose?", deck: "normal" },
    { id: "n109", question: "Who is most likely to accidentally send an insulting text to the person it's about?", deck: "normal" },
    { id: "n110", question: "Who is most likely to somehow survive a zombie apocalypse because the zombies just ignored them?", deck: "normal" },
    { id: "n111", question: "Who is most likely to forget their own birthday until someone reminds them?", deck: "normal" },
    { id: "n112", question: "Who is most likely to wear gym clothes to a vaguely formal event?", deck: "normal" },
    { id: "n113", question: "Who is most likely to be genuinely convinced they can communicate with animals?", deck: "normal" },
    { id: "n114", question: "Who is most likely to trip on a completely flat surface?", deck: "normal" },
    { id: "n115", question: "Who is most likely to drop their phone in the toilet more than once?", deck: "normal" },
    { id: "n116", question: "Who is most likely to get a tattoo they deeply regret within 24 hours?", deck: "normal" },
    { id: "n117", question: "Who is most likely to spend an hour trying to find their glasses while wearing them?", deck: "normal" },
    { id: "n118", question: "Who is most likely to laugh at a joke they didn't hear?", deck: "normal" },
    { id: "n119", question: "Who is most likely to get scammed by an incredibly obvious phishing email?", deck: "normal" },
    { id: "n120", question: "Who is most likely to walk into a glass door while waving at someone?", deck: "normal" },
    { id: "n121", question: "Who is most likely to try a DIY project that ends with a hospital visit?", deck: "normal" },
    { id: "n122", question: "Who is most likely to leave their wallet on the roof of their car and drive off?", deck: "normal" },
    { id: "n123", question: "Who is most likely to wave back at someone who was waving at the person behind them?", deck: "normal" },
    { id: "n124", question: "Who is most likely to accidentally drink from someone else's glass and pretend they didn't notice?", deck: "normal" },
    { id: "n125", question: "Who is most likely to fall asleep in a movie theater and snore loudly?", deck: "normal" },
    { id: "n126", question: "Who is most likely to forget what they're saying mid-sentence on a regular basis?", deck: "normal" },
    { id: "n127", question: "Who is most likely to confidently say a word completely wrong for years?", deck: "normal" },
    { id: "n128", question: "Who is most likely to accidentally lock themselves out of their house in their pajamas?", deck: "normal" },
    { id: "n129", question: "Who is most likely to pull a push door multiple times before realizing?", deck: "normal" },
    { id: "n130", question: "Who is most likely to put their shirt on backwards and not notice until the end of the day?", deck: "normal" },
    { id: "n131", question: "Who is most likely to start a story, get distracted, and never finish it?", deck: "normal" },
    { id: "n132", question: "Who is most likely to talk themselves out of a brilliant idea?", deck: "normal" },
    { id: "n133", question: "Who is most likely to lose their boarding pass at airport security?", deck: "normal" },
    { id: "n134", question: "Who is most likely to get genuinely angry at a video game NPC?", deck: "normal" },
    { id: "n135", question: "Who is most likely to leave a completely full coffee cup on the roof of their car?", deck: "normal" },
    { id: "n136", question: "Who is most likely to spend entirely too much money on a bizarre hobby?", deck: "normal" },
    { id: "n137", question: "Who is most likely to adopt a wildly aggressive dog because 'it looked sad'?", deck: "normal" },
    { id: "n138", question: "Who is most likely to confidently give wrong directions to a tourist?", deck: "normal" },
    { id: "n139", question: "Who is most likely to mistakenly throw away their keys and keep the trash?", deck: "normal" },
    { id: "n140", question: "Who is most likely to choke on water while sitting perfectly still?", deck: "normal" },
    { id: "n141", question: "Who is most likely to text 'here' when they are still 15 minutes away?", deck: "normal" },
    { id: "n142", question: "Who is most likely to reply to a text completely in their head and never send it?", deck: "normal" },
    { id: "n143", question: "Who is most likely to start a rumor accidentally because they misheard something?", deck: "normal" },
    { id: "n144", question: "Who is most likely to insist they aren't tired while clearly falling asleep?", deck: "normal" },
    { id: "n145", question: "Who is most likely to get wildly competitive at a casual board game night?", deck: "normal" },
    { id: "n146", question: "Who is most likely to completely ruin a surprise party by spilling the secret?", deck: "normal" },
    { id: "n147", question: "Who is most likely to fall for a fake news headline on social media?", deck: "normal" },
    { id: "n148", question: "Who is most likely to accidentally set the fire alarm off while cooking?", deck: "normal" },
    { id: "n149", question: "Who is most likely to over-prepare for an apocalypse that isn't happening?", deck: "normal" },
    { id: "n150", question: "Who is most likely to spend 3 hours curating a playlist and not listen to it?", deck: "normal" },
    { id: "n151", question: "Who is most likely to have the worst autocorrect disasters?", deck: "normal" },
    { id: "n152", question: "Who is most likely to refuse to follow a recipe and ruin dinner?", deck: "normal" },
    { id: "n153", question: "Who is most likely to confidently argue a point while being 100% incorrect?", deck: "normal" },
    { id: "n154", question: "Who is most likely to accidentally call a teacher or boss 'Mom'?", deck: "normal" },
    { id: "n155", question: "Who is most likely to be found wandering around a parking lot looking for their car?", deck: "normal" },
    { id: "n156", question: "Who is most likely to start clapping in a movie theater when the movie ends?", deck: "normal" },
    { id: "n157", question: "Who is most likely to invent a slang word and force everyone to use it?", deck: "normal" },
    { id: "n158", question: "Who is most likely to buy a gym membership and never go?", deck: "normal" },
    { id: "n159", question: "Who is most likely to try negotiating prices at a corporate retail store?", deck: "normal" },
    { id: "n160", question: "Who is most likely to dramatically quit their job and immediately regret it?", deck: "normal" },
    { id: "n161", question: "Who is most likely to fall in love with a fictional character?", deck: "normal" },
    { id: "n162", question: "Who is most likely to talk at the movie screen during a dramatic scene?", deck: "normal" },
    { id: "n163", question: "Who is most likely to try and pet a wild animal they shouldn't?", deck: "normal" },
    { id: "n164", question: "Who is most likely to leave the stove on and turn back halfway to work?", deck: "normal" },
    { id: "n165", question: "Who is most likely to loudly complain about traffic while being the cause of it?", deck: "normal" },
    { id: "n166", question: "Who is most likely to order something absurdly expensive without checking the price?", deck: "normal" },
    { id: "n167", question: "Who is most likely to accidentally respond 'you too' when a waiter says 'enjoy your meal'?", deck: "normal" },
    { id: "n168", question: "Who is most likely to accidentally bring home someone else's pet?", deck: "normal" },
    { id: "n169", question: "Who is most likely to show up an hour late with an iced coffee and a terrible excuse?", deck: "normal" },
    { id: "n170", question: "Who is most likely to insist on going the scenic route and getting incredibly lost?", deck: "normal" },
    { id: "n171", question: "Who is most likely to accidentally buy tickets for the wrong movie or flight?", deck: "normal" },
    { id: "n172", question: "Who is most likely to lose a passport the morning of an international flight?", deck: "normal" },
    { id: "n173", question: "Who is most likely to accidentally like a photo from 6 years ago while stalking?", deck: "normal" },
    { id: "n174", question: "Who is most likely to eat the garnish off a plate thinking it's food?", deck: "normal" },
    { id: "n175", question: "Who is most likely to adopt a weird new aesthetic every few months?", deck: "normal" },
    { id: "n176", question: "Who is most likely to write an angry review for a place they never visited?", deck: "normal" },
    { id: "n177", question: "Who is most likely to wear a Halloween costume when it isn't Halloween?", deck: "normal" },
    { id: "n178", question: "Who is most likely to trip up the stairs instead of down?", deck: "normal" },
    { id: "n179", question: "Who is most likely to be completely unaffected by caffeine?", deck: "normal" },
    { id: "n180", question: "Who is most likely to be terrible at keeping a secret twist in a movie?", deck: "normal" },
    { id: "n181", question: "Who is most likely to get randomly selected for prolonged security screening?", deck: "normal" },
    { id: "n182", question: "Who is most likely to spend half their paycheck on an absurdly niche collection?", deck: "normal" },
    { id: "n183", question: "Who is most likely to start packing 10 minutes before leaving for a trip?", deck: "normal" },
    { id: "n184", question: "Who is most likely to try doing a backflip and completely faceplant?", deck: "normal" },
    { id: "n185", question: "Who is most likely to get a parking ticket completely unknowingly for weeks?", deck: "normal" },
    { id: "n186", question: "Who is most likely to get wildly sunburned on a cloudy day?", deck: "normal" },
    { id: "n187", question: "Who is most likely to forget what day of the week it is on a Wednesday?", deck: "normal" },
    { id: "n188", question: "Who is most likely to accidentally delete a massive, important document?", deck: "normal" },
    { id: "n189", question: "Who is most likely to refuse to use GPS and get horribly lost to prove a point?", deck: "normal" },
    { id: "n190", question: "Who is most likely to dramatically trip while trying to look cool?", deck: "normal" },
    { id: "n191", question: "Who is most likely to somehow break something by trying to fix it?", deck: "normal" },
    { id: "n192", question: "Who is most likely to stubbornly refuse an umbrella in a torrential downpour?", deck: "normal" },
    { id: "n193", question: "Who is most likely to be totally unaware they are being heavily flirted with?", deck: "normal" },
    { id: "n194", question: "Who is most likely to sleep through a fire alarm entirely?", deck: "normal" },
    { id: "n195", question: "Who is most likely to start an intense diet on Monday and quit by Tuesday morning?", deck: "normal" },
    { id: "n196", question: "Who is most likely to talk directly to dogs on the street instead of their owners?", deck: "normal" },
    { id: "n197", question: "Who is most likely to leave the house in mismatched shoes?", deck: "normal" },
    { id: "n198", question: "Who is most likely to confidently explain the plot of a movie they've never seen?", deck: "normal" },
    { id: "n199", question: "Who is most likely to lose an argument they were initially winning because they kept talking?", deck: "normal" },
    { id: "n200", question: "Who is most likely to accidentally wear their shirt inside-out for an entire day?", deck: "normal" },

    // Batch 2 of Expansions (bringing total to 300)
    { id: "n201", question: "Who is most likely to cry when they get angry?", deck: "normal" },
    { id: "n202", question: "Who is most likely to win a reality TV show by being completely ruthless?", deck: "normal" },
    { id: "n203", question: "Who is most likely to ruin a joke by trying to explain why it's funny?", deck: "normal" },
    { id: "n204", question: "Who is most likely to successfully fake an injury to get out of doing something?", deck: "normal" },
    { id: "n205", question: "Who is most likely to get blocked by a celebrity on social media?", deck: "normal" },
    { id: "n206", question: "Who is most likely to buy a highly specific kitchen gadget and use it once?", deck: "normal" },
    { id: "n207", question: "Who is most likely to enthusiastically wave at someone who wasn't waving at them?", deck: "normal" },
    { id: "n208", question: "Who is most likely to fall asleep during a highly suspenseful thriller movie?", deck: "normal" },
    { id: "n209", question: "Who is most likely to accidentally eat a dog treat thinking it's a cookie?", deck: "normal" },
    { id: "n210", question: "Who is most likely to create a fake email address just to get a 10% discount?", deck: "normal" },
    { id: "n211", question: "Who is most likely to stubbornly try to carry all the groceries in one trip and drop them?", deck: "normal" },
    { id: "n212", question: "Who is most likely to accidentally steal something from a store without realizing until they get home?", deck: "normal" },
    { id: "n213", question: "Who is most likely to go viral for doing something completely embarrassing?", deck: "normal" },
    { id: "n214", question: "Who is most likely to laugh hysterically at a funeral or entirely inappropriate moment?", deck: "normal" },
    { id: "n215", question: "Who is most likely to start a dramatic argument over the rules of Uno?", deck: "normal" },
    { id: "n216", question: "Who is most likely to enthusiastically sing the wrong lyrics with complete confidence?", deck: "normal" },
    { id: "n217", question: "Who is most likely to accidentally like an ex's new partner's photo from 3 years ago?", deck: "normal" },
    { id: "n218", question: "Who is most likely to give terrible advice but sound incredibly wise doing it?", deck: "normal" },
    { id: "n219", question: "Who is most likely to get emotionally attached to an inanimate object?", deck: "normal" },
    { id: "n220", question: "Who is most likely to get stuck in a bathroom at a party?", deck: "normal" },
    { id: "n221", question: "Who is most likely to spend an entire party talking exclusively to the host's pet?", deck: "normal" },
    { id: "n222", question: "Who is most likely to somehow break a bone while sleeping?", deck: "normal" },
    { id: "n223", question: "Who is most likely to convincingly fake fluency in a language they don't speak?", deck: "normal" },
    { id: "n224", question: "Who is most likely to accidentally condition themselves like Pavlov's dog?", deck: "normal" },
    { id: "n225", question: "Who is most likely to confidently give a completely wrong answer in trivia and convince everyone it's right?", deck: "normal" },
    { id: "n226", question: "Who is most likely to complain about being full and then eat an entire dessert?", deck: "normal" },
    { id: "n227", question: "Who is most likely to accidentally join a pyramid scheme?", deck: "normal" },
    { id: "n228", question: "Who is most likely to get lost in their own hometown?", deck: "normal" },
    { id: "n229", question: "Who is most likely to walk into a spiderweb and start doing martial arts?", deck: "normal" },
    { id: "n230", question: "Who is most likely to randomly decide to move to a different country on a Tuesday?", deck: "normal" },
    { id: "n231", question: "Who is most likely to aggressively honk their horn at a car that turns out to be a police cruiser?", deck: "normal" },
    { id: "n232", question: "Who is most likely to dramatically quit a game they are losing and say it's dumb anyway?", deck: "normal" },
    { id: "n233", question: "Who is most likely to accidentally swallow a bug while talking?", deck: "normal" },
    { id: "n234", question: "Who is most likely to try and pay for something over $100 entirely in loose change?", deck: "normal" },
    { id: "n235", question: "Who is most likely to get overly competitive at a children's game?", deck: "normal" },
    { id: "n236", question: "Who is most likely to accidentally insult someone while trying to give them a compliment?", deck: "normal" },
    { id: "n237", question: "Who is most likely to try an extreme sport and immediately regret it mid-air?", deck: "normal" },
    { id: "n238", question: "Who is most likely to spend days researching a $15 purchase?", deck: "normal" },
    { id: "n239", question: "Who is most likely to dramatically talk to themselves in the mirror?", deck: "normal" },
    { id: "n240", question: "Who is most likely to invent a conspiracy theory completely accidentally?", deck: "normal" },
    { id: "n241", question: "Who is most likely to forget they ordered food until the delivery person knocks?", deck: "normal" },
    { id: "n242", question: "Who is most likely to enthusiastically start a hobby and abandon it within 48 hours?", deck: "normal" },
    { id: "n243", question: "Who is most likely to accidentally start a fire while trying to boil water?", deck: "normal" },
    { id: "n244", question: "Who is most likely to get highly offended on behalf of someone who isn't offended at all?", deck: "normal" },
    { id: "n245", question: "Who is most likely to bring a full acoustic guitar to a party and start playing unprompted?", deck: "normal" },
    { id: "n246", question: "Who is most likely to try and barter at a major chain grocery store?", deck: "normal" },
    { id: "n247", question: "Who is most likely to leave a highly dramatic one-star review on Yelp?", deck: "normal" },
    { id: "n248", question: "Who is most likely to take a 'Which kind of bread are you' quiz entirely too seriously?", deck: "normal" },
    { id: "n249", question: "Who is most likely to get genuinely angry at a friend because of something they did in a dream?", deck: "normal" },
    { id: "n250", question: "Who is most likely to accidentally wear two different shoes to work?", deck: "normal" },
    { id: "n251", question: "Who is most likely to start a sentence with 'I'm not gonna lie' and then lie?", deck: "normal" },
    { id: "n252", question: "Who is most likely to get surprisingly emotional while watching a cartoon?", deck: "normal" },
    { id: "n253", question: "Who is most likely to passionately debate a topic they know absolutely nothing about?", deck: "normal" },
    { id: "n254", question: "Who is most likely to try and sneak their own snacks into a movie theater and drop them everywhere?", deck: "normal" },
    { id: "n255", question: "Who is most likely to try a 'life hack' they saw online that ends in total disaster?", deck: "normal" },
    { id: "n256", question: "Who is most likely to accidentally send an intimate message to the family group chat?", deck: "normal" },
    { id: "n257", question: "Who is most likely to get visibly irritated when someone breathes too loudly?", deck: "normal" },
    { id: "n258", question: "Who is most likely to hold a door open for someone way too far away?", deck: "normal" },
    { id: "n259", question: "Who is most likely to enthusiastically start a slow clap that nobody else joins?", deck: "normal" },
    { id: "n260", question: "Who is most likely to confidently open a push door by pulling as hard as they can?", deck: "normal" },
    { id: "n261", question: "Who is most likely to successfully survive in the wilderness using only internet knowledge?", deck: "normal" },
    { id: "n262", question: "Who is most likely to pretend to be on an important phone call to avoid social interaction?", deck: "normal" },
    { id: "n263", question: "Who is most likely to completely misread the room and make a joke at the worst possible time?", deck: "normal" },
    { id: "n264", question: "Who is most likely to accidentally say 'love you' to a customer service representative?", deck: "normal" },
    { id: "n265", question: "Who is most likely to accidentally get onto the wrong train and just accept their new life?", deck: "normal" },
    { id: "n266", question: "Who is most likely to buy ridiculously expensive clothes for their pets?", deck: "normal" },
    { id: "n267", question: "Who is most likely to start cleaning vigorously only when people are coming over?", deck: "normal" },
    { id: "n268", question: "Who is most likely to apologize to an inanimate object after bumping into it?", deck: "normal" },
    { id: "n269", question: "Who is most likely to be completely oblivious that someone is flirting with them?", deck: "normal" },
    { id: "n270", question: "Who is most likely to dramatically whisper 'I knew it' while watching a completely predictable movie?", deck: "normal" },
    { id: "n271", question: "Who is most likely to confidently order food in a foreign language and get something totally different?", deck: "normal" },
    { id: "n272", question: "Who is most likely to stubbornly refuse to look at the instructions while assembling furniture?", deck: "normal" },
    { id: "n273", question: "Who is most likely to loudly judge reality TV stars while sitting on the couch eating junk food?", deck: "normal" },
    { id: "n274", question: "Who is most likely to mistakenly put salt in their coffee instead of sugar?", deck: "normal" },
    { id: "n275", question: "Who is most likely to bring a massive suitcase for a one-night trip?", deck: "normal" },
    { id: "n276", question: "Who is most likely to randomly get obsessed with a very specific era of history for a week?", deck: "normal" },
    { id: "n277", question: "Who is most likely to start a diet by throwing away all the junk food, and buying it all back the next day?", deck: "normal" },
    { id: "n278", question: "Who is most likely to reply 'Haha yeah' to a question because they weren't listening?", deck: "normal" },
    { id: "n279", question: "Who is most likely to take a joke way too far and ruin the vibe?", deck: "normal" },
    { id: "n280", question: "Who is most likely to genuinely believe their pet can understand English perfectly?", deck: "normal" },
    { id: "n281", question: "Who is most likely to get completely lost in thought and stare blankly at someone making them uncomfortable?", deck: "normal" },
    { id: "n282", question: "Who is most likely to stubbornly hold onto a completely debunked 'fact'?", deck: "normal" },
    { id: "n283", question: "Who is most likely to loudly ask 'What? No way!' to a story they've already heard three times?", deck: "normal" },
    { id: "n284", question: "Who is most likely to leave half-empty water bottles all over their room?", deck: "normal" },
    { id: "n285", question: "Who is most likely to enthusiastically jump into a pool holding their phone?", deck: "normal" },
    { id: "n286", question: "Who is most likely to dramatically read out their own horoscope as if it's absolute truth?", deck: "normal" },
    { id: "n287", question: "Who is most likely to mysteriously disappear during a night out without telling anyone?", deck: "normal" },
    { id: "n288", question: "Who is most likely to accidentally like a terrible movie and vigorously defend it?", deck: "normal" },
    { id: "n289", question: "Who is most likely to completely fabricate a story to get out of a minor social obligation?", deck: "normal" },
    { id: "n290", question: "Who is most likely to try and 'fix' someone who actively does not want to be fixed?", deck: "normal" },
    { id: "n291", question: "Who is most likely to start a deeply serious conversation at 2 AM on a Tuesday?", deck: "normal" },
    { id: "n292", question: "Who is most likely to show up aggressively over-dressed to a casual hangout?", deck: "normal" },
    { id: "n293", question: "Who is most likely to dramatically act like their life is over because of a minor inconvenience?", deck: "normal" },
    { id: "n294", question: "Who is most likely to genuinely believe they could win an Olympic medal with a few months of training?", deck: "normal" },
    { id: "n295", question: "Who is most likely to unironically start using outdated slang?", deck: "normal" },
    { id: "n296", question: "Who is most likely to stubbornly keep an old, dying electronic device instead of buying a new one?", deck: "normal" },
    { id: "n297", question: "Who is most likely to have extreme anxiety about opening a biscuit tube?", deck: "normal" },
    { id: "n298", question: "Who is most likely to leave the house without their keys but perfectly remember a song from 2005?", deck: "normal" },
    { id: "n299", question: "Who is most likely to get genuinely angry when a character dies in a book?", deck: "normal" },
    { id: "n300", question: "Who is most likely to stubbornly insist they have a great sense of direction right before getting lost?", deck: "normal" }
];

// Awkward Deck (100 cards)
const awkwardDeck: WhosMostLikelyCard[] = [
    { id: "a1", question: "Who is most likely to stalk an ex on social media?", deck: "awkward" },
    { id: "a2", question: "Who is most likely to fart in a crowded elevator?", deck: "awkward" },
    { id: "a3", question: "Who is most likely to lie about their age?", deck: "awkward" },
    { id: "a4", question: "Who is most likely to record a conversation without telling anyone?", deck: "awkward" },
    { id: "a5", question: "Who is most likely to check their phone during sex?", deck: "awkward" },
    { id: "a6", question: "Who is most likely to have a secret crush on a friend's partner?", deck: "awkward" },
    { id: "a7", question: "Who is most likely to spread a rumor?", deck: "awkward" },
    { id: "a8", question: "Who is most likely to go days without showering?", deck: "awkward" },
    { id: "a9", question: "Who is most likely to steal something small?", deck: "awkward" },
    { id: "a10", question: "Who is most likely to have an embarrassing nickname?", deck: "awkward" },
    { id: "a11", question: "Who is most likely to pick their nose in public?", deck: "awkward" },
    { id: "a12", question: "Who is most likely to be the most jealous?", deck: "awkward" },
    { id: "a13", question: "Who is most likely to look through someone else's phone?", deck: "awkward" },
    { id: "a14", question: "Who is most likely to cheat on a test?", deck: "awkward" },
    { id: "a15", question: "Who is most likely to ghost someone?", deck: "awkward" },
    { id: "a16", question: "Who is most likely to be involved in a scandal?", deck: "awkward" },
    { id: "a17", question: "Who is most likely to pee in the pool?", deck: "awkward" },
    { id: "a18", question: "Who is most likely to wear weird underwear?", deck: "awkward" },
    { id: "a19", question: "Who is most likely to have the strangest fetish?", deck: "awkward" },
    { id: "a20", question: "Who is most likely to date someone for their money?", deck: "awkward" },
    { id: "a21", question: "Who is most likely to have a fake ID?", deck: "awkward" },
    { id: "a22", question: "Who is most likely to get caught in a lie?", deck: "awkward" },
    { id: "a23", question: "Who is most likely to eavesdrop on a conversation?", deck: "awkward" },
    { id: "a24", question: "Who is most likely to re-gift a present?", deck: "awkward" },
    { id: "a25", question: "Who is most likely to pretend to like a gift?", deck: "awkward" },
    { id: "a26", question: "Who is most likely to eat someone else's food in the fridge?", deck: "awkward" },
    { id: "a27", question: "Who is most likely to hook up with an ex?", deck: "awkward" },
    { id: "a28", question: "Who is most likely to have a one-night stand?", deck: "awkward" },
    { id: "a29", question: "Who is most likely to be the worst kisser?", deck: "awkward" },
    { id: "a30", question: "Who is most likely to say the wrong name in bed?", deck: "awkward" },
    { id: "a31", question: "Who is most likely to clog a toilet at a party?", deck: "awkward" },
    { id: "a32", question: "Who is most likely to forget to flush?", deck: "awkward" },
    { id: "a33", question: "Who is most likely to accidentally flirt with someone's parent?", deck: "awkward" },
    { id: "a34", question: "Who is most likely to have a secret family?", deck: "awkward" },
    { id: "a35", question: "Who is most likely to fake an orgasm?", deck: "awkward" },
    { id: "a36", question: "Who is most likely to flirt to get what they want?", deck: "awkward" },
    { id: "a37", question: "Who is most likely to have a criminal record?", deck: "awkward" },
    { id: "a38", question: "Who is most likely to break a promise?", deck: "awkward" },
    { id: "a39", question: "Who is most likely to reveal a secret?", deck: "awkward" },
    { id: "a40", question: "Who is most likely to be high maintenance?", deck: "awkward" },
    { id: "a41", question: "Who is most likely to be a gold digger?", deck: "awkward" },
    { id: "a42", question: "Who is most likely to judge others silently?", deck: "awkward" },
    { id: "a43", question: "Who is most likely to trauma-dump on a first date?", deck: "awkward" },
    { id: "a44", question: "Who is most likely to borrow money and not pay it back?", deck: "awkward" },
    { id: "a45", question: "Who is most likely to be a drama queen?", deck: "awkward" },
    { id: "a46", question: "Who is most likely to have plastic surgery?", deck: "awkward" },
    { id: "a47", question: "Who is most likely to be catfished?", deck: "awkward" },
    { id: "a48", question: "Who is most likely to catfish someone?", deck: "awkward" },
    { id: "a49", question: "Who is most likely to have the most embarrassing search history?", deck: "awkward" },
    { id: "a50", question: "Who is most likely to send a text to the wrong person?", deck: "awkward" },
    { id: "a51", question: "Who is most likely to laugh at a funeral?", deck: "awkward" },
    { id: "a52", question: "Who is most likely to be late due to vanity?", deck: "awkward" },
    { id: "a53", question: "Who is most likely to take credit for someone else's work?", deck: "awkward" },
    { id: "a54", question: "Who is most likely to slide into a celebrity's DMs?", deck: "awkward" },
    { id: "a55", question: "Who is most likely to complain at a restaurant?", deck: "awkward" },
    { id: "a56", question: "Who is most likely to screenshot your texts and share them?", deck: "awkward" },
    { id: "a57", question: "Who is most likely to talk about themselves all night?", deck: "awkward" },
    { id: "a58", question: "Who is most likely to interrupt others?", deck: "awkward" },
    { id: "a59", question: "Who is most likely to be on their phone during a date?", deck: "awkward" },
    { id: "a60", question: "Who is most likely to swipe left on everyone?", deck: "awkward" },
    { id: "a61", question: "Who is most likely to use a cheesy pickup line?", deck: "awkward" },
    { id: "a62", question: "Who is most likely to get friend-zoned?", deck: "awkward" },
    { id: "a63", question: "Who is most likely to fall only for bad boys/girls?", deck: "awkward" },
    { id: "a64", question: "Who is most likely to be single forever?", deck: "awkward" },
    { id: "a65", question: "Who is most likely to get married for money?", deck: "awkward" },
    { id: "a66", question: "Who is most likely to have a secret addiction?", deck: "awkward" },
    { id: "a67", question: "Who is most likely to lie on their resume?", deck: "awkward" },
    { id: "a68", question: "Who is most likely to get fired?", deck: "awkward" },
    { id: "a69", question: "Who is most likely to have a workplace romance?", deck: "awkward" },
    { id: "a70", question: "Who is most likely to steal office supplies?", deck: "awkward" },
    { id: "a71", question: "Who is most likely to suck up to the boss?", deck: "awkward" },
    { id: "a72", question: "Who is most likely to panic in a crisis?", deck: "awkward" },
    { id: "a73", question: "Who is most likely to be the first to die in a horror movie?", deck: "awkward" },
    { id: "a74", question: "Who is most likely to betray a friend?", deck: "awkward" },
    { id: "a75", question: "Who is most likely to keep a lost wallet?", deck: "awkward" },
    { id: "a76", question: "Who is most likely to cheat at cards?", deck: "awkward" },
    { id: "a77", question: "Who is most likely to have the worst tattoo?", deck: "awkward" },
    { id: "a78", question: "Who is most likely to wear socks with sandals?", deck: "awkward" },
    { id: "a79", question: "Who is most likely to have a mullet?", deck: "awkward" },
    { id: "a80", question: "Who is most likely to believe a conspiracy theory?", deck: "awkward" },
    { id: "a81", question: "Who is most likely to be an anti-vaxxer?", deck: "awkward" },
    { id: "a82", question: "Who is most likely to join a pyramid scheme?", deck: "awkward" },
    { id: "a83", question: "Who is most likely to get a face tattoo?", deck: "awkward" },
    { id: "a84", question: "Who is most likely to run away from responsibilities?", deck: "awkward" },
    { id: "a85", question: "Who is most likely to be a narcissist?", deck: "awkward" },
    { id: "a86", question: "Who is most likely to manipulate others?", deck: "awkward" },
    { id: "a87", question: "Who is most likely to start a fight?", deck: "awkward" },
    { id: "a88", question: "Who is most likely to be the loudest neighbor?", deck: "awkward" },
    { id: "a89", question: "Who is most likely to not tip?", deck: "awkward" },
    { id: "a90", question: "Who is most likely to be rude to waiters?", deck: "awkward" },
    { id: "a91", question: "Who is most likely to gaslight someone without even realizing?", deck: "awkward" },
    { id: "a92", question: "Who is most likely to text their ex at a party?", deck: "awkward" },
    { id: "a93", question: "Who is most likely to spoil a surprise party?", deck: "awkward" },
    { id: "a94", question: "Who is most likely to be the worst roommate?", deck: "awkward" },
    { id: "a95", question: "Who is most likely to steal the covers?", deck: "awkward" },
    { id: "a96", question: "Who is most likely to snore the loudest?", deck: "awkward" },
    { id: "a97", question: "Who is most likely to talk in their sleep?", deck: "awkward" },
    { id: "a98", question: "Who is most likely to have cried in a public bathroom recently?", deck: "awkward" },
    { id: "a99", question: "Who is most likely to fake sick and then post going out online?", deck: "awkward" },
    { id: "a100", question: "Who is most likely to have the weirdest laugh?", deck: "awkward" },
];

// Lust Deck (18+) (100 cards)
const lustDeck: WhosMostLikelyCard[] = [
    { id: "x1", question: "Who is most likely to cum first?", deck: "lust" },
    { id: "x2", question: "Who is most likely to initiate sex?", deck: "lust" },
    { id: "x3", question: "Who is most likely to want public sex?", deck: "lust" },
    { id: "x4", question: "Who is most likely to watch porn daily?", deck: "lust" },
    { id: "x5", question: "Who is most likely to have a sex tape?", deck: "lust" },
    { id: "x6", question: "Who is most likely to be the louder moaner?", deck: "lust" },
    { id: "x7", question: "Who is most likely to be into BDSM?", deck: "lust" },
    { id: "x8", question: "Who is most likely to want a threesome?", deck: "lust" },
    { id: "x9", question: "Who is most likely to suggest roleplay?", deck: "lust" },
    { id: "x10", question: "Who is most likely to be dominant in bed?", deck: "lust" },
    { id: "x11", question: "Who is most likely to be submissive in bed?", deck: "lust" },
    { id: "x12", question: "Who is most likely to send a risky nude?", deck: "lust" },
    { id: "x13", question: "Who is most likely to have the higher body count?", deck: "lust" },
    { id: "x14", question: "Who is most likely to be kinky?", deck: "lust" },
    { id: "x15", question: "Who is most likely to try anal?", deck: "lust" },
    { id: "x16", question: "Who is most likely to own sex toys?", deck: "lust" },
    { id: "x17", question: "Who is most likely to have a foot fetish?", deck: "lust" },
    { id: "x18", question: "Who is most likely to talk dirty?", deck: "lust" },
    { id: "x19", question: "Who is most likely to fall asleep after sex?", deck: "lust" },
    { id: "x20", question: "Who is most likely to want morning sex?", deck: "lust" },
    { id: "x21", question: "Who is most likely to be up for a quickie?", deck: "lust" },
    { id: "x22", question: "Who is most likely to get turned on the easiest?", deck: "lust" },
    { id: "x23", question: "Who is most likely to have had sex in a car?", deck: "lust" },
    { id: "x24", question: "Who is most likely to strip for their partner?", deck: "lust" },
    { id: "x25", question: "Who is most likely to like it rough?", deck: "lust" },
    { id: "x26", question: "Who is most likely to like biting?", deck: "lust" },
    { id: "x27", question: "Who is most likely to like scratching?", deck: "lust" },
    { id: "x28", question: "Who is most likely to climax from foreplay alone?", deck: "lust" },
    { id: "x29", question: "Who is most likely to experiment with food in bed?", deck: "lust" },
    { id: "x30", question: "Who is most likely to have an unexpected orgasm?", deck: "lust" },
    { id: "x31", question: "Who is most likely to make the first move?", deck: "lust" },
    { id: "x32", question: "Who is most likely to think about sex all day?", deck: "lust" },
    { id: "x33", question: "Who is most likely to masturbate at work?", deck: "lust" },
    { id: "x34", question: "Who is most likely to get caught having sex?", deck: "lust" },
    { id: "x35", question: "Who is most likely to give the best head?", deck: "lust" },
    { id: "x36", question: "Who is most likely to want sex every day?", deck: "lust" },
    { id: "x37", question: "Who is most likely to say no to sex?", deck: "lust" },
    { id: "x38", question: "Who is most likely to lie about being turned on?", deck: "lust" },
    { id: "x39", question: "Who is most likely to be adventurous in bed?", deck: "lust" },
    { id: "x40", question: "Who is most likely to suggest using a blindfold?", deck: "lust" },
    { id: "x41", question: "Who is most likely to like being tied up?", deck: "lust" },
    { id: "x42", question: "Who is most likely to want to tie their partner up?", deck: "lust" },
    { id: "x43", question: "Who is most likely to like spanking?", deck: "lust" },
    { id: "x44", question: "Who is most likely to be the best lover?", deck: "lust" },
    { id: "x45", question: "Who is most likely to be shy about their body?", deck: "lust" },
    { id: "x46", question: "Who is most likely to walk around naked?", deck: "lust" },
    { id: "x47", question: "Who is most likely to like watching their partner pleasure themselves?", deck: "lust" },
    { id: "x48", question: "Who is most likely to pleasure themselves in front of their partner?", deck: "lust" },
    { id: "x49", question: "Who is most likely to want to visit a strip club?", deck: "lust" },
    { id: "x50", question: "Who is most likely to pay for sex?", deck: "lust" },
    { id: "x51", question: "Who is most likely to have a secret sex diary?", deck: "lust" },
    { id: "x52", question: "Who is most likely to get turned on by danger?", deck: "lust" },
    { id: "x53", question: "Who is most likely to have sex on a first date?", deck: "lust" },
    { id: "x54", question: "Who is most likely to sleep with a stranger?", deck: "lust" },
    { id: "x55", question: "Who is most likely to suggest a teacher/student roleplay?", deck: "lust" },
    { id: "x56", question: "Who is most likely to have a detailed celebrity fantasy they've never told anyone?", deck: "lust" },
    { id: "x57", question: "Who is most likely to be polyamorous?", deck: "lust" },
    { id: "x58", question: "Who is most likely to swing?", deck: "lust" },
    { id: "x59", question: "Who is most likely to watch hentai?", deck: "lust" },
    { id: "x60", question: "Who is most likely to read erotica?", deck: "lust" },
    { id: "x61", question: "Who is most likely to own handcuffs?", deck: "lust" },
    { id: "x62", question: "Who is most likely to enjoy edging their partner until they beg?", deck: "lust" },
    { id: "x63", question: "Who is most likely to give a massage that leads to sex?", deck: "lust" },
    { id: "x64", question: "Who is most likely to suggest shower sex?", deck: "lust" },
    { id: "x65", question: "Who is most likely to suggest beach sex?", deck: "lust" },
    { id: "x66", question: "Who is most likely to suggest outdoor sex?", deck: "lust" },
    { id: "x67", question: "Who is most likely to get loud during sex?", deck: "lust" },
    { id: "x68", question: "Who is most likely to keep their eyes open during sex?", deck: "lust" },
    { id: "x69", question: "Who is most likely to ask 'do you like that?' constantly?", deck: "lust" },
    { id: "x70", question: "Who is most likely to cuddle after sex?", deck: "lust" },
    { id: "x71", question: "Who is most likely to get up and leave after sex?", deck: "lust" },
    { id: "x72", question: "Who is most likely to want round two immediately?", deck: "lust" },
    { id: "x73", question: "Who is most likely to fake enjoyment?", deck: "lust" },
    { id: "x74", question: "Who is most likely to try a new position?", deck: "lust" },
    { id: "x75", question: "Who is most likely to suggest the 69 position?", deck: "lust" },
    { id: "x76", question: "Who is most likely to like doggy style best?", deck: "lust" },
    { id: "x77", question: "Who is most likely to like missionary best?", deck: "lust" },
    { id: "x78", question: "Who is most likely to like cowgirl best?", deck: "lust" },
    { id: "x79", question: "Who is most likely to have sex in a bathroom?", deck: "lust" },
    { id: "x80", question: "Who is most likely to have sex in a movie theater?", deck: "lust" },
    { id: "x81", question: "Who is most likely to have sex at a party?", deck: "lust" },
    { id: "x82", question: "Who is most likely to join the mile high club?", deck: "lust" },
    { id: "x83", question: "Who is most likely to have sex in a dressing room?", deck: "lust" },
    { id: "x84", question: "Who is most likely to get turned on by uniforms?", deck: "lust" },
    { id: "x85", question: "Who is most likely to be a exhibitionist?", deck: "lust" },
    { id: "x86", question: "Who is most likely to be a voyeur?", deck: "lust" },
    { id: "x87", question: "Who is most likely to narrate exactly what they want in bed?", deck: "lust" },
    { id: "x88", question: "Who is most likely to send a naughty text at work?", deck: "lust" },
    { id: "x89", question: "Who is most likely to take a nude bath together?", deck: "lust" },
    { id: "x90", question: "Who is most likely to initiate phone sex?", deck: "lust" },
    { id: "x91", question: "Who is most likely to have sex on the kitchen table?", deck: "lust" },
    { id: "x92", question: "Who is most likely to suggest edging?", deck: "lust" },
    { id: "x93", question: "Who is most likely to like hair pulling?", deck: "lust" },
    { id: "x94", question: "Who is most likely to like choking?", deck: "lust" },
    { id: "x95", question: "Who is most likely to use whipped cream in bed?", deck: "lust" },
    { id: "x96", question: "Who is most likely to play strip poker?", deck: "lust" },
    { id: "x97", question: "Who is most likely to suggest a sex game?", deck: "lust" },
    { id: "x98", question: "Who is most likely to have a secret fantasy?", deck: "lust" },
    { id: "x99", question: "Who is most likely to want to make a sex tape?", deck: "lust" },
    { id: "x100", question: "Who is most likely to be the wildest in bed?", deck: "lust" },
];

export const ALL_CARDS = [...normalDeck, ...awkwardDeck, ...lustDeck];

export function getCardsByDeck(deck: DeckType) {
    switch (deck) {
        case "normal":
            return normalDeck;
        case "awkward":
            return awkwardDeck;
        case "lust":
            return lustDeck;
        default:
            return normalDeck;
    }
}

// Simple seeded random number generator
function mulberry32(a: number) {
    return function () {
        let t = (a += 0x6d2b79f5);
        t = Math.imul(t ^ (t >>> 15), t | 1);
        t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
        return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
}

export function getDeckCards(deckType: DeckType, count: number, seed: number): WhosMostLikelyCard[] {
    const allDeckCards = getCardsByDeck(deckType);
    const random = mulberry32(seed);

    // Filter duplicates if any (though static lists shouldn't have them)
    // Then shuffle using Fisher-Yates
    const shuffled = [...allDeckCards];
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }

    // Return requested amount
    return shuffled.slice(0, count);
}
