export interface WhosMostLikelyCard {
    id: string;
    question: string;
    deck: string;
}

export type DeckType = "normal" | "awkward" | "lust";

export const DECKS: Record<DeckType, { name: string; emoji: string; description: string }> = {
    normal: {
        name: "Normal Mode 😇",
        emoji: "😇",
        description: "Fun & casual questions for everyone.",
    },
    awkward: {
        name: "Awkward Mode 😬",
        emoji: "😬",
        description: "Get ready for some uncomfortable truths.",
    },
    lust: {
        name: "Lust Mode 😈",
        emoji: "😈",
        description: "Spicy 18+ questions to heat things up.",
    },
};

// Normal Deck (100 cards)
const normalDeck: WhosMostLikelyCard[] = [
    { id: "n1", question: "Who is most likely to become famous?", deck: "normal" },
    { id: "n2", question: "Who is most likely to survive a zombie apocalypse?", deck: "normal" },
    { id: "n3", question: "Who is most likely to cry during a sad movie?", deck: "normal" },
    { id: "n4", question: "Who is most likely to win the lottery and lose the ticket?", deck: "normal" },
    { id: "n5", question: "Who is most likely to trip over nothing?", deck: "normal" },
    { id: "n6", question: "Who is most likely to adopt a stray animal?", deck: "normal" },
    { id: "n7", question: "Who is most likely to become a billionaire?", deck: "normal" },
    { id: "n8", question: "Who is most likely to talk their way out of a speeding ticket?", deck: "normal" },
    { id: "n9", question: "Who is most likely to forget someone's name immediately after meeting them?", deck: "normal" },
    { id: "n10", question: "Who is most likely to spend all their money on food?", deck: "normal" },
    { id: "n11", question: "Who is most likely to accidentally set something on fire cooking?", deck: "normal" },
    { id: "n12", question: "Who is most likely to join a cult by accident?", deck: "normal" },
    { id: "n13", question: "Who is most likely to get lost in their own neighborhood?", deck: "normal" },
    { id: "n14", question: "Who is most likely to become a stand-up comedian?", deck: "normal" },
    { id: "n15", question: "Who is most likely to binge-watch a whole series in one day?", deck: "normal" },
    { id: "n16", question: "Who is most likely to drop their phone in the toilet?", deck: "normal" },
    { id: "n17", question: "Who is most likely to laugh at the wrong moment?", deck: "normal" },
    { id: "n18", question: "Who is most likely to marry a stranger in Vegas?", deck: "normal" },
    { id: "n19", question: "Who is most likely to sleep through an earthquake?", deck: "normal" },
    { id: "n20", question: "Who is most likely to eat something off the floor?", deck: "normal" },
    { id: "n21", question: "Who is most likely to break a world record?", deck: "normal" },
    { id: "n22", question: "Who is most likely to go viral on TikTok?", deck: "normal" },
    { id: "n23", question: "Who is most likely to get a tattoo they regret?", deck: "normal" },
    { id: "n24", question: "Who is most likely to fall asleep in class/meeting?", deck: "normal" },
    { id: "n25", question: "Who is most likely to be late to their own wedding?", deck: "normal" },
    { id: "n26", question: "Who is most likely to talk to animals?", deck: "normal" },
    { id: "n27", question: "Who is most likely to scream at a spider?", deck: "normal" },
    { id: "n28", question: "Who is most likely to move to another country on a whim?", deck: "normal" },
    { id: "n29", question: "Who is most likely to be the best parent?", deck: "normal" },
    { id: "n30", question: "Who is most likely to win a dance battle?", deck: "normal" },
    { id: "n31", question: "Who is most likely to get arrested for something silly?", deck: "normal" },
    { id: "n32", question: "Who is most likely to become a crazy cat/dog person?", deck: "normal" },
    { id: "n33", question: "Who is most likely to buy something useless from an infomercial?", deck: "normal" },
    { id: "n34", question: "Who is most likely to give all their money to charity?", deck: "normal" },
    { id: "n35", question: "Who is most likely to write a best-selling book?", deck: "normal" },
    { id: "n36", question: "Who is most likely to spoil a movie ending?", deck: "normal" },
    { id: "n37", question: "Who is most likely to hold a grudge the longest?", deck: "normal" },
    { id: "n38", question: "Who is most likely to fake their own death?", deck: "normal" },
    { id: "n39", question: "Who is most likely to be the fun drunk?", deck: "normal" },
    { id: "n40", question: "Who is most likely to become a spy?", deck: "normal" },
    { id: "n41", question: "Who is most likely to lock themselves out of the house?", deck: "normal" },
    { id: "n42", question: "Who is most likely to invent something useless?", deck: "normal" },
    { id: "n43", question: "Who is most likely to go a week without showering?", deck: "normal" },
    { id: "n44", question: "Who is most likely to become a travel blogger?", deck: "normal" },
    { id: "n45", question: "Who is most likely to cry over a spilt drink?", deck: "normal" },
    { id: "n46", question: "Who is most likely to win a reality TV show?", deck: "normal" },
    { id: "n47", question: "Who is most likely to get sunburned?", deck: "normal" },
    { id: "n48", question: "Who is most likely to fix a broken appliance?", deck: "normal" },
    { id: "n49", question: "Who is most likely to be the first one on the dance floor?", deck: "normal" },
    { id: "n50", question: "Who is most likely to overpack for a trip?", deck: "normal" },
    { id: "n51", question: "Who is most likely to buy a boat?", deck: "normal" },
    { id: "n52", question: "Who is most likely to get lost in IKEA?", deck: "normal" },
    { id: "n53", question: "Who is most likely to text back immediately?", deck: "normal" },
    { id: "n54", question: "Who is most likely to leave you on read?", deck: "normal" },
    { id: "n55", question: "Who is most likely to have the messiest room?", deck: "normal" },
    { id: "n56", question: "Who is most likely to be the best cook?", deck: "normal" },
    { id: "n57", question: "Who is most likely to believe in ghosts?", deck: "normal" },
    { id: "n58", question: "Who is most likely to talk during a movie?", deck: "normal" },
    { id: "n59", question: "Who is most likely to take the best selfies?", deck: "normal" },
    { id: "n60", question: "Who is most likely to be the mom/dad of the group?", deck: "normal" },
    { id: "n61", question: "Who is most likely to cancel plans last minute?", deck: "normal" },
    { id: "n62", question: "Who is most likely to be the best secret keeper?", deck: "normal" },
    { id: "n63", question: "Who is most likely to sing in the shower?", deck: "normal" },
    { id: "n64", question: "Who is most likely to become a vegan?", deck: "normal" },
    { id: "n65", question: "Who is most likely to run a marathon?", deck: "normal" },
    { id: "n66", question: "Who is most likely to own an exotic pet?", deck: "normal" },
    { id: "n67", question: "Who is most likely to get famous for something stupid?", deck: "normal" },
    { id: "n68", question: "Who is most likely to survive in the wild?", deck: "normal" },
    { id: "n69", question: "Who is most likely to break their phone screen?", deck: "normal" },
    { id: "n70", question: "Who is most likely to dramatically quit their job?", deck: "normal" },
    { id: "n71", question: "Who is most likely to be the life of the party?", deck: "normal" },
    { id: "n72", question: "Who is most likely to have the worst temper?", deck: "normal" },
    { id: "n73", question: "Who is most likely to be a morning person?", deck: "normal" },
    { id: "n74", question: "Who is most likely to stay up all night?", deck: "normal" },
    { id: "n75", question: "Who is most likely to become a monk/nun?", deck: "normal" },
    { id: "n76", question: "Who is most likely to win a Nobel Prize?", deck: "normal" },
    { id: "n77", question: "Who is most likely to be featured on the news?", deck: "normal" },
    { id: "n78", question: "Who is most likely to have a secret identity?", deck: "normal" },
    { id: "n79", question: "Who is most likely to cheat at a board game?", deck: "normal" },
    { id: "n80", question: "Who is most likely to forget their own birthday?", deck: "normal" },
    { id: "n81", question: "Who is most likely to get a speeding ticket?", deck: "normal" },
    { id: "n82", question: "Who is most likely to become a politician?", deck: "normal" },
    { id: "n83", question: "Who is most likely to win an argument?", deck: "normal" },
    { id: "n84", question: "Who is most likely to lose their keys?", deck: "normal" },
    { id: "n85", question: "Who is most likely to embarrass themselves in public?", deck: "normal" },
    { id: "n86", question: "Who is most likely to spend the most on clothes?", deck: "normal" },
    { id: "n87", question: "Who is most likely to cry at a wedding?", deck: "normal" },
    { id: "n88", question: "Who is most likely to be the thrill seeker?", deck: "normal" },
    { id: "n89", question: "Who is most likely to live to 100?", deck: "normal" },
    { id: "n90", question: "Who is most likely to get scammed?", deck: "normal" },
    { id: "n91", question: "Who is most likely to give the best advice?", deck: "normal" },
    { id: "n92", question: "Who is most likely to be the most organized?", deck: "normal" },
    { id: "n93", question: "Who is most likely to be the most spontaneous?", deck: "normal" },
    { id: "n94", question: "Who is most likely to fall in love at first sight?", deck: "normal" },
    { id: "n95", question: "Who is most likely to be the best listener?", deck: "normal" },
    { id: "n96", question: "Who is most likely to make everyone laugh?", deck: "normal" },
    { id: "n97", question: "Who is most likely to have the best taste in music?", deck: "normal" },
    { id: "n98", question: "Who is most likely to have the most followers?", deck: "normal" },
    { id: "n99", question: "Who is most likely to be the best driver?", deck: "normal" },
    { id: "n100", question: "Who is most likely to plan the best party?", deck: "normal" },
];

// Awkward Deck (100 cards)
const awkwardDeck: WhosMostLikelyCard[] = [
    { id: "a1", question: "Who is most likely to stalk an ex on social media?", deck: "awkward" },
    { id: "a2", question: "Who is most likely to fart in a crowded elevator?", deck: "awkward" },
    { id: "a3", question: "Who is most likely to lie about their age?", deck: "awkward" },
    { id: "a4", question: "Who is most likely to have the worst breath?", deck: "awkward" },
    { id: "a5", question: "Who is most likely to check their phone during sex?", deck: "awkward" },
    { id: "a6", question: "Who is most likely to have a secret crush on a friend's partner?", deck: "awkward" },
    { id: "a7", question: "Who is most likely to spread a rumor?", deck: "awkward" },
    { id: "a8", question: "Who is most likely to go days without showering?", deck: "awkward" },
    { id: "a9", question: "Who is most likely to steal something small?", deck: "awkward" },
    { id: "a10", question: "Who is most likely to have an embarrassing nickname?", deck: "awkward" },
    { id: "a11", question: "Who is most likely to pick their nose in public?", deck: "awkward" },
    { id: "a12", question: "Who is most likely to be the most jealous?", deck: "awkward" },
    { id: "a13", question: "Who is most likely to look through someone else's phone?", deck: "awkward" },
    { id: "a14", question: "Who is most likely to cheat on a test?", deck: "awkward" },
    { id: "a15", question: "Who is most likely to ghost someone?", deck: "awkward" },
    { id: "a16", question: "Who is most likely to be involved in a scandal?", deck: "awkward" },
    { id: "a17", question: "Who is most likely to pee in the pool?", deck: "awkward" },
    { id: "a18", question: "Who is most likely to wear weird underwear?", deck: "awkward" },
    { id: "a19", question: "Who is most likely to have the strangest fetish?", deck: "awkward" },
    { id: "a20", question: "Who is most likely to date someone for their money?", deck: "awkward" },
    { id: "a21", question: "Who is most likely to have a fake ID?", deck: "awkward" },
    { id: "a22", question: "Who is most likely to get caught in a lie?", deck: "awkward" },
    { id: "a23", question: "Who is most likely to eavesdrop on a conversation?", deck: "awkward" },
    { id: "a24", question: "Who is most likely to re-gift a present?", deck: "awkward" },
    { id: "a25", question: "Who is most likely to pretend to like a gift?", deck: "awkward" },
    { id: "a26", question: "Who is most likely to eat someone else's food in the fridge?", deck: "awkward" },
    { id: "a27", question: "Who is most likely to hook up with an ex?", deck: "awkward" },
    { id: "a28", question: "Who is most likely to have a one-night stand?", deck: "awkward" },
    { id: "a29", question: "Who is most likely to be the worst kisser?", deck: "awkward" },
    { id: "a30", question: "Who is most likely to say the wrong name in bed?", deck: "awkward" },
    { id: "a31", question: "Who is most likely to clog a toilet at a party?", deck: "awkward" },
    { id: "a32", question: "Who is most likely to forget to flush?", deck: "awkward" },
    { id: "a33", question: "Who is most likely to wear dirty clothes?", deck: "awkward" },
    { id: "a34", question: "Who is most likely to have a secret family?", deck: "awkward" },
    { id: "a35", question: "Who is most likely to fake an orgasm?", deck: "awkward" },
    { id: "a36", question: "Who is most likely to flirt to get what they want?", deck: "awkward" },
    { id: "a37", question: "Who is most likely to have a criminal record?", deck: "awkward" },
    { id: "a38", question: "Who is most likely to break a promise?", deck: "awkward" },
    { id: "a39", question: "Who is most likely to reveal a secret?", deck: "awkward" },
    { id: "a40", question: "Who is most likely to be high maintenance?", deck: "awkward" },
    { id: "a41", question: "Who is most likely to be a gold digger?", deck: "awkward" },
    { id: "a42", question: "Who is most likely to judge others silently?", deck: "awkward" },
    { id: "a43", question: "Who is most likely to have a messy car?", deck: "awkward" },
    { id: "a44", question: "Who is most likely to borrow money and not pay it back?", deck: "awkward" },
    { id: "a45", question: "Who is most likely to be a drama queen?", deck: "awkward" },
    { id: "a46", question: "Who is most likely to have plastic surgery?", deck: "awkward" },
    { id: "a47", question: "Who is most likely to be catfished?", deck: "awkward" },
    { id: "a48", question: "Who is most likely to catfish someone?", deck: "awkward" },
    { id: "a49", question: "Who is most likely to have the most embarrassing search history?", deck: "awkward" },
    { id: "a50", question: "Who is most likely to send a text to the wrong person?", deck: "awkward" },
    { id: "a51", question: "Who is most likely to laugh at a funeral?", deck: "awkward" },
    { id: "a52", question: "Who is most likely to be late due to vanity?", deck: "awkward" },
    { id: "a53", question: "Who is most likely to take credit for someone else's work?", deck: "awkward" },
    { id: "a54", question: "Who is most likely to be a picky eater?", deck: "awkward" },
    { id: "a55", question: "Who is most likely to complain at a restaurant?", deck: "awkward" },
    { id: "a56", question: "Who is most likely to return food?", deck: "awkward" },
    { id: "a57", question: "Who is most likely to talk about themselves all night?", deck: "awkward" },
    { id: "a58", question: "Who is most likely to interrupt others?", deck: "awkward" },
    { id: "a59", question: "Who is most likely to be on their phone during a date?", deck: "awkward" },
    { id: "a60", question: "Who is most likely to swipe left on everyone?", deck: "awkward" },
    { id: "a61", question: "Who is most likely to use a cheesy pickup line?", deck: "awkward" },
    { id: "a62", question: "Who is most likely to get friend-zoned?", deck: "awkward" },
    { id: "a63", question: "Who is most likely to fall only for bad boys/girls?", deck: "awkward" },
    { id: "a64", question: "Who is most likely to be single forever?", deck: "awkward" },
    { id: "a65", question: "Who is most likely to get married for money?", deck: "awkward" },
    { id: "a66", question: "Who is most likely to have a secret addiction?", deck: "awkward" },
    { id: "a67", question: "Who is most likely to lie on their resume?", deck: "awkward" },
    { id: "a68", question: "Who is most likely to get fired?", deck: "awkward" },
    { id: "a69", question: "Who is most likely to have a workplace romance?", deck: "awkward" },
    { id: "a70", question: "Who is most likely to steal office supplies?", deck: "awkward" },
    { id: "a71", question: "Who is most likely to suck up to the boss?", deck: "awkward" },
    { id: "a72", question: "Who is most likely to panic in a crisis?", deck: "awkward" },
    { id: "a73", question: "Who is most likely to be the first to die in a horror movie?", deck: "awkward" },
    { id: "a74", question: "Who is most likely to betray a friend?", deck: "awkward" },
    { id: "a75", question: "Who is most likely to keep a lost wallet?", deck: "awkward" },
    { id: "a76", question: "Who is most likely to cheat at cards?", deck: "awkward" },
    { id: "a77", question: "Who is most likely to have the worst tattoo?", deck: "awkward" },
    { id: "a78", question: "Who is most likely to wear socks with sandals?", deck: "awkward" },
    { id: "a79", question: "Who is most likely to have a mullet?", deck: "awkward" },
    { id: "a80", question: "Who is most likely to believe a conspiracy theory?", deck: "awkward" },
    { id: "a81", question: "Who is most likely to be an anti-vaxxer?", deck: "awkward" },
    { id: "a82", question: "Who is most likely to join a pyramid scheme?", deck: "awkward" },
    { id: "a83", question: "Who is most likely to get a face tattoo?", deck: "awkward" },
    { id: "a84", question: "Who is most likely to run away from responsibilities?", deck: "awkward" },
    { id: "a85", question: "Who is most likely to be a narcissist?", deck: "awkward" },
    { id: "a86", question: "Who is most likely to manipulate others?", deck: "awkward" },
    { id: "a87", question: "Who is most likely to start a fight?", deck: "awkward" },
    { id: "a88", question: "Who is most likely to be the loudest neighbor?", deck: "awkward" },
    { id: "a89", question: "Who is most likely to not tip?", deck: "awkward" },
    { id: "a90", question: "Who is most likely to be rude to waiters?", deck: "awkward" },
    { id: "a91", question: "Who is most likely to litter?", deck: "awkward" },
    { id: "a92", question: "Who is most likely to double dip?", deck: "awkward" },
    { id: "a93", question: "Who is most likely to spoil a surprise party?", deck: "awkward" },
    { id: "a94", question: "Who is most likely to be the worst roommate?", deck: "awkward" },
    { id: "a95", question: "Who is most likely to steal the covers?", deck: "awkward" },
    { id: "a96", question: "Who is most likely to snore the loudest?", deck: "awkward" },
    { id: "a97", question: "Who is most likely to talk in their sleep?", deck: "awkward" },
    { id: "a98", question: "Who is most likely to drool while sleeping?", deck: "awkward" },
    { id: "a99", question: "Who is most likely to wear pajamas to the store?", deck: "awkward" },
    { id: "a100", question: "Who is most likely to have the weirdest laugh?", deck: "awkward" },
];

// Lust Deck (18+) (100 cards)
const lustDeck: WhosMostLikelyCard[] = [
    { id: "x1", question: "Who is most likely to cum first?", deck: "lust" },
    { id: "x2", question: "Who is most likely to initiate sex?", deck: "lust" },
    { id: "x3", question: "Who is most likely to want public sex?", deck: "lust" },
    { id: "x4", question: "Who is most likely to watch porn daily?", deck: "lust" },
    { id: "x5", question: "Who is most likely to have a sex tape?", deck: "lust" },
    { id: "x6", question: "Who is most likely to be the louder moaner?", deck: "lust" },
    { id: "x7", question: "Who is most likely to be into BDSM?", deck: "lust" },
    { id: "x8", question: "Who is most likely to want a threesome?", deck: "lust" },
    { id: "x9", question: "Who is most likely to suggest roleplay?", deck: "lust" },
    { id: "x10", question: "Who is most likely to be dominant in bed?", deck: "lust" },
    { id: "x11", question: "Who is most likely to be submissive in bed?", deck: "lust" },
    { id: "x12", question: "Who is most likely to send a risky nude?", deck: "lust" },
    { id: "x13", question: "Who is most likely to have the higher body count?", deck: "lust" },
    { id: "x14", question: "Who is most likely to be kinky?", deck: "lust" },
    { id: "x15", question: "Who is most likely to try anal?", deck: "lust" },
    { id: "x16", question: "Who is most likely to own sex toys?", deck: "lust" },
    { id: "x17", question: "Who is most likely to have a foot fetish?", deck: "lust" },
    { id: "x18", question: "Who is most likely to talk dirty?", deck: "lust" },
    { id: "x19", question: "Who is most likely to fall asleep after sex?", deck: "lust" },
    { id: "x20", question: "Who is most likely to want morning sex?", deck: "lust" },
    { id: "x21", question: "Who is most likely to be up for a quickie?", deck: "lust" },
    { id: "x22", question: "Who is most likely to get turned on the easiest?", deck: "lust" },
    { id: "x23", question: "Who is most likely to have had sex in a car?", deck: "lust" },
    { id: "x24", question: "Who is most likely to strip for their partner?", deck: "lust" },
    { id: "x25", question: "Who is most likely to like it rough?", deck: "lust" },
    { id: "x26", question: "Who is most likely to like biting?", deck: "lust" },
    { id: "x27", question: "Who is most likely to like scratching?", deck: "lust" },
    { id: "x28", question: "Who is most likely to simplify sex?", deck: "lust" },
    { id: "x29", question: "Who is most likely to experiment with food in bed?", deck: "lust" },
    { id: "x30", question: "Who is most likely to have an unexpected orgasm?", deck: "lust" },
    { id: "x31", question: "Who is most likely to make the first move?", deck: "lust" },
    { id: "x32", question: "Who is most likely to think about sex all day?", deck: "lust" },
    { id: "x33", question: "Who is most likely to masturbate at work?", deck: "lust" },
    { id: "x34", question: "Who is most likely to get caught having sex?", deck: "lust" },
    { id: "x35", question: "Who is most likely to give the best head?", deck: "lust" },
    { id: "x36", question: "Who is most likely to want sex every day?", deck: "lust" },
    { id: "x37", question: "Who is most likely to say no to sex?", deck: "lust" },
    { id: "x38", question: "Who is most likely to lie about being turned on?", deck: "lust" },
    { id: "x39", question: "Who is most likely to be adventurous in bed?", deck: "lust" },
    { id: "x40", question: "Who is most likely to suggest using a blindfold?", deck: "lust" },
    { id: "x41", question: "Who is most likely to like being tied up?", deck: "lust" },
    { id: "x42", question: "Who is most likely to want to tie their partner up?", deck: "lust" },
    { id: "x43", question: "Who is most likely to like spanking?", deck: "lust" },
    { id: "x44", question: "Who is most likely to be the best lover?", deck: "lust" },
    { id: "x45", question: "Who is most likely to be shy about their body?", deck: "lust" },
    { id: "x46", question: "Who is most likely to walk around naked?", deck: "lust" },
    { id: "x47", question: "Who is most likely to like watching their partner pleasure themselves?", deck: "lust" },
    { id: "x48", question: "Who is most likely to pleasure themselves in front of their partner?", deck: "lust" },
    { id: "x49", question: "Who is most likely to want to visit a strip club?", deck: "lust" },
    { id: "x50", question: "Who is most likely to pay for sex?", deck: "lust" },
    { id: "x51", question: "Who is most likely to have a secret sex diary?", deck: "lust" },
    { id: "x52", question: "Who is most likely to get turned on by danger?", deck: "lust" },
    { id: "x53", question: "Who is most likely to have sex on a first date?", deck: "lust" },
    { id: "x54", question: "Who is most likely to sleep with a stranger?", deck: "lust" },
    { id: "x55", question: "Who is most likely to have a crush on a teacher?", deck: "lust" },
    { id: "x56", question: "Who is most likely to have a crush on a celebrity?", deck: "lust" },
    { id: "x57", question: "Who is most likely to be polyamorous?", deck: "lust" },
    { id: "x58", question: "Who is most likely to swing?", deck: "lust" },
    { id: "x59", question: "Who is most likely to watch hentai?", deck: "lust" },
    { id: "x60", question: "Who is most likely to read erotica?", deck: "lust" },
    { id: "x61", question: "Who is most likely to own handcuffs?", deck: "lust" },
    { id: "x62", question: "Who is most likely to like heavy petting?", deck: "lust" },
    { id: "x63", question: "Who is most likely to give a massage that leads to sex?", deck: "lust" },
    { id: "x64", question: "Who is most likely to suggest shower sex?", deck: "lust" },
    { id: "x65", question: "Who is most likely to suggest beach sex?", deck: "lust" },
    { id: "x66", question: "Who is most likely to suggest outdoor sex?", deck: "lust" },
    { id: "x67", question: "Who is most likely to get loud during sex?", deck: "lust" },
    { id: "x68", question: "Who is most likely to keep their eyes open during sex?", deck: "lust" },
    { id: "x69", question: "Who is most likely to ask 'do you like that?' constantly?", deck: "lust" },
    { id: "x70", question: "Who is most likely to cuddle after sex?", deck: "lust" },
    { id: "x71", question: "Who is most likely to get up and leave after sex?", deck: "lust" },
    { id: "x72", question: "Who is most likely to want round two immediately?", deck: "lust" },
    { id: "x73", question: "Who is most likely to fake enjoyment?", deck: "lust" },
    { id: "x74", question: "Who is most likely to try a new position?", deck: "lust" },
    { id: "x75", question: "Who is most likely to suggest the 69 position?", deck: "lust" },
    { id: "x76", question: "Who is most likely to like doggy style best?", deck: "lust" },
    { id: "x77", question: "Who is most likely to like missionary best?", deck: "lust" },
    { id: "x78", question: "Who is most likely to like cowgirl best?", deck: "lust" },
    { id: "x79", question: "Who is most likely to have sex in a bathroom?", deck: "lust" },
    { id: "x80", question: "Who is most likely to have sex in a movie theater?", deck: "lust" },
    { id: "x81", question: "Who is most likely to have sex at a party?", deck: "lust" },
    { id: "x82", question: "Who is most likely to join the mile high club?", deck: "lust" },
    { id: "x83", question: "Who is most likely to have sex in a dressing room?", deck: "lust" },
    { id: "x84", question: "Who is most likely to get turned on by uniforms?", deck: "lust" },
    { id: "x85", question: "Who is most likely to be a exhibitionist?", deck: "lust" },
    { id: "x86", question: "Who is most likely to be a voyeur?", deck: "lust" },
    { id: "x87", question: "Who is most likely to like sensual touching?", deck: "lust" },
    { id: "x88", question: "Who is most likely to send a naughty text at work?", deck: "lust" },
    { id: "x89", question: "Who is most likely to take a nude bath together?", deck: "lust" },
    { id: "x90", question: "Who is most likely to initiate phone sex?", deck: "lust" },
    { id: "x91", question: "Who is most likely to have sex on the kitchen table?", deck: "lust" },
    { id: "x92", question: "Who is most likely to suggest eding?", deck: "lust" },
    { id: "x93", question: "Who is most likely to like hair pulling?", deck: "lust" },
    { id: "x94", question: "Who is most likely to like choking?", deck: "lust" },
    { id: "x95", question: "Who is most likely to use whipped cream in bed?", deck: "lust" },
    { id: "x96", question: "Who is most likely to play strip poker?", deck: "lust" },
    { id: "x97", question: "Who is most likely to suggest a sex game?", deck: "lust" },
    { id: "x98", question: "Who is most likely to have a secret fantasy?", deck: "lust" },
    { id: "x99", question: "Who is most likely to want to make a sex tape?", deck: "lust" },
    { id: "x100", question: "Who is most likely to be the wildest in bed?", deck: "lust" },
];

export const ALL_CARDS = [...normalDeck, ...awkwardDeck, ...lustDeck];

export function getCardsByDeck(deck: DeckType) {
    switch (deck) {
        case "normal":
            return normalDeck;
        case "awkward":
            return awkwardDeck;
        case "lust":
            return lustDeck;
        default:
            return normalDeck;
    }
}

// Simple seeded random number generator
function mulberry32(a: number) {
    return function () {
        let t = (a += 0x6d2b79f5);
        t = Math.imul(t ^ (t >>> 15), t | 1);
        t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
        return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
}

export function getDeckCards(deckType: DeckType, count: number, seed: number): WhosMostLikelyCard[] {
    const allDeckCards = getCardsByDeck(deckType);
    const random = mulberry32(seed);

    // Filter duplicates if any (though static lists shouldn't have them)
    // Then shuffle
    const shuffled = [...allDeckCards]
        .sort(() => 0.5 - random());

    // Return requested amount
    return shuffled.slice(0, count);
}
