export type DeckType = "classic" | "pop-culture" | "history" | "science" | "geography" | "literature" | "sports" | "random";

interface Question {
    question: string;
    options: string[]; // 4 options
    answer: number; // 0-3 index of correct answer
}

interface Deck {
    name: string;
    emoji: string;
    description: string;
    cards: Question[];
}

export const GENERAL_KNOWLEDGE_DECKS: Record<DeckType, Deck> = {
    "classic": {
        name: "Classic",
        emoji: "🧠",
        description: "Standard general knowledge questions for everyone.",
        cards: [
            { question: "Which planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Saturn"], answer: 1 },
            { question: "What is the capital of France?", options: ["London", "Berlin", "Madrid", "Paris"], answer: 3 },
            { question: "Who wrote 'Romeo and Juliet'?", options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"], answer: 1 },
            { question: "What represents the letter 'O' in the periodic table?", options: ["Gold", "Silver", "Oxygen", "Osmium"], answer: 2 },
            { question: "Which animal is known as the 'King of the Jungle'?", options: ["Tiger", "Lion", "Elephant", "Gorilla"], answer: 1 },
            { question: "How many continents are there?", options: ["5", "6", "7", "8"], answer: 2 },
            { question: "What is the largest ocean on Earth?", options: ["Atlantic", "Indian", "Arctic", "Pacific"], answer: 3 },
            { question: "Who painted the Mona Lisa?", options: ["Michelangelo", "Leonardo da Vinci", "Raphael", "Donatello"], answer: 1 },
            { question: "What is the smallest country in the world?", options: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"], answer: 1 },
            { question: "How many sides does a hexagon have?", options: ["5", "6", "7", "8"], answer: 1 },
            { question: "What is the capital of Japan?", options: ["Seoul", "Beijing", "Tokyo", "Bangkok"], answer: 2 },
            { question: "Which element has the chemical symbol 'Au'?", options: ["Silver", "Gold", "Aluminum", "Argon"], answer: 1 },
            { question: "How many bones are in the adult human body?", options: ["186", "206", "226", "246"], answer: 1 },
            { question: "What year did World War II end?", options: ["1943", "1944", "1945", "1946"], answer: 2 },
            { question: "What is the largest mammal in the world?", options: ["African Elephant", "Blue Whale", "Giraffe", "Polar Bear"], answer: 1 },
            { question: "Who invented the telephone?", options: ["Thomas Edison", "Nikola Tesla", "Alexander Graham Bell", "Benjamin Franklin"], answer: 2 },
            { question: "What is the speed of light?", options: ["299,792 km/s", "199,792 km/s", "399,792 km/s", "99,792 km/s"], answer: 0 },
            { question: "Which country is home to the kangaroo?", options: ["New Zealand", "Australia", "South Africa", "Brazil"], answer: 1 },
            { question: "What is the hardest natural substance on Earth?", options: ["Gold", "Iron", "Diamond", "Platinum"], answer: 2 },
            { question: "How many players are on a soccer team?", options: ["9", "10", "11", "12"], answer: 2 },
            { question: "What is the main ingredient in guacamole?", options: ["Tomato", "Onion", "Avocado", "Pepper"], answer: 2 },
            { question: "Which planet is closest to the Sun?", options: ["Venus", "Earth", "Mercury", "Mars"], answer: 2 },
            { question: "What is the currency of the United Kingdom?", options: ["Euro", "Dollar", "Pound Sterling", "Yen"], answer: 2 },
            { question: "Who was the first person to walk on the Moon?", options: ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "Michael Collins"], answer: 1 },
            { question: "What covers approx. 71% of Earth's surface?", options: ["Land", "Water", "Ice", "Sand"], answer: 1 },
            { question: "Which instrument has 88 keys?", options: ["Guitar", "Violin", "Piano", "Flute"], answer: 2 },
            { question: "What is the tallest mountain in the world?", options: ["K2", "Mount Everest", "Kilimanjaro", "Mount Fuji"], answer: 1 },
            { question: "Which gas do plants absorb from the atmosphere?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], answer: 1 },
            { question: "How many days are in a leap year?", options: ["364", "365", "366", "367"], answer: 2 },
            { question: "What color do you get by mixing red and blue?", options: ["Green", "Orange", "Purple", "Brown"], answer: 2 },
            { question: "Which organ pumps blood through the body?", options: ["Brain", "Lungs", "Heart", "Liver"], answer: 2 },
            { question: "What is the chemical symbol for water?", options: ["H2O", "CO2", "O2", "NaCl"], answer: 0 },
            { question: "Who wrote 'Harry Potter'?", options: ["J.R.R. Tolkien", "J.K. Rowling", "George R.R. Martin", "Stephen King"], answer: 1 },
            { question: "Which continent is the Sahara Desert located in?", options: ["Asia", "South America", "Africa", "Australia"], answer: 2 },
            { question: "How many zeros are in one million?", options: ["5", "6", "7", "8"], answer: 1 },
            { question: "What is the freezing point of water?", options: ["0°C", "10°C", "32°C", "-10°C"], answer: 0 },
            { question: "Which bird is the universal symbol of peace?", options: ["Eagle", "Dove", "Owl", "Swan"], answer: 1 },
            { question: "What is the largest country by land area?", options: ["China", "USA", "Canada", "Russia"], answer: 3 },
            { question: "Who discovered gravity when an apple fell?", options: ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Nikola Tesla"], answer: 1 },
            { question: "What is the national flower of Japan?", options: ["Rose", "Tulip", "Cherry Blossom", "Lotus"], answer: 2 },
            { question: "Which language is the most spoken worldwide?", options: ["Spanish", "English", "Mandarin Chinese", "Hindi"], answer: 1 },
            { question: "How many legs does a spider have?", options: ["6", "8", "10", "12"], answer: 1 },
            { question: "What represents the 5 rings in the Olympic symbol?", options: ["Oceans", "Continents", "Countries", "Planets"], answer: 1 },
            { question: "Which fruit has its seeds on the outside?", options: ["Banana", "Strawberry", "Kiwi", "Apple"], answer: 1 },
            { question: "What is the largest internal organ in the human body?", options: ["Heart", "Lungs", "Liver", "Stomach"], answer: 2 },
            { question: "Who is known as the 'Father of the Nation' in India?", options: ["Nehru", "Gandhi", "Modi", "Ambedkar"], answer: 1 },
            { question: "Which planet has the most rings?", options: ["Jupiter", "Saturn", "Uranus", "Neptune"], answer: 1 },
            { question: "What is the square root of 64?", options: ["6", "7", "8", "9"], answer: 2 },
            { question: "Which famous ship sank in 1912?", options: ["Titanic", "Lusitania", "Britannic", "Olympic"], answer: 0 },
            { question: "How many stars are on the US flag?", options: ["48", "49", "50", "51"], answer: 2 }
        ]
    },
    "pop-culture": {
        name: "Pop Culture",
        emoji: "🎬",
        description: "Movies, music, celebrities, and viral trends.",
        cards: [
            { question: "Who played Jack in 'Titanic'?", options: ["Brad Pitt", "Tom Cruise", "Leonardo DiCaprio", "Johnny Depp"], answer: 2 },
            { question: "Who is the 'Queen of Pop'?", options: ["Beyoncé", "Madonna", "Lady Gaga", "Britney Spears"], answer: 1 },
            { question: "Which TV show is set in Westeros?", options: ["The Witcher", "Game of Thrones", "Vikings", "Lord of the Rings"], answer: 1 },
            { question: "Who released the album 'Midnights'?", options: ["Taylor Swift", "Adele", "Rihanna", "Katy Perry"], answer: 0 },
            { question: "What is the highest-grossing film of all time?", options: ["Avatar", "Avengers: Endgame", "Titanic", "Star Wars"], answer: 0 },
            { question: "Who sang 'Thriller'?", options: ["Prince", "Michael Jackson", "Stevie Wonder", "David Bowie"], answer: 1 },
            { question: "Which Avenger is a god?", options: ["Iron Man", "Thor", "Hulk", "Captain America"], answer: 1 },
            { question: "Who is Kim Kardashian’s mother?", options: ["Caitlyn", "Kris", "Kourtney", "Khloe"], answer: 1 },
            { question: "What is the name of Shrek's wife?", options: ["Fiona", "Cinderella", "Snow White", "Belle"], answer: 0 },
            { question: "Who directed 'Inception'?", options: ["Steven Spielberg", "Christopher Nolan", "Quentin Tarantino", "Martin Scorsese"], answer: 1 },
            { question: "Which band sang 'Bohemian Rhapsody'?", options: ["The Beatles", "Queen", "Led Zeppelin", "AC/DC"], answer: 1 },
            { question: "What is the name of the fictional city in Black Panther?", options: ["Wakanda", "Zamunda", "Genovia", "El Dorado"], answer: 0 },
            { question: "Who is the most followed person on Instagram (2024)?", options: ["Cristiano Ronaldo", "Lionel Messi", "Selena Gomez", "Kylie Jenner"], answer: 0 },
            { question: "Which movie features the quote 'May the Force be with you'?", options: ["Star Trek", "Star Wars", "Matrix", "Guardians of the Galaxy"], answer: 1 },
            { question: "Who won the first season of American Idol?", options: ["Kelly Clarkson", "Carrie Underwood", "Adam Lambert", "Jennifer Hudson"], answer: 0 },
            { question: "What is the name of Harry Potter's owl?", options: ["Hedwig", "Crookshanks", "Scabbers", "Fang"], answer: 0 },
            { question: "Who played Iron Man in the MCU?", options: ["Chris Evans", "Robert Downey Jr.", "Chris Hemsworth", "Mark Ruffalo"], answer: 1 },
            { question: "Which singer is known as 'The Weeknd'?", options: ["Abel Tesfaye", "Aubrey Graham", "Shawn Mendes", "Justin Bieber"], answer: 0 },
            { question: "What is the longest-running animated TV show?", options: ["Family Guy", "The Simpsons", "South Park", "SpongeBob"], answer: 1 },
            { question: "Who wrote the song 'Hello'?", options: ["Adele", "Sia", "Beyoncé", "Taylor Swift"], answer: 0 },
            { question: "Which actor played the Joker in 'The Dark Knight'?", options: ["Jared Leto", "Jack Nicholson", "Heath Ledger", "Joaquin Phoenix"], answer: 2 },
            { question: "What is the name of the coffee shop in 'Friends'?", options: ["Central Perk", "Monk's Cafe", "Luke's Diner", "MacLaren's Pub"], answer: 0 },
            { question: "Who is the stunning actress in 'Barbie' (2023)?", options: ["Margot Robbie", "Emma Stone", "Scarlett Johansson", "Jennifer Lawrence"], answer: 0 },
            { question: "Which pop star has a fandom called 'Swifties'?", options: ["Taylor Swift", "Ariana Grande", "Selena Gomez", "Miley Cyrus"], answer: 0 },
            { question: "What is the name of the toy cowboy in Toy Story?", options: ["Buzz", "Woody", "Jesse", "Bullseye"], answer: 1 },
            { question: "Who famously interrupted Taylor Swift at the VMAs?", options: ["Jay-Z", "Kanye West", "Drake", "Eminem"], answer: 1 },
            { question: "Which movie features a character named 'Gollum'?", options: ["Harry Potter", "Lord of the Rings", "The Hobbit", "Narnia"], answer: 1 },
            { question: "Who is the lead singer of Coldplay?", options: ["Chris Martin", "Thom Yorke", "Bono", "Dave Grohl"], answer: 0 },
            { question: "What is the name of the kingdom in 'Frozen'?", options: ["Arendelle", "Genovia", "Aldovia", "Corona"], answer: 0 },
            { question: "Who played Hermione Granger?", options: ["Emma Watson", "Emma Stone", "Emma Roberts", "Emma Thompson"], answer: 0 },
            { question: "Which artist painted 'Starry Night'?", options: ["Picasso", "Van Gogh", "Monet", "Dali"], answer: 1 },
            { question: "Who is the 'King of Rock and Roll'?", options: ["Elvis Presley", "Chuck Berry", "Buddy Holly", "Little Richard"], answer: 0 },
            { question: "What is the name of the dog in 'Scooby-Doo'?", options: ["Scooby-Doo", "Scrappy", "Shaggy", "Fred"], answer: 0 },
            { question: "Who hosted 'The Office' (US) mostly?", options: ["Steve Carell", "Ricky Gervais", "John Krasinski", "Rainn Wilson"], answer: 0 },
            { question: "Which movie won Best Picture in 2020?", options: ["Parasite", "1917", "Joker", "Once Upon a Time"], answer: 0 },
            { question: "Who is known as 'The Fresh Prince'?", options: ["Will Smith", "Eddie Murphy", "Martin Lawrence", "Jamie Foxx"], answer: 0 },
            { question: "Which girl group was Beyoncé in?", options: ["TLC", "Destiny's Child", "Spice Girls", "En Vogue"], answer: 1 },
            { question: "What is the name of the skyscraper in 'Die Hard'?", options: ["Nakatomi Plaza", "Empire State", "Chrysler Building", "Sears Tower"], answer: 0 },
            { question: "Who played Wolverine?", options: ["Hugh Jackman", "Ryan Reynolds", "Ben Affleck", "Henry Cavill"], answer: 0 },
            { question: "Which singer had a hit with 'Baby One More Time'?", options: ["Christina Aguilera", "Britney Spears", "Jessica Simpson", "Mandy Moore"], answer: 1 },
            { question: "What is the name of the hobbit played by Elijah Wood?", options: ["Frodo", "Sam", "Merry", "Pippin"], answer: 0 },
            { question: "Who is the creator of Star Wars?", options: ["George Lucas", "Steven Spielberg", "J.J. Abrams", "James Cameron"], answer: 0 },
            { question: "Which movie features the song 'Let It Go'?", options: ["Moana", "Tangled", "Frozen", "Brave"], answer: 2 },
            { question: "Who is the youngest Kardashian/Jenner?", options: ["Kendall", "Kylie", "Khloe", "Kim"], answer: 1 },
            { question: "What is the name of the clown in 'It'?", options: ["Pennywise", "Joker", "Ronald", "Bozo"], answer: 0 },
            { question: "Who played Forrest Gump?", options: ["Tom Hanks", "Tom Cruise", "Harrison Ford", "Robin Williams"], answer: 0 },
            { question: "Which rapper's real name is Marshall Mathers?", options: ["Drake", "Eminem", "Jay-Z", "50 Cent"], answer: 1 },
            { question: "What sits on the Iron Throne at the end of GOT?", options: ["Jon Snow", "Bran Stark", "Daenerys", "Sansa"], answer: 1 },
            { question: "Who sang 'Rolling in the Deep'?", options: ["Adele", "Amy Winehouse", "Duffy", "Leona Lewis"], answer: 0 },
            { question: "Which superhero is from Wakanda?", options: ["Black Panther", "Falcon", "War Machine", "Luke Cage"], answer: 0 }
        ]
    },
    "history": {
        name: "History Buff",
        emoji: "📜",
        description: "Events, figures, and dates from the past.",
        cards: [
            { question: "Who was the first President of the USA?", options: ["Jefferson", "Lincoln", "Washington", "Adams"], answer: 2 },
            { question: "In which year did World War I begin?", options: ["1912", "1914", "1916", "1918"], answer: 1 },
            { question: "Who discovered America in 1492?", options: ["Magellan", "Columbus", "Vespucci", "Cook"], answer: 1 },
            { question: "Which ancient civilization built the pyramids?", options: ["Romans", "Greeks", "Egyptians", "Mayans"], answer: 2 },
            { question: "Who was the first female Prime Minister of the UK?", options: ["Theresa May", "Margaret Thatcher", "Liz Truss", "Queen Elizabeth"], answer: 1 },
            { question: "What wall fell in 1989?", options: ["Great Wall", "Berlin Wall", "Hadrian's Wall", "Wailing Wall"], answer: 1 },
            { question: "Who wrote the Declaration of Independence?", options: ["Washington", "Franklin", "Jefferson", "Hamilton"], answer: 2 },
            { question: "Which ship sank on its maiden voyage in 1912?", options: ["Titanic", "Olympic", "Britannic", "Lusitania"], answer: 0 },
            { question: "Who was the first man in space?", options: ["Armstrong", "Glenn", "Gagarin", "Shepard"], answer: 2 },
            { question: "Which empire was ruled by Julius Caesar?", options: ["Greek", "Roman", "Persian", "Ottoman"], answer: 1 },
            { question: "When did the US subscribe to the Constitution?", options: ["1776", "1787", "1791", "1800"], answer: 1 },
            { question: "Who was the British monarch during WWII?", options: ["George V", "George VI", "Edward VIII", "Elizabeth II"], answer: 1 },
            { question: "What year did the moon landing occur?", options: ["1965", "1969", "1971", "1975"], answer: 1 },
            { question: "Who painted the Sistine Chapel ceiling?", options: ["Leonardo", "Raphael", "Michelangelo", "Donatello"], answer: 2 },
            { question: "Which war was fought between the North and South USA?", options: ["Revolutionary War", "Civil War", "War of 1812", "Vietnam War"], answer: 1 },
            { question: "Who was the Soviet leader during WWII?", options: ["Lenin", "Stalin", "Gorbachev", "Putin"], answer: 1 },
            { question: "What was the name of the ship Charles Darwin sailed on?", options: ["Beagle", "Endeavour", "Mayflower", "Santa Maria"], answer: 0 },
            { question: "Who was the first Emperor of China?", options: ["Qin Shi Huang", "Sun Yat-sen", "Mao Zedong", "Kublai Khan"], answer: 0 },
            { question: "When did the French Revolution begin?", options: ["1776", "1789", "1812", "1848"], answer: 1 },
            { question: "Who was assassinated in 1963 in Dallas?", options: ["MLK", "RFK", "JFK", "Lincoln"], answer: 2 },
            { question: "What was the code name for the D-Day invasion?", options: ["Operation Overlord", "Operation Barbarossa", "Operation Torch", "Operation Sea Lion"], answer: 0 },
            { question: "Who was the leader of Nazi Germany?", options: ["Himmler", "Goebbels", "Hitler", "Goering"], answer: 2 },
            { question: "Which city was destroyed by Vesuvius?", options: ["Rome", "Athens", "Pompeii", "Sparta"], answer: 2 },
            { question: "Who invented the printing press?", options: ["Gutenberg", "Edison", "Bell", "Franklin"], answer: 0 },
            { question: "What year did the Berlin Wall fall?", options: ["1987", "1989", "1991", "1993"], answer: 1 },
            { question: "Who was the first woman to fly solo across the Atlantic?", options: ["Amelia Earhart", "Bessie Coleman", "Harriet Quimby", "Valentina Tereshkova"], answer: 0 },
            { question: "Which country gifted the Statue of Liberty to the USA?", options: ["England", "Spain", "France", "Italy"], answer: 2 },
            { question: "Who was the longest-reigning British monarch?", options: ["Victoria", "Elizabeth II", "George III", "Henry VIII"], answer: 1 },
            { question: "What was the name of the first atomic bomb?", options: ["Little Boy", "Fat Man", "Trinity", "Czar Bomba"], answer: 0 },
            { question: "Which ancient wonder was located in Alexandria?", options: ["Lighthouse", "Gardens", "Colossus", "Statue"], answer: 0 },
            { question: "Who conquered the Aztec Empire?", options: ["Pizarro", "Cortes", "Columbus", "Magellan"], answer: 1 },
            { question: "When did the Cold War end?", options: ["1989", "1991", "1995", "2000"], answer: 1 },
            { question: "Who was the first female Pharoah?", options: ["Cleopatra", "Nefertiti", "Hatshepsut", "Isis"], answer: 2 },
            { question: "What treaty ended WWI?", options: ["Treaty of Paris", "Treaty of Versailles", "Treaty of Ghent", "Treaty of Vienna"], answer: 1 },
            { question: "Who led the Salt March in India?", options: ["Nehru", "Gandhi", "Jinnah", "Bose"], answer: 1 },
            { question: "Which king had six wives?", options: ["Henry VIII", "Louis XIV", "George III", "Edward VII"], answer: 0 },
            { question: "Who wrote the 95 Theses?", options: ["Calvin", "Luther", "Zwingli", "Knox"], answer: 1 },
            { question: "Who was the first man to circumnavigate the globe?", options: ["Columbus", "Magellan", "Drake", "Cook"], answer: 1 },
            { question: "What year did the Black Death peak in Europe?", options: ["1347-1351", "1400-1405", "1215-1220", "1500-1505"], answer: 0 },
            { question: "Who was the 'Maid of Orléans'?", options: ["Joan of Arc", "Marie Antoinette", "Catherine de Medici", "Eleanor of Aquitaine"], answer: 0 },
            { question: "Which US state was the last to join the union?", options: ["Alaska", "Arizona", "Hawaii", "New Mexico"], answer: 2 },
            { question: "Who invented the lightbulb?", options: ["Tesla", "Edison", "Bell", "Morse"], answer: 1 },
            { question: "What was the first capital of the US?", options: ["Philadelphia", "New York", "Boston", "Washington DC"], answer: 1 },
            { question: "Who was the first female scientist to win a Nobel Prize?", options: ["Curie", "Franklin", "Lovelace", "Hodgkin"], answer: 0 },
            { question: "Which civilization built Machu Picchu?", options: ["Aztec", "Maya", "Inca", "Olmec"], answer: 2 },
            { question: "Who wrote 'The Communist Manifesto'?", options: ["Lenin", "Marx", "Stalin", "Engels"], answer: 1 },
            { question: "When did women get the vote in the US?", options: ["1918", "1920", "1925", "1930"], answer: 1 },
            { question: "Who was the first person to reach the South Pole?", options: ["Scott", "Amundsen", "Shackleton", "Peary"], answer: 1 },
            { question: "What empire did Genghis Khan found?", options: ["Mongol", "Ottoman", "Roman", "Mughal"], answer: 0 },
            { question: "Who was the famous nurse of the Crimean War?", options: ["Florence Nightingale", "Clara Barton", "Mary Seacole", "Edith Cavell"], answer: 0 }
        ]
    },
    "science": {
        name: "Tech & Science",
        emoji: "🔬",
        description: "Discoveries, inventions, and natural phenomena.",
        cards: [
            { question: "What is the powerhouse of the cell?", options: ["Nucleus", "Ribosome", "Mitochondria", "Golgi"], answer: 2 },
            { question: "What is the chemical symbol for Gold?", options: ["Ag", "Au", "Fe", "Cu"], answer: 1 },
            { question: "Which planet is the largest?", options: ["Jupiter", "Saturn", "Neptune", "Uranus"], answer: 0 },
            { question: "What is the boiling point of water?", options: ["90°C", "100°C", "110°C", "120°C"], answer: 1 },
            { question: "Who developed the theory of relativity?", options: ["Newton", "Einstein", "Darwin", "Hawking"], answer: 1 },
            { question: "What gas do humans breathe out?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Helium"], answer: 2 },
            { question: "How many bones are in the human body?", options: ["200", "206", "212", "218"], answer: 1 },
            { question: "What is the closest star to Earth?", options: ["Alpha Centauri", "Sirius", "The Sun", "Betelgeuse"], answer: 2 },
            { question: "Which organ filters blood?", options: ["Heart", "Liver", "Kidney", "Stomach"], answer: 2 },
            { question: "What is the speed of sound?", options: ["343 m/s", "299 m/s", "500 m/s", "1000 m/s"], answer: 0 },
            { question: "Who invented the World Wide Web?", options: ["Gates", "Jobs", "Berners-Lee", "Zuckerberg"], answer: 2 },
            { question: "What does DNA stand for?", options: ["Deoxyribonucleic Acid", "Dynamic Acid", "Double Nucleic Acid", "Direct Acid"], answer: 0 },
            { question: "What is the hardest mineral?", options: ["Topaz", "Quartz", "Diamond", "Corundum"], answer: 2 },
            { question: "Which planet has the Great Red Spot?", options: ["Mars", "Jupiter", "Saturn", "Venus"], answer: 1 },
            { question: "What part of the plant conducts photosynthesis?", options: ["Root", "Stem", "Leaf", "Flower"], answer: 2 },
            { question: "What is H2O?", options: ["Salt", "Water", "Acid", "Base"], answer: 1 },
            { question: "Who discovered penicillin?", options: ["Fleming", "Pasteur", "Curie", "Salk"], answer: 0 },
            { question: "What is the largest organ?", options: ["Liver", "Skin", "Lungs", "Brain"], answer: 1 },
            { question: "Which element is needed for strong bones?", options: ["Iron", "Calcium", "Zinc", "Potassium"], answer: 1 },
            { question: "What galaxy is Earth in?", options: ["Andromeda", "Milky Way", "Triangulum", "Sombrero"], answer: 1 },
            { question: "What is the center of an atom?", options: ["Proton", "Neutron", "Electron", "Nucleus"], answer: 3 },
            { question: "Which animal group has cold blood?", options: ["Mammals", "Birds", "Reptiles", "Insects"], answer: 2 },
            { question: "What force keeps us on the ground?", options: ["Friction", "Gravity", "Magnetism", "Tension"], answer: 1 },
            { question: "Who famously studied chimpanzees?", options: ["Fossey", "Goodall", "Galdikas", "Irwin"], answer: 1 },
            { question: "What is the pH of pure water?", options: ["5", "6", "7", "8"], answer: 2 },
            { question: "Which planet is nicknamed the 'Ice Giant'?", options: ["Mars", "Mercury", "Uranus", "Venus"], answer: 2 },
            { question: "What does CPU stand for?", options: ["Central Processing Unit", "Computer Personal Unit", "Central Power Unit", "Core Processing Unit"], answer: 0 },
            { question: "Who co-founded Microsoft?", options: ["Jobs", "Gates", "Musk", "Bezos"], answer: 1 },
            { question: "What is the study of life called?", options: ["Physics", "Chemistry", "Biology", "Geology"], answer: 2 },
            { question: "How many teeth does an adult human have?", options: ["28", "30", "32", "34"], answer: 2 },
            { question: "What cloud stores data?", options: ["Cumulus", "Stratus", "Cirrus", "The Cloud"], answer: 3 },
            { question: "Which vitamin comes from the sun?", options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], answer: 3 },
            { question: "What layer protects Earth from UV rays?", options: ["Ozone", "Troposphere", "Mesosphere", "Exosphere"], answer: 0 },
            { question: "What is the smallest unit of matter?", options: ["Molecule", "Atom", "Cell", "Electron"], answer: 1 },
            { question: "Which metal is liquid at room temperature?", options: ["Iron", "Mercury", "Gold", "Lead"], answer: 1 },
            { question: "What drives the weather on Earth?", options: ["Moon", "Ocean", "Sun", "Wind"], answer: 2 },
            { question: "Who proposed evolution by natural selection?", options: ["Lamarck", "Darwin", "Mendel", "Wallace"], answer: 1 },
            { question: "What is 0 degrees Kelvin?", options: ["Freezing Point", "Boiling Point", "Absolute Zero", "Room Temp"], answer: 2 },
            { question: "Which planet rotates on its side?", options: ["Earth", "Mars", "Uranus", "Jupiter"], answer: 2 },
            { question: "What type of energy is stored in a battery?", options: ["Kinetic", "Thermal", "Chemical", "Nuclear"], answer: 2 },
            { question: "Who invented the telephone?", options: ["Bell", "Edison", "Tesla", "Marconi"], answer: 0 },
            { question: "What is the rarest blood type?", options: ["A+", "O-", "AB-", "B+"], answer: 2 },
            { question: "Which gas is most abundant in the atmosphere?", options: ["Oxygen", "Nitrogen", "Argon", "CO2"], answer: 1 },
            { question: "What causes tides?", options: ["Sun", "Moon", "Wind", "Rotation"], answer: 1 },
            { question: "Which animal has the largest brain?", options: ["Human", "Elephant", "Sperm Whale", "Dolphin"], answer: 2 },
            { question: "What is the symbol for Iron?", options: ["Ir", "Fe", "In", "I"], answer: 1 },
            { question: "Who is the father of physics?", options: ["Galileo", "Newton", "Einstein", "Bohr"], answer: 1 },
            { question: "What is a group of crows called?", options: ["Flock", "Murder", "Pack", "School"], answer: 1 },
            { question: "How many hearts does an octopus have?", options: ["1", "2", "3", "4"], answer: 2 },
            { question: "What does 'www' stand for?", options: ["World Wide Web", "World Web Wide", "Wide World Web", "Web World Wide"], answer: 0 }
        ]
    },
    "geography": {
        name: "Geography",
        emoji: "🌍",
        description: "Countries, capitals, landmarks, and maps.",
        cards: [
            { question: "What is the largest ocean?", options: ["Atlantic", "Pacific", "Indian", "Arctic"], answer: 1 },
            { question: "Which country has the most people?", options: ["India", "China", "USA", "Indonesia"], answer: 0 },
            { question: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], answer: 2 },
            { question: "Which river is the longest?", options: ["Amazon", "Nile", "Yangtze", "Mississippi"], answer: 1 },
            { question: "What continent is Brazil in?", options: ["North America", "South America", "Africa", "Europe"], answer: 1 },
            { question: "Which country is shaped like a boot?", options: ["Spain", "France", "Italy", "Greece"], answer: 2 },
            { question: "What is the tallest mountain?", options: ["K2", "Everest", "Fuji", "Kilimanjaro"], answer: 1 },
            { question: "Which US state is the largest?", options: ["Texas", "California", "Alaska", "Montana"], answer: 2 },
            { question: "What is the capital of Canada?", options: ["Toronto", "Vancouver", "Montreal", "Ottawa"], answer: 3 },
            { question: "Which desert is the largest?", options: ["Gobi", "Sahara", "Antarctic", "Arabian"], answer: 2 },
            { question: "What country is Paris in?", options: ["Germany", "France", "Italy", "Spain"], answer: 1 },
            { question: "How many continents are there?", options: ["5", "6", "7", "8"], answer: 2 },
            { question: "Which country has the most islands?", options: ["Philippines", "Indonesia", "Sweden", "Canada"], answer: 2 },
            { question: "What is the smallest country?", options: ["Monaco", "Vatican City", "Nauru", "Tuvalu"], answer: 1 },
            { question: "Which ocean is between US and Europe?", options: ["Pacific", "Atlantic", "Indian", "Arctic"], answer: 1 },
            { question: "What represents the 0 degree latitude?", options: ["Equator", "Prime Meridian", "Tropic of Cancer", "Tropic of Capricorn"], answer: 0 },
            { question: "Which country owns Greenland?", options: ["USA", "Canada", "Denmark", "Norway"], answer: 2 },
            { question: "What is the capital of Japan?", options: ["Kyoto", "Osaka", "Tokyo", "Seoul"], answer: 2 },
            { question: "Which continent has no permanent population?", options: ["Australia", "Antarctica", "Africa", "Asia"], answer: 1 },
            { question: "What mountain range separates Europe and Asia?", options: ["Alps", "Himalayas", "Ural", "Andes"], answer: 2 },
            { question: "Which US state has the most people?", options: ["New York", "Texas", "Florida", "California"], answer: 3 },
            { question: "What is the longest river in the US?", options: ["Colorado", "Mississippi", "Missouri", "Ohio"], answer: 2 },
            { question: "Which African country was never colonized?", options: ["Nigeria", "Kenya", "Ethiopia", "Egypt"], answer: 2 },
            { question: "What is the capital of Germany?", options: ["Munich", "Frankfurt", "Hamburg", "Berlin"], answer: 3 },
            { question: "Which country is known as the Land of Rising Sun?", options: ["China", "Japan", "Korea", "Thailand"], answer: 1 },
            { question: "What are the Great Lakes?", options: ["3", "4", "5", "6"], answer: 2 },
            { question: "Which city has the Eiffel Tower?", options: ["London", "Berlin", "Paris", "Rome"], answer: 2 },
            { question: "What river flows through Egypt?", options: ["Amazon", "Nile", "Congo", "Danube"], answer: 1 },
            { question: "Which country has the Great Barrier Reef?", options: ["USA", "Brazil", "Australia", "Mexico"], answer: 2 },
            { question: "What is the capital of Span?", options: ["Barcelona", "Madrid", "Seville", "Valencia"], answer: 1 },
            { question: "Which US state is an island chain?", options: ["Florida", "Hawaii", "Alaska", "Maine"], answer: 1 },
            { question: "What continent is the Sahara in?", options: ["Asia", "Africa", "Australia", "America"], answer: 1 },
            { question: "Which country is famous for tulips?", options: ["France", "Netherlands", "Belgium", "Germany"], answer: 1 },
            { question: "What is the largest island in the world?", options: ["Greenland", "New Guinea", "Borneo", "Madagascar"], answer: 0 },
            { question: "Which city is the Big Apple?", options: ["LA", "Chicago", "NYC", "Miami"], answer: 2 },
            { question: "What connects the Atlantic and Pacific?", options: ["Suez Canal", "Panama Canal", "English Channel", "Strait of Gibraltar"], answer: 1 },
            { question: "Which country has the most languages?", options: ["India", "Nigeria", "Papua New Guinea", "China"], answer: 2 },
            { question: "What is the coldest continent?", options: ["Europe", "North America", "Asia", "Antarctica"], answer: 3 },
            { question: "Which sea is the saltiest?", options: ["Red Sea", "Mediterranean", "Dead Sea", "Black Sea"], answer: 2 },
            { question: "What is the capital of Russia?", options: ["St. Petersburg", "Moscow", "Kiev", "Minsk"], answer: 1 },
            { question: "Which country is the Taj Mahal in?", options: ["Thailand", "India", "Pakistan", "Nepal"], answer: 1 },
            { question: "What is the currency of Japan?", options: ["Yuan", "Won", "Yen", "Dollar"], answer: 2 },
            { question: "Which country is home to kangaroos?", options: ["New Zealand", "Australia", "South Africa", "Austria"], answer: 1 },
            { question: "What is the highest waterfall?", options: ["Niagara", "Victoria", "Angel", "Iguazu"], answer: 2 },
            { question: "Which city is built on canals?", options: ["Paris", "Venice", "London", "Madrid"], answer: 1 },
            { question: "What is the capital of Italy?", options: ["Milan", "Venice", "Florence", "Rome"], answer: 3 },
            { question: "Which country gave us pizza?", options: ["France", "USA", "Italy", "Greece"], answer: 2 },
            { question: "What continent is the Amazon Rainforest in?", options: ["Africa", "Asia", "South America", "North America"], answer: 2 },
            { question: "Which pole has penguins?", options: ["North", "South", "East", "West"], answer: 1 },
            { question: "What is the capital of China?", options: ["Shanghai", "Beijing", "Hong Kong", "Wuhan"], answer: 1 }
        ]
    },
    "literature": {
        name: "Literature",
        emoji: "📚",
        description: "Books, authors, poetry, and plays.",
        cards: [
            { question: "Who wrote 'Harry Potter'?", options: ["Tolkien", "Rowling", "Lewis", "Pullman"], answer: 1 },
            { question: "Who wrote 'Romeo and Juliet'?", options: ["Marlowe", "Shakespeare", "Jonson", "Bacon"], answer: 1 },
            { question: "What is the name of the hobbit protagonist?", options: ["Sam", "Merry", "Frodo", "Pippin"], answer: 2 },
            { question: "Who wrote '1984'?", options: ["Huxley", "Orwell", "Bradbury", "Atwood"], answer: 1 },
            { question: "Which sleuth lives at 221B Baker St?", options: ["Poirot", "Marple", "Holmes", "Dupin"], answer: 2 },
            { question: "Who wrote 'Pride and Prejudice'?", options: ["Bronte", "Austen", "Woolf", "Eliot"], answer: 1 },
            { question: "What is the whale's name in Moby Dick?", options: ["Willy", "Moby Dick", "Monstro", "Shamu"], answer: 1 },
            { question: "Who wrote 'The Great Gatsby'?", options: ["Hemingway", "Fitzgerald", "Steinbeck", "Faulkner"], answer: 1 },
            { question: "Which book series features Katniss?", options: ["Divergent", "Hunger Games", "Maze Runner", "Twilight"], answer: 1 },
            { question: "Who wrote 'To Kill a Mockingbird'?", options: ["Lee", "Capote", "Twain", "Salinger"], answer: 0 },
            { question: "What is the vampire's name in Twilight?", options: ["Jacob", "Edward", "Emmett", "Carlisle"], answer: 1 },
            { question: "Who wrote 'The Lord of the Rings'?", options: ["Lewis", "Tolkien", "Martin", "Jordan"], answer: 1 },
            { question: "Who creates the world of Narnia?", options: ["Aslan", "Gandalf", "Dumbledore", "Merlin"], answer: 0 },
            { question: "Which poet wrote 'The Raven'?", options: ["Frost", "Dickinson", "Poe", "Whitman"], answer: 2 },
            { question: "Who wrote 'Frankenstein'?", options: ["Mary Shelley", "Bram Stoker", "H.G. Wells", "Jules Verne"], answer: 0 },
            { question: "What is the name of the pig in 'Charlotte's Web'?", options: ["Babe", "Wilbur", "Piglet", "Snowball"], answer: 1 },
            { question: "Who wrote 'Game of Thrones'?", options: ["King", "Martin", "Rothfuss", "Sanderson"], answer: 1 },
            { question: "Which play features Hamlet?", options: ["Macbeth", "Othello", "Hamlet", "King Lear"], answer: 2 },
            { question: "Who wrote 'The Shining'?", options: ["Koontz", "King", "Barker", "Lovecraft"], answer: 1 },
            { question: "What is the nanny's name in PL Travers' book?", options: ["Nanny McPhee", "Mary Poppins", "Amelia Bedelia", "Fran Fine"], answer: 1 },
            { question: "Who wrote 'Les Misérables'?", options: ["Dumas", "Hugo", "Verne", "Flaubert"], answer: 1 },
            { question: "Which bear loves honey?", options: ["Paddington", "Winnie the Pooh", "Yogi", "Baloo"], answer: 1 },
            { question: "Who wrote 'The Odyssey'?", options: ["Homer", "Virgil", "Ovid", "Plato"], answer: 0 },
            { question: "What is the name of Sherlock's partner?", options: ["Hastings", "Watson", "Lestrade", "Hudson"], answer: 1 },
            { question: "Who wrote 'Dracula'?", options: ["Shelley", "Stoker", "Rice", "Meyer"], answer: 1 },
            { question: "Which character is 'Oliver Twist'?", options: ["Orphan", "Prince", "Wizard", "Knight"], answer: 0 },
            { question: "Who wrote 'The Catcher in the Rye'?", options: ["Salinger", "Kerouac", "Plath", "Vonnegut"], answer: 0 },
            { question: "Which dystopian novel is by Huxley?", options: ["1984", "Brave New World", "Fahrenheit 451", "The Road"], answer: 1 },
            { question: "Who wrote 'Alice in Wonderland'?", options: ["Carroll", "Barrie", "Potter", "Dahl"], answer: 0 },
            { question: "What color is the letter in Hawthorne's book?", options: ["Red", "Blue", "Black", "Scarlet"], answer: 3 },
            { question: "Who wrote 'Of Mice and Men'?", options: ["Hemingway", "Steinbeck", "Miller", "Williams"], answer: 1 },
            { question: "Which sister wrote 'Jane Eyre'?", options: ["Emily", "Anne", "Charlotte", "Jane"], answer: 2 },
            { question: "Who is the wizard in 'The Hobbit'?", options: ["Saruman", "Radagast", "Gandalf", "Alatar"], answer: 2 },
            { question: "Who wrote 'A Christmas Carol'?", options: ["Dickens", "Twain", "Hardy", "Austen"], answer: 0 },
            { question: "What is the name of Captain Hook's foe?", options: ["Peter Pan", "Wendy", "Smee", "Tiger Lily"], answer: 0 },
            { question: "Who wrote 'Jurassic Park'?", options: ["Crichton", "King", "Grisham", "Clancy"], answer: 0 },
            { question: "Which book has the character Atticus Finch?", options: ["The Help", "To Kill a Mockingbird", "A Time to Kill", "Just Mercy"], answer: 1 },
            { question: "Who wrote 'The Handmaid's Tale'?", options: ["Lessing", "Atwood", "Morrison", "Walker"], answer: 1 },
            { question: "What is the name of the Lion in Narnia?", options: ["Simba", "Mufasa", "Aslan", "Leo"], answer: 2 },
            { question: "Who wrote 'Don Quixote'?", options: ["Cervantes", "Marquez", "Borges", "Neruda"], answer: 0 },
            { question: "Which Shakespeare play has three witches?", options: ["Hamlet", "Macbeth", "Othello", "Tempest"], answer: 1 },
            { question: "Who creates the 'Hunger Games'?", options: ["Collins", "Roth", "Meyer", "Clare"], answer: 0 },
            { question: "What animal is 'Black Beauty'?", options: ["Dog", "Cat", "Horse", "Rabbit"], answer: 2 },
            { question: "Who wrote 'Little Women'?", options: ["Alcott", "Montgomery", "Wilder", "Burnett"], answer: 0 },
            { question: "Which genre is Agatha Christie queen of?", options: ["Romance", "Sci-Fi", "Mystery", "Horror"], answer: 2 },
            { question: "Who wrote 'War and Peace'?", options: ["Dostoevsky", "Tolstoy", "Chekhov", "Gogol"], answer: 1 },
            { question: "What is the name of the whale captain?", options: ["Hook", "Sparrow", "Ahab", "Nemo"], answer: 2 },
            { question: "Who wrote 'The Da Vinci Code'?", options: ["Patterson", "Brown", "Baldacci", "Child"], answer: 1 },
            { question: "Which book features Big Brother?", options: ["1984", "Animal Farm", "We", "Anthem"], answer: 0 },
            { question: "Who wrote 'The Cat in the Hat'?", options: ["Disney", "Seuss", "Sendak", "Silverstein"], answer: 1 }
        ]
    },
    "sports": {
        name: "Sports",
        emoji: "⚽",
        description: "Athletes, teams, rules, and records.",
        cards: [
            { question: "Which sport plays in a diamond?", options: ["Soccer", "Tennis", "Baseball", "Golf"], answer: 2 },
            { question: "How many players on a soccer team?", options: ["9", "10", "11", "12"], answer: 2 },
            { question: "What is the Super Bowl sport?", options: ["Baseball", "Basketball", "Football", "Hockey"], answer: 2 },
            { question: "Which country invented golf?", options: ["USA", "Scotland", "England", "Ireland"], answer: 1 },
            { question: "Who is Usain Bolt?", options: ["Swimmer", "Sprinter", "Boxer", "Cyclist"], answer: 1 },
            { question: "What sport uses a shuttlecock?", options: ["Tennis", "Badminton", "Squash", "Pickleball"], answer: 1 },
            { question: "How many quarters in basketball?", options: ["2", "3", "4", "5"], answer: 2 },
            { question: "Who is Michael Jordan?", options: ["Golfer", "Basketballer", "Footballer", "Actor"], answer: 1 },
            { question: "What is the tour de france?", options: ["Car race", "Bike race", "Running", "Swimming"], answer: 1 },
            { question: "Which sport has a puck?", options: ["Soccer", "Hockey", "Lacrosse", "Polo"], answer: 1 },
            { question: "How many holes in standard golf?", options: ["9", "12", "18", "24"], answer: 2 },
            { question: "Who has the most Olympic medals?", options: ["Bolt", "Phelps", "Biles", "Lewis"], answer: 1 },
            { question: "What is a hat-trick in soccer?", options: ["1 goal", "2 goals", "3 goals", "4 goals"], answer: 2 },
            { question: "Which tennis tournament is on grass?", options: ["US Open", "French Open", "Wimbledon", "Australian Open"], answer: 2 },
            { question: "What value is a touchdown?", options: ["3", "6", "7", "10"], answer: 1 },
            { question: "How long is a marathon?", options: ["13 miles", "26.2 miles", "30 miles", "50 miles"], answer: 1 },
            { question: "Who is Serena Williams?", options: ["Tennis player", "Golfer", "Swimmer", "Runner"], answer: 0 },
            { question: "Which country dominates cricket?", options: ["USA", "India", "Japan", "Brazil"], answer: 1 },
            { question: "What sport uses a net and sand?", options: ["Tennis", "Volleyball", "Soccer", "Badminton"], answer: 1 },
            { question: "How many strikes for an out?", options: ["2", "3", "4", "5"], answer: 1 },
            { question: "What color is a yellow card?", options: ["Red", "Blue", "Green", "Yellow"], answer: 3 },
            { question: "Which sport has a scrum?", options: ["Soccer", "Rugby", "Football", "Hockey"], answer: 1 },
            { question: "Who is 'The Great One' in hockey?", options: ["Crosby", "Gretzky", "Ovechkin", "Lemieux"], answer: 1 },
            { question: "What is the NBA?", options: ["Baseball", "Basketball", "Bowling", "Boxing"], answer: 1 },
            { question: "Which sport uses a heavy ball to pins?", options: ["Billiards", "Bowling", "Bocce", "Curling"], answer: 1 },
            { question: "Who is a famous boxer?", options: ["Ali", "Woods", "Brady", "Messi"], answer: 0 },
            { question: "What is 'love' in tennis?", options: ["Win", "Loss", "Zero", "Tie"], answer: 2 },
            { question: "Which city hosted 2012 Olympics?", options: ["Beijing", "London", "Rio", "Tokyo"], answer: 1 },
            { question: "How many minutes in a soccer match?", options: ["60", "80", "90", "100"], answer: 2 },
            { question: "What sport involves checkmate?", options: ["Checkers", "Chess", "Poker", "Go"], answer: 1 },
            { question: "What is field goal in NFL worth?", options: ["1", "2", "3", "6"], answer: 2 },
            { question: "Which sport has a pitcher?", options: ["Cricket", "Baseball", "Hockey", "Golf"], answer: 1 },
            { question: "Who is Lionel Messi?", options: ["Tennis", "Soccer", "Golf", "F1"], answer: 1 },
            { question: "What is the world's most popular sport?", options: ["Basketball", "Cricket", "Soccer", "Tennis"], answer: 2 },
            { question: "How many players on a basketball court?", options: ["4", "5", "6", "7"], answer: 1 },
            { question: "Which event includes swimming and biking?", options: ["Marathon", "Triathlon", "Decathlon", "Pentathlon"], answer: 1 },
            { question: "What country won 2022 World Cup?", options: ["France", "Brazil", "Argentina", "Germany"], answer: 2 },
            { question: "What is a spare in bowling?", options: ["First try", "Second try", "Third try", "Miss"], answer: 1 },
            { question: "Which sport uses a broom?", options: ["Hockey", "Curling", "Lacrosse", "Polo"], answer: 1 },
            { question: "What is the diameter of a basketball hoop?", options: ["15 inch", "18 inch", "20 inch", "24 inch"], answer: 1 },
            { question: "Who is Tiger Woods?", options: ["Golfer", "Boxer", "Driver", "Runner"], answer: 0 },
            { question: "Which sport has belts (white, black)?", options: ["Boxing", "Karate", "Wrestling", "Fencing"], answer: 1 },
            { question: "How many bases in baseball?", options: ["3", "4", "5", "6"], answer: 1 },
            { question: "What is the FIFA trophy made of?", options: ["Silver", "Gold", "Bronze", "Platinum"], answer: 1 },
            { question: "Which car race is in Monaco?", options: ["Nascar", "F1", "Rally", "Indy"], answer: 1 },
            { question: "What sport is Lebron James in?", options: ["MLB", "NBA", "NFL", "NHL"], answer: 1 },
            { question: "Whose ear did Tyson bite?", options: ["Ali", "Holyfield", "Foreman", "Lewis"], answer: 1 },
            { question: "What is the max score in bowling?", options: ["200", "300", "400", "500"], answer: 1 },
            { question: "Which team is the Yankees?", options: ["Boston", "New York", "Chicago", "LA"], answer: 1 },
            { question: "What is the rings instrument?", options: ["Gymnastics", "Track", "Swimming", "Diving"], answer: 0 }
        ]
    },
    "random": {
        name: "Random Facts",
        emoji: "🎲",
        description: "A mix of everything unpredictable.",
        cards: [
            { question: "How many hearts does an octopus have?", options: ["1", "2", "3", "4"], answer: 2 },
            { question: "Which animal sleep standing up?", options: ["Horse", "Dog", "Cat", "Lion"], answer: 0 },
            { question: "What color is a polar bear's skin?", options: ["White", "Pink", "Black", "Brown"], answer: 2 },
            { question: "How many cards in a deck?", options: ["48", "50", "52", "54"], answer: 2 },
            { question: "Which fruit floats?", options: ["Grape", "Apple", "Mango", "Cherry"], answer: 1 },
            { question: "What is the dot over 'i' called?", options: ["Dot", "Spot", "Tittle", "Mark"], answer: 2 },
            { question: "Can pigs look up at the sky?", options: ["Yes", "No", "Sometimes", "Only piglets"], answer: 1 },
            { question: "Which country eats the most chocolate?", options: ["USA", "Belgium", "Switzerland", "France"], answer: 2 },
            { question: "How long is a gold fish memory?", options: ["3 sec", "3 min", "3 months", "3 years"], answer: 2 },
            { question: "What nut is used for dynamite?", options: ["Walnut", "Peanut", "Almond", "Cashew"], answer: 1 },
            { question: "Which animal has fingerprints?", options: ["Koala", "Sloth", "Canda", "Bear"], answer: 0 },
            { question: "What is the only flying mammal?", options: ["Squirrel", "Bat", "Lemur", "Mouse"], answer: 1 },
            { question: "How many eyes does a bee have?", options: ["2", "3", "4", "5"], answer: 3 },
            { question: "What color is hippo sweat?", options: ["Clear", "Blue", "Red", "Green"], answer: 2 },
            { question: "Which planet spins backwards?", options: ["Mars", "Venus", "Jupiter", "Earth"], answer: 1 },
            { question: "How many legs does a lobster have?", options: ["6", "8", "10", "12"], answer: 2 },
            { question: "What is a group of lions called?", options: ["Pack", "Pride", "School", "Herd"], answer: 1 },
            { question: "Which food never rots?", options: ["Rice", "Honey", "Beans", "Corn"], answer: 1 },
            { question: "What is the fear of clowns?", options: ["Arachnophobia", "Coulrophobia", "Acrophobia", "Clownophobia"], answer: 1 },
            { question: "How many noses does a slug have?", options: ["1", "2", "3", "4"], answer: 3 },
            { question: "Which animal can't jump?", options: ["Elephant", "Hippo", "Rhino", "Giraffe"], answer: 0 },
            { question: "What is the fastest bird?", options: ["Eagle", "Falcon", "Hawk", "Swift"], answer: 1 },
            { question: "How many keys on a piano?", options: ["66", "77", "88", "99"], answer: 2 },
            { question: "What is a baby goat called?", options: ["Calf", "Kid", "Lamb", "Foal"], answer: 1 },
            { question: "Which vegetable is a fruit?", options: ["Carrot", "Potato", "Tomato", "Onion"], answer: 2 },
            { question: "How many teeth does a mosquito have?", options: ["0", "12", "24", "47"], answer: 3 },
            { question: "What is the loudest animal?", options: ["Lion", "Whale", "Elephant", "Monkey"], answer: 1 },
            { question: "Which bird can fly backwards?", options: ["Eagle", "Hummingbird", "Parrot", "Owl"], answer: 1 },
            { question: "How many colors in a rainbow?", options: ["5", "6", "7", "8"], answer: 2 },
            { question: "What is the strongest muscle?", options: ["Bicep", "Tongue", "Heart", "Jaw"], answer: 3 },
            { question: "Which animal never sleeps?", options: ["Shark", "Bullfrog", "Ant", "Dolphin"], answer: 1 },
            { question: "How many chambers in a heart?", options: ["2", "3", "4", "6"], answer: 2 },
            { question: "What is a duel between three people?", options: ["Trio", "Truel", "Tri-fight", "Melee"], answer: 1 },
            { question: "Which country has no river?", options: ["Egypt", "Saudi Arabia", "Iran", "Grece"], answer: 1 },
            { question: "How many stripes on US flag?", options: ["10", "11", "12", "13"], answer: 3 },
            { question: "What is a female donkey called?", options: ["Mare", "Jenny", "Doe", "Ewe"], answer: 1 },
            { question: "Which metal is liquid at room temp?", options: ["Iron", "Lead", "Mercury", "Gold"], answer: 2 },
            { question: "How many sides on a stop sign?", options: ["6", "8", "10", "12"], answer: 1 },
            { question: "What is the main gas in air?", options: ["Oxygen", "Nitrogen", "CO2", "Helium"], answer: 1 },
            { question: "How many weeks in a year?", options: ["48", "50", "52", "54"], answer: 2 },
            { question: "Which geometric shape has 5 sides?", options: ["Hexagon", "Pentagon", "Octagon", "Square"], answer: 1 },
            { question: "What is a baby kangaroo called?", options: ["Kid", "Joey", "Cub", "Calf"], answer: 1 },
            { question: "Which month has 28 days?", options: ["Feb", "All of them", "June", "Dec"], answer: 1 },
            { question: "What is the currency of Russia?", options: ["Euro", "Dollar", "Ruble", "Yen"], answer: 2 },
            { question: "How many humps does a dromedary have?", options: ["1", "2", "3", "4"], answer: 0 },
            { question: "What is the only continent with no bees?", options: ["Asia", "Antarctica", "Australia", "Africa"], answer: 1 },
            { question: "Which animal has blue blood?", options: ["Shark", "Lobster", "Bear", "Wolf"], answer: 1 },
            { question: "How many dots on a dice?", options: ["20", "21", "22", "24"], answer: 1 },
            { question: "What is the tallest grass?", options: ["Wheat", "Bamboo", "Corn", "Rice"], answer: 1 },
            { question: "Which planet is the hottest?", options: ["Mercury", "Venus", "Mars", "Jupiter"], answer: 1 }
        ]
    }
};
