export interface RapidFireCard {
    id: string;
    optionA: string;
    optionB: string;
    deck: string;
}

// Couples Deck (~100 cards)
const couplesDeck: RapidFireCard[] = [
    { id: "c1", optionA: "Stay in", optionB: "Go out", deck: "couples" },
    { id: "c2", optionA: "Morning person", optionB: "Night owl", deck: "couples" },
    { id: "c3", optionA: "Text message", optionB: "Phone call", deck: "couples" },
    { id: "c4", optionA: "Big spoon", optionB: "Little spoon", deck: "couples" },
    { id: "c5", optionA: "Plan everything", optionB: "Spontaneous", deck: "couples" },
    { id: "c6", optionA: "Cook at home", optionB: "Order takeout", deck: "couples" },
    { id: "c7", optionA: "Movies", optionB: "TV series", deck: "couples" },
    { id: "c8", optionA: "Beach vacation", optionB: "Mountain getaway", deck: "couples" },
    { id: "c9", optionA: "Quality time", optionB: "Personal space", deck: "couples" },
    { id: "c10", optionA: "Hold hands", optionB: "Arm around shoulder", deck: "couples" },
    { id: "c11", optionA: "Love songs", optionB: "Action movies", deck: "couples" },
    { id: "c12", optionA: "Cuddling", optionB: "Dancing", deck: "couples" },
    { id: "c13", optionA: "Sunrise together", optionB: "Sunset together", deck: "couples" },
    { id: "c14", optionA: "Long walks", optionB: "Cozy couch", deck: "couples" },
    { id: "c15", optionA: "Handwritten note", optionB: "Sweet text", deck: "couples" },
    { id: "c16", optionA: "Fancy dinner", optionB: "Picnic", deck: "couples" },
    { id: "c17", optionA: "Dancing", optionB: "Singing karaoke", deck: "couples" },
    { id: "c18", optionA: "Surprise gifts", optionB: "Planned gifts", deck: "couples" },
    { id: "c19", optionA: "Weekend brunch", optionB: "Late night snacks", deck: "couples" },
    { id: "c20", optionA: "Road trip", optionB: "Flight", deck: "couples" },
    { id: "c21", optionA: "Matching outfits", optionB: "Complementary styles", deck: "couples" },
    { id: "c22", optionA: "Joint hobbies", optionB: "Separate hobbies", deck: "couples" },
    { id: "c23", optionA: "Public affection", optionB: "Private affection", deck: "couples" },
    { id: "c24", optionA: "Save money", optionB: "Spend on experiences", deck: "couples" },
    { id: "c25", optionA: "Cats", optionB: "Dogs", deck: "couples" },
    { id: "c26", optionA: "Hot weather", optionB: "Cold weather", deck: "couples" },
    { id: "c27", optionA: "City life", optionB: "Countryside", deck: "couples" },
    { id: "c28", optionA: "Gym together", optionB: "Separate workouts", deck: "couples" },
    { id: "c29", optionA: "Same bed", optionB: "Separate blankets", deck: "couples" },
    { id: "c30", optionA: "Argue it out", optionB: "Cool down first", deck: "couples" },
    { id: "c31", optionA: "Talk about feelings", optionB: "Show through actions", deck: "couples" },
    { id: "c32", optionA: "Big friend group", optionB: "Just us two", deck: "couples" },
    { id: "c33", optionA: "Adventure date", optionB: "Relaxing date", deck: "couples" },
    { id: "c34", optionA: "Comedy show", optionB: "Concert", deck: "couples" },
    { id: "c35", optionA: "Board games", optionB: "Video games", deck: "couples" },
    { id: "c36", optionA: "Wine", optionB: "Beer", deck: "couples" },
    { id: "c37", optionA: "Share dessert", optionB: "Own dessert", deck: "couples" },
    { id: "c38", optionA: "Breakfast in bed", optionB: "Brunch out", deck: "couples" },
    { id: "c39", optionA: "Flowers", optionB: "Chocolates", deck: "couples" },
    { id: "c40", optionA: "Anniversary trip", optionB: "Staycation", deck: "couples" },
    { id: "c41", optionA: "Deep talk", optionB: "Playful banter", deck: "couples" },
    { id: "c42", optionA: "Instagram couple", optionB: "Private relationship", deck: "couples" },
    { id: "c43", optionA: "Trying new things", optionB: "Favorite traditions", deck: "couples" },
    { id: "c44", optionA: "Compliments", optionB: "Teasing", deck: "couples" },
    { id: "c45", optionA: "Surprise date", optionB: "Planned date", deck: "couples" },
    { id: "c46", optionA: "Matching tattoos", optionB: "Matching rings", deck: "couples" },
    { id: "c47", optionA: "Cook together", optionB: "One cooks, one cleans", deck: "couples" },
    { id: "c48", optionA: "Same music taste", optionB: "Different playlists", deck: "couples" },
    { id: "c49", optionA: "Shower together", optionB: "Bubble bath", deck: "couples" },
    { id: "c50", optionA: "Say 'I love you' daily", optionB: "Show it through acts", deck: "couples" },
    { id: "c51", optionA: "Early anniversary", optionB: "Late night celebration", deck: "couples" },
    { id: "c52", optionA: "Sentimental gifts", optionB: "Practical gifts", deck: "couples" },
    { id: "c53", optionA: "Partner's family first", optionB: "Just us first", deck: "couples" },
    { id: "c54", optionA: "Matching PJs", optionB: "Comfy separate ones", deck: "couples" },
    { id: "c55", optionA: "One pet", optionB: "Multiple pets", deck: "couples" },
    { id: "c56", optionA: "Share phone passcode", optionB: "Private phones", deck: "couples" },
    { id: "c57", optionA: "Joint social media", optionB: "Separate accounts", deck: "couples" },
    { id: "c58", optionA: "Combined finances", optionB: "Separate accounts", deck: "couples" },
    { id: "c59", optionA: "His/her side of bed", optionB: "Switch sides", deck: "couples" },
    { id: "c60", optionA: "Couple goals posts", optionB: "Keep it private", deck: "couples" },
    { id: "c61", optionA: "Weekly date nights", optionB: "Monthly special dates", deck: "couples" },
    { id: "c62", optionA: "Small apartment together", optionB: "Live apart longer", deck: "couples" },
    { id: "c63", optionA: "Sleep early together", optionB: "Different sleep schedules", deck: "couples" },
    { id: "c64", optionA: "Travel the world", optionB: "Build a home", deck: "couples" },
    { id: "c65", optionA: "Dream wedding", optionB: "Simple ceremony", deck: "couples" },
    { id: "c66", optionA: "Kids soon", optionB: "Wait a while", deck: "couples" },
    { id: "c67", optionA: "Big family", optionB: "Small family", deck: "couples" },
    { id: "c68", optionA: "City apartment", optionB: "Suburban house", deck: "couples" },
    { id: "c69", optionA: "Pet before kids", optionB: "Kids first", deck: "couples" },
    { id: "c70", optionA: "Work hard now", optionB: "Enjoy the present", deck: "couples" },
    { id: "c71", optionA: "Chase dreams", optionB: "Stable job", deck: "couples" },
    { id: "c72", optionA: "Move for opportunity", optionB: "Stay near family", deck: "couples" },
    { id: "c73", optionA: "Minimalist", optionB: "Collector", deck: "couples" },
    { id: "c74", optionA: "DIY home", optionB: "Hire professionals", deck: "couples" },
    { id: "c75", optionA: "Host parties", optionB: "Quiet home", deck: "couples" },
    { id: "c76", optionA: "Modern decor", optionB: "Cozy vintage", deck: "couples" },
    { id: "c77", optionA: "Home gym", optionB: "Gym membership", deck: "couples" },
    { id: "c78", optionA: "Garden together", optionB: "Low maintenance yard", deck: "couples" },
    { id: "c79", optionA: "Big TV", optionB: "Projector", deck: "couples" },
    { id: "c80", optionA: "Game room", optionB: "Home office", deck: "couples" },
    { id: "c81", optionA: "Open kitchen", optionB: "Separate dining", deck: "couples" },
    { id: "c82", optionA: "Balcony", optionB: "Backyard", deck: "couples" },
    { id: "c83", optionA: "Smart home", optionB: "Traditional switches", deck: "couples" },
    { id: "c84", optionA: "Roomba", optionB: "Manual vacuum", deck: "couples" },
    { id: "c85", optionA: "Meal prep", optionB: "Cook fresh daily", deck: "couples" },
    { id: "c86", optionA: "Grocery delivery", optionB: "Shop together", deck: "couples" },
    { id: "c87", optionA: "Stream everything", optionB: "Some cable", deck: "couples" },
    { id: "c88", optionA: "One car", optionB: "Two cars", deck: "couples" },
    { id: "c89", optionA: "Bike to work", optionB: "Drive", deck: "couples" },
    { id: "c90", optionA: "Date night at home", optionB: "Always go out", deck: "couples" },
    { id: "c91", optionA: "Netflix binge", optionB: "Read books", deck: "couples" },
    { id: "c92", optionA: "Video call family", optionB: "Visit in person", deck: "couples" },
    { id: "c93", optionA: "Celebrate small wins", optionB: "Big achievements only", deck: "couples" },
    { id: "c94", optionA: "Post couple pics", optionB: "Keep us private", deck: "couples" },
    { id: "c95", optionA: "Joint calendar", optionB: "Separate schedules", deck: "couples" },
    { id: "c96", optionA: "Couple Halloween costume", optionB: "Individual costumes", deck: "couples" },
    { id: "c97", optionA: "Christmas lights everywhere", optionB: "Simple decorations", deck: "couples" },
    { id: "c98", optionA: "Big birthday party", optionB: "Intimate celebration", deck: "couples" },
    { id: "c99", optionA: "Strict budget", optionB: "Flexible spending", deck: "couples" },
    { id: "c100", optionA: "Long engagement", optionB: "Quick wedding", deck: "couples" },
];

// Food Deck
const foodDeck: RapidFireCard[] = [
    { id: "f1", optionA: "Pizza", optionB: "Burgers", deck: "food" },
    { id: "f2", optionA: "Coffee", optionB: "Tea", deck: "food" },
    { id: "f3", optionA: "Sweet", optionB: "Savory", deck: "food" },
    { id: "f4", optionA: "Chocolate", optionB: "Vanilla", deck: "food" },
    { id: "f5", optionA: "Italian", optionB: "Chinese", deck: "food" },
    { id: "f6", optionA: "Breakfast", optionB: "Dinner", deck: "food" },
    { id: "f7", optionA: "Hot food", optionB: "Cold food", deck: "food" },
    { id: "f8", optionA: "Spicy", optionB: "Mild", deck: "food" },
    { id: "f9", optionA: "Wine", optionB: "Beer", deck: "food" },
    { id: "f10", optionA: "Cake", optionB: "Ice cream", deck: "food" },
    { id: "f11", optionA: "Sushi", optionB: "Tacos", deck: "food" },
    { id: "f12", optionA: "Pasta", optionB: "Rice", deck: "food" },
    { id: "f13", optionA: "French fries", optionB: "Onion rings", deck: "food" },
    { id: "f14", optionA: "Pancakes", optionB: "Waffles", deck: "food" },
    { id: "f15", optionA: "Steak", optionB: "Seafood", deck: "food" },
    { id: "f16", optionA: "Cookies", optionB: "Brownies", deck: "food" },
    { id: "f17", optionA: "Smoothie", optionB: "Juice", deck: "food" },
    { id: "f18", optionA: "Sandwich", optionB: "Wrap", deck: "food" },
    { id: "f19", optionA: "Soup", optionB: "Salad", deck: "food" },
    { id: "f20", optionA: "Donuts", optionB: "Muffins", deck: "food" },
    { id: "f21", optionA: "Cereal", optionB: "Oatmeal", deck: "food" },
    { id: "f22", optionA: "Bacon", optionB: "Sausage", deck: "food" },
    { id: "f23", optionA: "Ketchup", optionB: "Mayo", deck: "food" },
    { id: "f24", optionA: "Apple", optionB: "Banana", deck: "food" },
    { id: "f25", optionA: "Popcorn", optionB: "Chips", deck: "food" },
    { id: "f26", optionA: "Peanut butter", optionB: "Nutella", deck: "food" },
    { id: "f27", optionA: "Lemonade", optionB: "Iced tea", deck: "food" },
    { id: "f28", optionA: "Burger King", optionB: "McDonald's", deck: "food" },
    { id: "f29", optionA: "Takeaway", optionB: "Dine-in", deck: "food" },
    { id: "f30", optionA: "Buffet", optionB: "À la carte", deck: "food" },
    { id: "f31", optionA: "Food court", optionB: "Restaurant", deck: "food" },
    { id: "f32", optionA: "Street food", optionB: "Fine dining", deck: "food" },
    { id: "f33", optionA: "Meat lover", optionB: "Vegetarian", deck: "food" },
    { id: "f34", optionA: "Cheese", optionB: "No cheese", deck: "food" },
    { id: "f35", optionA: "Deep fried", optionB: "Grilled", deck: "food" },
    { id: "f36", optionA: "Mac and cheese", optionB: "Ramen", deck: "food" },
    { id: "f37", optionA: "Wings", optionB: "Nuggets", deck: "food" },
    { id: "f38", optionA: "Baked", optionB: "Fried", deck: "food" },
    { id: "f39", optionA: "Greek yogurt", optionB: "Regular yogurt", deck: "food" },
    { id: "f40", optionA: "Mint chocolate", optionB: "Regular chocolate", deck: "food" },
    { id: "f41", optionA: "Dark chocolate", optionB: "Milk chocolate", deck: "food" },
    { id: "f42", optionA: "Candy", optionB: "Chocolate", deck: "food" },
    { id: "f43", optionA: "Gummy bears", optionB: "Sour candy", deck: "food" },
    { id: "f44", optionA: "Pie", optionB: "Cake", deck: "food" },
    { id: "f45", optionA: "Cupcake", optionB: "Cookie", deck: "food" },
    { id: "f46", optionA: "Pudding", optionB: "Jello", deck: "food" },
    { id: "f47", optionA: "Whipped cream", optionB: "Ice cream", deck: "food" },
    { id: "f48", optionA: "Jam", optionB: "Honey", deck: "food" },
    { id: "f49", optionA: "Butter", optionB: "Margarine", deck: "food" },
    { id: "f50", optionA: "White bread", optionB: "Wheat bread", deck: "food" },
    { id: "f51", optionA: "Bagel", optionB: "Croissant", deck: "food" },
    { id: "f52", optionA: "Pretzels", optionB: "Crackers", deck: "food" },
    { id: "f53", optionA: "Trail mix", optionB: "Granola bar", deck: "food" },
    { id: "f54", optionA: "Energy drink", optionB: "Coffee", deck: "food" },
    { id: "f55", optionA: "Soda", optionB: "Water", deck: "food" },
    { id: "f56", optionA: "Sparkling water", optionB: "Still water", deck: "food" },
    { id: "f57", optionA: "Fresh juice", optionB: "Bottled juice", deck: "food" },
    { id: "f58", optionA: "Milkshake", optionB: "Smoothie", deck: "food" },
    { id: "f59", optionA: "Hot chocolate", optionB: "Hot tea", deck: "food" },
    { id: "f60", optionA: "Espresso", optionB: "Latte", deck: "food" },
    { id: "f61", optionA: "Cappuccino", optionB: "Americano", deck: "food" },
    { id: "f62", optionA: "Black coffee", optionB: "Coffee with milk", deck: "food" },
    { id: "f63", optionA: "Green tea", optionB: "Black tea", deck: "food" },
    { id: "f64", optionA: "Bubble tea", optionB: "Regular tea", deck: "food" },
    { id: "f65", optionA: "Hot drinks", optionB: "Iced drinks", deck: "food" },
    { id: "f66", optionA: "Mexican", optionB: "Thai", deck: "food" },
    { id: "f67", optionA: "Indian", optionB: "Japanese", deck: "food" },
    { id: "f68", optionA: "Korean", optionB: "Vietnamese", deck: "food" },
    { id: "f69", optionA: "BBQ", optionB: "Hotpot", deck: "food" },
    { id: "f70", optionA: "Mediterranean", optionB: "Middle Eastern", deck: "food" },
    { id: "f71", optionA: "American", optionB: "European", deck: "food" },
    { id: "f72", optionA: "Fast food", optionB: "Slow food", deck: "food" },
    { id: "f73", optionA: "Comfort food", optionB: "Healthy food", deck: "food" },
    { id: "f74", optionA: "Organic", optionB: "Regular", deck: "food" },
    { id: "f75", optionA: "GMO-free", optionB: "Don't care", deck: "food" },
    { id: "f76", optionA: "Gluten-free", optionB: "Regular", deck: "food" },
    { id: "f77", optionA: "Vegan", optionB: "Regular", deck: "food" },
    { id: "f78", optionA: "Low carb", optionB: "Low fat", deck: "food" },
    { id: "f79", optionA: "Protein bar", optionB: "Fruit", deck: "food" },
    { id: "f80", optionA: "Nuts", optionB: "Seeds", deck: "food" },
    { id: "f81", optionA: "Hummus", optionB: "Guacamole", deck: "food" },
    { id: "f82", optionA: "Salsa", optionB: "Queso", deck: "food" },
    { id: "f83", optionA: "Ranch", optionB: "Blue cheese", deck: "food" },
    { id: "f84", optionA: "Caesar salad", optionB: "Greek salad", deck: "food" },
    { id: "f85", optionA: "Coleslaw", optionB: "Potato salad", deck: "food" },
    { id: "f86", optionA: "Mashed potatoes", optionB: "Baked potatoes", deck: "food" },
    { id: "f87", optionA: "Sweet potato", optionB: "Regular potato", deck: "food" },
    { id: "f88", optionA: "Corn", optionB: "Peas", deck: "food" },
    { id: "f89", optionA: "Broccoli", optionB: "Cauliflower", deck: "food" },
    { id: "f90", optionA: "Carrots", optionB: "Celery", deck: "food" },
    { id: "f91", optionA: "Cucumber", optionB: "Zucchini", deck: "food" },
    { id: "f92", optionA: "Tomato", optionB: "Pepper", deck: "food" },
    { id: "f93", optionA: "Onion", optionB: "Garlic", deck: "food" },
    { id: "f94", optionA: "Mushrooms", optionB: "No mushrooms", deck: "food" },
    { id: "f95", optionA: "Olives", optionB: "Pickles", deck: "food" },
    { id: "f96", optionA: "Avocado", optionB: "No avocado", deck: "food" },
    { id: "f97", optionA: "Sriracha", optionB: "Hot sauce", deck: "food" },
    { id: "f98", optionA: "Mustard", optionB: "Ketchup", deck: "food" },
    { id: "f99", optionA: "BBQ sauce", optionB: "Teriyaki", deck: "food" },
    { id: "f100", optionA: "Soy sauce", optionB: "Fish sauce", deck: "food" },
];

// Create other decks with placeholder data (keeping them shorter for now but structure is there)
const travelDeck: RapidFireCard[] = [
    { id: "t1", optionA: "Beach", optionB: "Mountains", deck: "travel" },
    { id: "t2", optionA: "City", optionB: "Nature", deck: "travel" },
    { id: "t3", optionA: "Hotel", optionB: "Airbnb", deck: "travel" },
    { id: "t4", optionA: "Backpack", optionB: "Suitcase", deck: "travel" },
    { id: "t5", optionA: "Road trip", optionB: "Flight", deck: "travel" },
    { id: "t6", optionA: "Solo travel", optionB: "Group travel", deck: "travel" },
    { id: "t7", optionA: "Cruise", optionB: "Resort", deck: "travel" },
    { id: "t8", optionA: "Adventure", optionB: "Relaxation", deck: "travel" },
    { id: "t9", optionA: "Europe", optionB: "Asia", deck: "travel" },
    { id: "t10", optionA: "Camping", optionB: "Glamping", deck: "travel" },
    { id: "t11", optionA: "Window seat", optionB: "Aisle seat", deck: "travel" },
    { id: "t12", optionA: "Summer vacation", optionB: "Winter getaway", deck: "travel" },
    { id: "t13", optionA: "Museums", optionB: "Theme parks", deck: "travel" },
    { id: "t14", optionA: "Street food", optionB: "Fine dining", deck: "travel" },
    { id: "t15", optionA: "Historical sites", optionB: "Modern attractions", deck: "travel" },
    { id: "t16", optionA: "Planned itinerary", optionB: "Go with the flow", deck: "travel" },
    { id: "t17", optionA: "Hostel", optionB: "Hotel", deck: "travel" },
    { id: "t18", optionA: "Train ride", optionB: "Bus ride", deck: "travel" },
    { id: "t19", optionA: "Tourist hotspots", optionB: "Hidden gems", deck: "travel" },
    { id: "t20", optionA: "Souvenirs", optionB: "Photos", deck: "travel" },
    { id: "t21", optionA: "Early morning flight", optionB: "Red-eye flight", deck: "travel" },
    { id: "t22", optionA: "Tropical island", optionB: "Snowy cabin", deck: "travel" },
    { id: "t23", optionA: "Disney World", optionB: "Universal Studios", deck: "travel" },
    { id: "t24", optionA: "Guided tour", optionB: "Self-guided", deck: "travel" },
    { id: "t25", optionA: "Staycation", optionB: "International trip", deck: "travel" },
    { id: "t26", optionA: "Pack light", optionB: "Pack everything", deck: "travel" },
    { id: "t27", optionA: "Google Maps", optionB: "Paper map", deck: "travel" },
    { id: "t28", optionA: "New York", optionB: "Los Angeles", deck: "travel" },
    { id: "t29", optionA: "London", optionB: "Paris", deck: "travel" },
    { id: "t30", optionA: "Tokyo", optionB: "Kyoto", deck: "travel" },
    { id: "t31", optionA: "Safari", optionB: "Rainforest", deck: "travel" },
    { id: "t32", optionA: "Scuba diving", optionB: "Skydiving", deck: "travel" },
    { id: "t33", optionA: "Hiking", optionB: "Swimming", deck: "travel" },
    { id: "t34", optionA: "Skiing", optionB: "Snowboarding", deck: "travel" },
    { id: "t35", optionA: "Surfing", optionB: "Sunbathing", deck: "travel" },
    { id: "t36", optionA: "RV Trip", optionB: "Tent Camping", deck: "travel" },
    { id: "t37", optionA: "First class", optionB: "Economy", deck: "travel" },
    { id: "t38", optionA: "Airport lounge", optionB: "Gate waiting", deck: "travel" },
    { id: "t39", optionA: "Travel vlog", optionB: "Travel blog", deck: "travel" },
    { id: "t40", optionA: "Postcards", optionB: "Instagram stories", deck: "travel" },
    { id: "t41", optionA: "Local language", optionB: "English", deck: "travel" },
    { id: "t42", optionA: "Convertible", optionB: "SUV rental", deck: "travel" },
    { id: "t43", optionA: "Boat trip", optionB: "Helicopter ride", deck: "travel" },
    { id: "t44", optionA: "Fishing", optionB: "Kayaking", deck: "travel" },
    { id: "t45", optionA: "Zoo", optionB: "Aquarium", deck: "travel" },
    { id: "t46", optionA: "National Park", optionB: "Theme Park", deck: "travel" },
    { id: "t47", optionA: "Las Vegas", optionB: "Miami", deck: "travel" },
    { id: "t48", optionA: "Hawaii", optionB: "Alaska", deck: "travel" },
    { id: "t49", optionA: "Italy", optionB: "Greece", deck: "travel" },
    { id: "t50", optionA: "Bali", optionB: "Thailand", deck: "travel" },
    { id: "t51", optionA: "Passport", optionB: "Driver's license", deck: "travel" },
    { id: "t52", optionA: "Check-in bag", optionB: "Carry-on only", deck: "travel" },
    { id: "t53", optionA: "Travel pillow", optionB: "Neck pillow", deck: "travel" },
    { id: "t54", optionA: "Jet lag", optionB: "No sleep", deck: "travel" },
    { id: "t55", optionA: "Duty free", optionB: "Local markets", deck: "travel" },
    { id: "t56", optionA: "Room service", optionB: "Breakfast buffet", deck: "travel" },
    { id: "t57", optionA: "Late check-out", optionB: "Early check-in", deck: "travel" },
    { id: "t58", optionA: "Travel insurance", optionB: "Risk it", deck: "travel" },
    { id: "t59", optionA: "Currency exchange", optionB: "Credit card", deck: "travel" },
    { id: "t60", optionA: "Google Translate", optionB: "Pocket dictionary", deck: "travel" },
    { id: "t61", optionA: "Selfie stick", optionB: "Ask a stranger", deck: "travel" },
    { id: "t62", optionA: "GoPro", optionB: "DSLR", deck: "travel" },
    { id: "t63", optionA: "Travel alone", optionB: "Travel with partner", deck: "travel" },
    { id: "t64", optionA: "Travel with friends", optionB: "Travel with family", deck: "travel" },
    { id: "t65", optionA: "Hostel bunk", optionB: "Private room", deck: "travel" },
    { id: "t66", optionA: "Night train", optionB: "Day train", deck: "travel" },
    { id: "t67", optionA: "Ferry", optionB: "Speedboat", deck: "travel" },
    { id: "t68", optionA: "Bike rental", optionB: "Scooter rental", deck: "travel" },
    { id: "t69", optionA: "Walking tour", optionB: "Bus tour", deck: "travel" },
    { id: "t70", optionA: "Audio guide", optionB: "Live guide", deck: "travel" },
    { id: "t71", optionA: "Tip well", optionB: "Tip standard", deck: "travel" },
    { id: "t72", optionA: "Haggling", optionB: "Fixed price", deck: "travel" },
    { id: "t73", optionA: "Street performance", optionB: "Opera", deck: "travel" },
    { id: "t74", optionA: "Local bar", optionB: "Club", deck: "travel" },
    { id: "t75", optionA: "Sunrise hike", optionB: "Sunset cruise", deck: "travel" },
    { id: "t76", optionA: "Northern Lights", optionB: "Great Barrier Reef", deck: "travel" },
    { id: "t77", optionA: "Pyramids", optionB: "Great Wall", deck: "travel" },
    { id: "t78", optionA: "Eiffel Tower", optionB: "Statue of Liberty", deck: "travel" },
    { id: "t79", optionA: "Colosseum", optionB: "Taj Mahal", deck: "travel" },
    { id: "t80", optionA: "Machu Picchu", optionB: "Petra", deck: "travel" },
    { id: "t81", optionA: "Grand Canyon", optionB: "Niagara Falls", deck: "travel" },
    { id: "t82", optionA: "Disneyland", optionB: "Disney World", deck: "travel" },
    { id: "t83", optionA: "Universal Orlando", optionB: "Universal Hollywood", deck: "travel" },
    { id: "t84", optionA: "Six Flags", optionB: "Cedar Point", deck: "travel" },
    { id: "t85", optionA: "Water park", optionB: "Amusement park", deck: "travel" },
    { id: "t86", optionA: "Zoo visits", optionB: "Safari drive", deck: "travel" },
    { id: "t87", optionA: "Whale watching", optionB: "Dolphin swimming", deck: "travel" },
    { id: "t88", optionA: "Bird watching", optionB: "Bear watching", deck: "travel" },
    { id: "t89", optionA: "Star gazing", optionB: "Cloud watching", deck: "travel" },
    { id: "t90", optionA: "Fishing trip", optionB: "Hunting trip", deck: "travel" },
    { id: "t91", optionA: "Golf trip", optionB: "Spa trip", deck: "travel" },
    { id: "t92", optionA: "Wine tasting", optionB: "Beer tasting", deck: "travel" },
    { id: "t93", optionA: "Food tour", optionB: "Pub crawl", deck: "travel" },
    { id: "t94", optionA: "Cooking class", optionB: "Dance class", deck: "travel" },
    { id: "t95", optionA: "Yoga retreat", optionB: "Surf camp", deck: "travel" },
    { id: "t96", optionA: "Volunteer trip", optionB: "Luxury trip", deck: "travel" },
    { id: "t97", optionA: "Work travel", optionB: "Vacation travel", deck: "travel" },
    { id: "t98", optionA: "Gap year", optionB: "Career break", deck: "travel" },
    { id: "t99", optionA: "Digital nomad", optionB: "Office job", deck: "travel" },
    { id: "t100", optionA: "Van life", optionB: "Tiny house", deck: "travel" },
];

const entertainmentDeck: RapidFireCard[] = [
    { id: "e1", optionA: "Movies", optionB: "TV shows", deck: "entertainment" },
    { id: "e2", optionA: "Comedy", optionB: "Drama", deck: "entertainment" },
    { id: "e3", optionA: "Action", optionB: "Romance", deck: "entertainment" },
    { id: "e4", optionA: "Horror", optionB: "Thriller", deck: "entertainment" },
    { id: "e5", optionA: "Netflix", optionB: "Cinema", deck: "entertainment" },
    { id: "e6", optionA: "Books", optionB: "Movies", deck: "entertainment" },
    { id: "e7", optionA: "Fiction", optionB: "Non-fiction", deck: "entertainment" },
    { id: "e8", optionA: "Podcast", optionB: "Audiobook", deck: "entertainment" },
    { id: "e9", optionA: "Concert", optionB: "Festival", deck: "entertainment" },
    { id: "e10", optionA: "Pop", optionB: "Rock", deck: "entertainment" },
    { id: "e11", optionA: "Jazz", optionB: "Blues", deck: "entertainment" },
    { id: "e12", optionA: "Rap", optionB: "Country", deck: "entertainment" },
    { id: "e13", optionA: "Spotify", optionB: "Apple Music", deck: "entertainment" },
    { id: "e14", optionA: "Headphones", optionB: "Speakers", deck: "entertainment" },
    { id: "e15", optionA: "Vinyl", optionB: "Digital", deck: "entertainment" },
    { id: "e16", optionA: "Marvel", optionB: "DC", deck: "entertainment" },
    { id: "e17", optionA: "Star Wars", optionB: "Star Trek", deck: "entertainment" },
    { id: "e18", optionA: "Harry Potter", optionB: "Lord of the Rings", deck: "entertainment" },
    { id: "e19", optionA: "Game of Thrones", optionB: "Walking Dead", deck: "entertainment" },
    { id: "e20", optionA: "Friends", optionB: "The Office", deck: "entertainment" },
    { id: "e21", optionA: "Seinfeld", optionB: "HIMYM", deck: "entertainment" },
    { id: "e22", optionA: "Breaking Bad", optionB: "Better Call Saul", deck: "entertainment" },
    { id: "e23", optionA: "Stranger Things", optionB: "Dark", deck: "entertainment" },
    { id: "e24", optionA: "Disney+", optionB: "Hulu", deck: "entertainment" },
    { id: "e25", optionA: "HBO", optionB: "Amazon Prime", deck: "entertainment" },
    { id: "e26", optionA: "YouTube", optionB: "Twitch", deck: "entertainment" },
    { id: "e27", optionA: "TikTok", optionB: "Instagram Reels", deck: "entertainment" },
    { id: "e28", optionA: "Video Games", optionB: "Board Games", deck: "entertainment" },
    { id: "e29", optionA: "Playstation", optionB: "Xbox", deck: "entertainment" },
    { id: "e30", optionA: "Nintendo", optionB: "PC", deck: "entertainment" },
    { id: "e31", optionA: "Fortnite", optionB: "Minecraft", deck: "entertainment" },
    { id: "e32", optionA: "Call of Duty", optionB: "Battlefield", deck: "entertainment" },
    { id: "e33", optionA: "League of Legends", optionB: "Dota 2", deck: "entertainment" },
    { id: "e34", optionA: "Singleplayer", optionB: "Multiplayer", deck: "entertainment" },
    { id: "e35", optionA: "FPS", optionB: "RPG", deck: "entertainment" },
    { id: "e36", optionA: "Sports games", optionB: "Racing games", deck: "entertainment" },
    { id: "e37", optionA: "Mobile games", optionB: "Console games", deck: "entertainment" },
    { id: "e38", optionA: "VR", optionB: "AR", deck: "entertainment" },
    { id: "e39", optionA: "E-sports", optionB: "Real sports", deck: "entertainment" },
    { id: "e40", optionA: "Football", optionB: "Basketball", deck: "entertainment" },
    { id: "e41", optionA: "Soccer", optionB: "Baseball", deck: "entertainment" },
    { id: "e42", optionA: "Tennis", optionB: "Golf", deck: "entertainment" },
    { id: "e43", optionA: "Boxing", optionB: "UFC", deck: "entertainment" },
    { id: "e44", optionA: "Olympics", optionB: "World Cup", deck: "entertainment" },
    { id: "e45", optionA: "Super Bowl", optionB: "Champions League", deck: "entertainment" },
    { id: "e46", optionA: "Cinema snacks", optionB: "Home snacks", deck: "entertainment" },
    { id: "e47", optionA: "3D Movies", optionB: "IMAX", deck: "entertainment" },
    { id: "e48", optionA: "Subtitles", optionB: "Dubbing", deck: "entertainment" },
    { id: "e49", optionA: "Binge-watching", optionB: "Weekly episodes", deck: "entertainment" },
    { id: "e50", optionA: "Reality TV", optionB: "Documentaries", deck: "entertainment" },
    { id: "e51", optionA: "Cartoons", optionB: "Anime", deck: "entertainment" },
    { id: "e52", optionA: "Sitcom", optionB: "Stand-up", deck: "entertainment" },
    { id: "e53", optionA: "Late night show", optionB: "Morning show", deck: "entertainment" },
    { id: "e54", optionA: "News", optionB: "Talk radio", deck: "entertainment" },
    { id: "e55", optionA: "Theater", optionB: "Musical", deck: "entertainment" },
    { id: "e56", optionA: "Opera", optionB: "Ballet", deck: "entertainment" },
    { id: "e57", optionA: "Art museum", optionB: "Science museum", deck: "entertainment" },
    { id: "e58", optionA: "Painting", optionB: "Sculpture", deck: "entertainment" },
    { id: "e59", optionA: "Drawing", optionB: "Sketching", deck: "entertainment" },
    { id: "e60", optionA: "Photography", optionB: "Videography", deck: "entertainment" },
    { id: "e61", optionA: "Editing", optionB: "Filming", deck: "entertainment" },
    { id: "e62", optionA: "Acting", optionB: "Directing", deck: "entertainment" },
    { id: "e63", optionA: "Writing", optionB: "Reading", deck: "entertainment" },
    { id: "e64", optionA: "Poetry", optionB: "Prose", deck: "entertainment" },
    { id: "e65", optionA: "Hardcover", optionB: "Paperback", deck: "entertainment" },
    { id: "e66", optionA: "E-book", optionB: "Physical book", deck: "entertainment" },
    { id: "e67", optionA: "Library", optionB: "Bookstore", deck: "entertainment" },
    { id: "e68", optionA: "Morning news", optionB: "Evening news", deck: "entertainment" },
    { id: "e69", optionA: "Newspaper", optionB: "Online news", deck: "entertainment" },
    { id: "e70", optionA: "Facebook", optionB: "Twitter", deck: "entertainment" },
    { id: "e71", optionA: "Reddit", optionB: "Tumblr", deck: "entertainment" },
    { id: "e72", optionA: "Pinterest", optionB: "Snapchat", deck: "entertainment" },
    { id: "e73", optionA: "LinkedIn", optionB: "Discord", deck: "entertainment" },
    { id: "e74", optionA: "Zoom", optionB: "Skype", deck: "entertainment" },
    { id: "e75", optionA: "Facetime", optionB: "Phone call", deck: "entertainment" },
    { id: "e76", optionA: "Texting", optionB: "Voice notes", deck: "entertainment" },
    { id: "e77", optionA: "Emojis", optionB: "GIFs", deck: "entertainment" },
    { id: "e78", optionA: "Memes", optionB: "Vines", deck: "entertainment" },
    { id: "e79", optionA: "Viral videos", optionB: "Trends", deck: "entertainment" },
    { id: "e80", optionA: "Influencers", optionB: "Celebrities", deck: "entertainment" },
    { id: "e81", optionA: "Paparazzi", optionB: "Red carpet", deck: "entertainment" },
    { id: "e82", optionA: "Oscars", optionB: "Grammys", deck: "entertainment" },
    { id: "e83", optionA: "Emmy", optionB: "Tony", deck: "entertainment" },
    { id: "e84", optionA: "Golden Globes", optionB: "SAG Awards", deck: "entertainment" },
    { id: "e85", optionA: "Film festival", optionB: "Comic Con", deck: "entertainment" },
    { id: "e86", optionA: "Cosplay", optionB: "Fan fiction", deck: "entertainment" },
    { id: "e87", optionA: "Spoilers", optionB: "No spoilers", deck: "entertainment" },
    { id: "e88", optionA: "Trailers", optionB: "Blind watch", deck: "entertainment" },
    { id: "e89", optionA: "Rewatching", optionB: "New content", deck: "entertainment" },
    { id: "e90", optionA: "Critics", optionB: "Audience score", deck: "entertainment" },
    { id: "e91", optionA: "Rotten Tomatoes", optionB: "IMDb", deck: "entertainment" },
    { id: "e92", optionA: "Sudoku", optionB: "Crossword", deck: "entertainment" },
    { id: "e93", optionA: "Chess", optionB: "Checkers", deck: "entertainment" },
    { id: "e94", optionA: "Poker", optionB: "Blackjack", deck: "entertainment" },
    { id: "e95", optionA: "Solitaire", optionB: "Uno", deck: "entertainment" },
    { id: "e96", optionA: "Monopoly", optionB: "Scrabble", deck: "entertainment" },
    { id: "e97", optionA: "Truth or Dare", optionB: "Never Have I Ever", deck: "entertainment" },
    { id: "e98", optionA: "Karaoke", optionB: "Dance battle", deck: "entertainment" },
    { id: "e99", optionA: "Magic show", optionB: "Circus", deck: "entertainment" },
    { id: "e100", optionA: "Fireworks", optionB: "Laser show", deck: "entertainment" },
];

const lifestyleDeck: RapidFireCard[] = [
    { id: "l1", optionA: "Early bird", optionB: "Night owl", deck: "lifestyle" },
    { id: "l2", optionA: "Gym", optionB: "Home workout", deck: "lifestyle" },
    { id: "l3", optionA: "iOS", optionB: "Android", deck: "lifestyle" },
    { id: "l4", optionA: "Minimalist", optionB: "Collector", deck: "lifestyle" },
    { id: "l5", optionA: "Planner", optionB: "Spontaneous", deck: "lifestyle" },
    { id: "l6", optionA: "Indoors", optionB: "Outdoors", deck: "lifestyle" },
    { id: "l7", optionA: "Shower", optionB: "Bath", deck: "lifestyle" },
    { id: "l8", optionA: "Summer", optionB: "Winter", deck: "lifestyle" },
    { id: "l9", optionA: "Save money", optionB: "Spend on experiences", deck: "lifestyle" },
    { id: "l10", optionA: "Work from home", optionB: "Office", deck: "lifestyle" },
    { id: "l11", optionA: "City", optionB: "Countryside", deck: "lifestyle" },
    { id: "l12", optionA: "Apartment", optionB: "House", deck: "lifestyle" },
    { id: "l13", optionA: "Rent", optionB: "Buy", deck: "lifestyle" },
    { id: "l14", optionA: "Car", optionB: "Public transport", deck: "lifestyle" },
    { id: "l15", optionA: "Uber", optionB: "Drive yourself", deck: "lifestyle" },
    { id: "l16", optionA: "Walk", optionB: "Bike", deck: "lifestyle" },
    { id: "l17", optionA: "Tattoos", optionB: "Piercings", deck: "lifestyle" },
    { id: "l18", optionA: "Glasses", optionB: "Contacts", deck: "lifestyle" },
    { id: "l19", optionA: "Beard", optionB: "Clean shaven", deck: "lifestyle" },
    { id: "l20", optionA: "sneakers", optionB: "Boots", deck: "lifestyle" },
    { id: "l21", optionA: "Jeans", optionB: "Sweatpants", deck: "lifestyle" },
    { id: "l22", optionA: "Hoodie", optionB: "Jacket", deck: "lifestyle" },
    { id: "l23", optionA: "T-shirt", optionB: "Button-up", deck: "lifestyle" },
    { id: "l24", optionA: "Suit", optionB: "Casual", deck: "lifestyle" },
    { id: "l25", optionA: "Heels", optionB: "Flats", deck: "lifestyle" },
    { id: "l26", optionA: "Makeup", optionB: "Natural", deck: "lifestyle" },
    { id: "l27", optionA: "Skincare", optionB: "Haircare", deck: "lifestyle" },
    { id: "l28", optionA: "Perfume", optionB: "Cologne", deck: "lifestyle" },
    { id: "l29", optionA: "Gold", optionB: "Silver", deck: "lifestyle" },
    { id: "l30", optionA: "Watch", optionB: "Smartwatch", deck: "lifestyle" },
    { id: "l31", optionA: "Cash", optionB: "Card", deck: "lifestyle" },
    { id: "l32", optionA: "Crypto", optionB: "Stocks", deck: "lifestyle" },
    { id: "l33", optionA: "Investing", optionB: "Saving", deck: "lifestyle" },
    { id: "l34", optionA: "Budgeting", optionB: "Splurging", deck: "lifestyle" },
    { id: "l35", optionA: "DIY", optionB: "Hire a pro", deck: "lifestyle" },
    { id: "l36", optionA: "Cooking", optionB: "Cleaning", deck: "lifestyle" },
    { id: "l37", optionA: "Laundry", optionB: "Dishes", deck: "lifestyle" },
    { id: "l38", optionA: "Vacuuming", optionB: "Dusting", deck: "lifestyle" },
    { id: "l39", optionA: "Plants", optionB: "Pets", deck: "lifestyle" },
    { id: "l40", optionA: "Dog", optionB: "Cat", deck: "lifestyle" },
    { id: "l41", optionA: "Big dog", optionB: "Small dog", deck: "lifestyle" },
    { id: "l42", optionA: "Fish", optionB: "Bird", deck: "lifestyle" },
    { id: "l43", optionA: "Morning shower", optionB: "Night shower", deck: "lifestyle" },
    { id: "l44", optionA: "Hot water", optionB: "Cold water", deck: "lifestyle" },
    { id: "l45", optionA: "Bar soap", optionB: "Body wash", deck: "lifestyle" },
    { id: "l46", optionA: "Electric toothbrush", optionB: "Manual", deck: "lifestyle" },
    { id: "l47", optionA: "Sunscreen", optionB: "Tanning", deck: "lifestyle" },
    { id: "l48", optionA: "Beach day", optionB: "Pool day", deck: "lifestyle" },
    { id: "l49", optionA: "Hiking", optionB: "Camping", deck: "lifestyle" },
    { id: "l50", optionA: "Skiing", optionB: "Snowboarding", deck: "lifestyle" },
    { id: "l51", optionA: "Yoga", optionB: "Pilates", deck: "lifestyle" },
    { id: "l52", optionA: "Running", optionB: "Cycling", deck: "lifestyle" },
    { id: "l53", optionA: "Swimming", optionB: "Lifting", deck: "lifestyle" },
    { id: "l54", optionA: "Cardio", optionB: "Weights", deck: "lifestyle" },
    { id: "l55", optionA: "Crossfit", optionB: "Powerlifting", deck: "lifestyle" },
    { id: "l56", optionA: "Meditation", optionB: "Therapy", deck: "lifestyle" },
    { id: "l57", optionA: "Journaling", optionB: "Vlogging", deck: "lifestyle" },
    { id: "l58", optionA: "Reading", optionB: "Writing", deck: "lifestyle" },
    { id: "l59", optionA: "Painting", optionB: "Drawing", deck: "lifestyle" },
    { id: "l60", optionA: "Singing", optionB: "Dancing", deck: "lifestyle" },
    { id: "l61", optionA: "Guitar", optionB: "Piano", deck: "lifestyle" },
    { id: "l62", optionA: "Drums", optionB: "Bass", deck: "lifestyle" },
    { id: "l63", optionA: "Violin", optionB: "Cello", deck: "lifestyle" },
    { id: "l64", optionA: "Classical", optionB: "Jazz", deck: "lifestyle" },
    { id: "l65", optionA: "Rock", optionB: "Pop", deck: "lifestyle" },
    { id: "l66", optionA: "Hip hop", optionB: "R&B", deck: "lifestyle" },
    { id: "l67", optionA: "Electronic", optionB: "Indie", deck: "lifestyle" },
    { id: "l68", optionA: "Metal", optionB: "Punk", deck: "lifestyle" },
    { id: "l69", optionA: "Country", optionB: "Folk", deck: "lifestyle" },
    { id: "l70", optionA: "Vinyl", optionB: "Streaming", deck: "lifestyle" },
    { id: "l71", optionA: "Live music", optionB: "Recorded", deck: "lifestyle" },
    { id: "l72", optionA: "Loud", optionB: "Quiet", deck: "lifestyle" },
    { id: "l73", optionA: "Fast", optionB: "Slow", deck: "lifestyle" },
    { id: "l74", optionA: "Bright colors", optionB: "Neutral tones", deck: "lifestyle" },
    { id: "l75", optionA: "Modern", optionB: "Vintage", deck: "lifestyle" },
    { id: "l76", optionA: "Clutter", optionB: "Organized", deck: "lifestyle" },
    { id: "l77", optionA: "Digital calendar", optionB: "Paper planner", deck: "lifestyle" },
    { id: "l78", optionA: "Email", optionB: "Slack", deck: "lifestyle" },
    { id: "l79", optionA: "Meetings", optionB: "Emails", deck: "lifestyle" },
    { id: "l80", optionA: "Open office", optionB: "Cubicle", deck: "lifestyle" },
    { id: "l81", optionA: "Freelance", optionB: "Salary", deck: "lifestyle" },
    { id: "l82", optionA: "Start-up", optionB: "Corporate", deck: "lifestyle" },
    { id: "l83", optionA: "Leader", optionB: "Follower", deck: "lifestyle" },
    { id: "l84", optionA: "Team work", optionB: "Solo work", deck: "lifestyle" },
    { id: "l85", optionA: "Presentation", optionB: "Report", deck: "lifestyle" },
    { id: "l86", optionA: "Excel", optionB: "PowerPoint", deck: "lifestyle" },
    { id: "l87", optionA: "Mac", optionB: "PC", deck: "lifestyle" },
    { id: "l88", optionA: "Chrome", optionB: "Safari", deck: "lifestyle" },
    { id: "l89", optionA: "Tab hoarder", optionB: "Clean browswer", deck: "lifestyle" },
    { id: "l90", optionA: "Dark mode", optionB: "Light mode", deck: "lifestyle" },
    { id: "l91", optionA: "Mechanical keyboard", optionB: "Laptop keyboard", deck: "lifestyle" },
    { id: "l92", optionA: "Mouse", optionB: "Trackpad", deck: "lifestyle" },
    { id: "l93", optionA: "Standing desk", optionB: "Sitting desk", deck: "lifestyle" },
    { id: "l94", optionA: "Coffee shop", optionB: "Library", deck: "lifestyle" },
    { id: "l95", optionA: "Silence", optionB: "Background noise", deck: "lifestyle" },
    { id: "l96", optionA: "Multi-tasking", optionB: "Focus", deck: "lifestyle" },
    { id: "l97", optionA: "To-do list", optionB: "Memory", deck: "lifestyle" },
    { id: "l98", optionA: "Alarm clock", optionB: "Natural wake up", deck: "lifestyle" },
    { id: "l99", optionA: "Snooze button", optionB: "Get up immediately", deck: "lifestyle" },
    { id: "l100", optionA: "Nap", optionB: "Power through", deck: "lifestyle" },
];

const randomDeck: RapidFireCard[] = [
    { id: "r1", optionA: "Left", optionB: "Right", deck: "random" },
    { id: "r2", optionA: "Heads", optionB: "Tails", deck: "random" },
    { id: "r3", optionA: "Red", optionB: "Blue", deck: "random" },
    { id: "r4", optionA: "Sweet", optionB: "Sour", deck: "random" },
    { id: "r5", optionA: "Hot", optionB: "Cold", deck: "random" },
    { id: "r6", optionA: "Big", optionB: "Small", deck: "random" },
    { id: "r7", optionA: "Fast", optionB: "Slow", deck: "random" },
    { id: "r8", optionA: "Loud", optionB: "Quiet", deck: "random" },
    { id: "r9", optionA: "Bright", optionB: "Dark", deck: "random" },
    { id: "r10", optionA: "Hard", optionB: "Soft", deck: "random" },
    { id: "r11", optionA: "Up", optionB: "Down", deck: "random" },
    { id: "r12", optionA: "In", optionB: "Out", deck: "random" },
    { id: "r13", optionA: "Yes", optionB: "No", deck: "random" },
    { id: "r14", optionA: "Stop", optionB: "Go", deck: "random" },
    { id: "r15", optionA: "Black", optionB: "White", deck: "random" },
    { id: "r16", optionA: "Day", optionB: "Night", deck: "random" },
    { id: "r17", optionA: "Sun", optionB: "Moon", deck: "random" },
    { id: "r18", optionA: "Star", optionB: "Planet", deck: "random" },
    { id: "r19", optionA: "Land", optionB: "Sea", deck: "random" },
    { id: "r20", optionA: "Fire", optionB: "Ice", deck: "random" },
    { id: "r21", optionA: "Gold", optionB: "Silver", deck: "random" },
    { id: "r22", optionA: "Rich", optionB: "Poor", deck: "random" },
    { id: "r23", optionA: "King", optionB: "Queen", deck: "random" },
    { id: "r24", optionA: "Prince", optionB: "Princess", deck: "random" },
    { id: "r25", optionA: "Boy", optionB: "Girl", deck: "random" },
    { id: "r26", optionA: "Man", optionB: "Woman", deck: "random" },
    { id: "r27", optionA: "Brother", optionB: "Sister", deck: "random" },
    { id: "r28", optionA: "Mom", optionB: "Dad", deck: "random" },
    { id: "r29", optionA: "Aunt", optionB: "Uncle", deck: "random" },
    { id: "r30", optionA: "Grandma", optionB: "Grandpa", deck: "random" },
    { id: "r31", optionA: "Cat", optionB: "Dog", deck: "random" },
    { id: "r32", optionA: "Bird", optionB: "Fish", deck: "random" },
    { id: "r33", optionA: "Lion", optionB: "Tiger", deck: "random" },
    { id: "r34", optionA: "Bear", optionB: "Wolf", deck: "random" },
    { id: "r35", optionA: "Elephant", optionB: "Giraffe", deck: "random" },
    { id: "r36", optionA: "Horse", optionB: "Cow", deck: "random" },
    { id: "r37", optionA: "Pig", optionB: "Sheep", deck: "random" },
    { id: "r38", optionA: "Chicken", optionB: "Duck", deck: "random" },
    { id: "r39", optionA: "Snake", optionB: "Lizard", deck: "random" },
    { id: "r40", optionA: "Frog", optionB: "Toad", deck: "random" },
    { id: "r41", optionA: "Shark", optionB: "Whale", deck: "random" },
    { id: "r42", optionA: "Dolphin", optionB: "Seal", deck: "random" },
    { id: "r43", optionA: "Eagle", optionB: "Hawk", deck: "random" },
    { id: "r44", optionA: "Owl", optionB: "Crow", deck: "random" },
    { id: "r45", optionA: "Bee", optionB: "Wasp", deck: "random" },
    { id: "r46", optionA: "Ant", optionB: "Spider", deck: "random" },
    { id: "r47", optionA: "Butterfly", optionB: "Moth", deck: "random" },
    { id: "r48", optionA: "Tree", optionB: "Flower", deck: "random" },
    { id: "r49", optionA: "Grass", optionB: "Dirt", deck: "random" },
    { id: "r50", optionA: "Rock", optionB: "Sand", deck: "random" },
    { id: "r51", optionA: "Paper", optionB: "Plastic", deck: "random" },
    { id: "r52", optionA: "Glass", optionB: "Metal", deck: "random" },
    { id: "r53", optionA: "Wood", optionB: "Stone", deck: "random" },
    { id: "r54", optionA: "Pen", optionB: "Pencil", deck: "random" },
    { id: "r55", optionA: "Marker", optionB: "Crayon", deck: "random" },
    { id: "r56", optionA: "Paint", optionB: "Draw", deck: "random" },
    { id: "r57", optionA: "Circle", optionB: "Square", deck: "random" },
    { id: "r58", optionA: "Triangle", optionB: "Rectangle", deck: "random" },
    { id: "r59", optionA: "Line", optionB: "Dot", deck: "random" },
    { id: "r60", optionA: "Start", optionB: "Finish", deck: "random" },
    { id: "r61", optionA: "Win", optionB: "Lose", deck: "random" },
    { id: "r62", optionA: "Play", optionB: "Pause", deck: "random" },
    { id: "r63", optionA: "Rewind", optionB: "Fast forward", deck: "random" },
    { id: "r64", optionA: "Volume up", optionB: "Volume down", deck: "random" },
    { id: "r65", optionA: "Mute", optionB: "Unmute", deck: "random" },
    { id: "r66", optionA: "On", optionB: "Off", deck: "random" },
    { id: "r67", optionA: "Open", optionB: "Close", deck: "random" },
    { id: "r68", optionA: "Lock", optionB: "Unlock", deck: "random" },
    { id: "r69", optionA: "Push", optionB: "Pull", deck: "random" },
    { id: "r70", optionA: "Enter", optionB: "Exit", deck: "random" },
    { id: "r71", optionA: "Arrival", optionB: "Departure", deck: "random" },
    { id: "r72", optionA: "Hello", optionB: "Goodbye", deck: "random" },
    { id: "r73", optionA: "Please", optionB: "Thank you", deck: "random" },
    { id: "r74", optionA: "Sorry", optionB: "You're welcome", deck: "random" },
    { id: "r75", optionA: "Love", optionB: "Hate", deck: "random" },
    { id: "r76", optionA: "Joy", optionB: "Sadness", deck: "random" },
    { id: "r77", optionA: "Anger", optionB: "Fear", deck: "random" },
    { id: "r78", optionA: "Hope", optionB: "Despair", deck: "random" },
    { id: "r79", optionA: "Life", optionB: "Death", deck: "random" },
    { id: "r80", optionA: "Heaven", optionB: "Hell", deck: "random" },
    { id: "r81", optionA: "Angel", optionB: "Demon", deck: "random" },
    { id: "r82", optionA: "Ghost", optionB: "Zombie", deck: "random" },
    { id: "r83", optionA: "Witch", optionB: "Wizard", deck: "random" },
    { id: "r84", optionA: "Dragon", optionB: "Unicorn", deck: "random" },
    { id: "r85", optionA: "Fairy", optionB: "Mermaid", deck: "random" },
    { id: "r86", optionA: "Hero", optionB: "Villain", deck: "random" },
    { id: "r87", optionA: "Boss", optionB: "Employee", deck: "random" },
    { id: "r88", optionA: "Teacher", optionB: "Student", deck: "random" },
    { id: "r89", optionA: "Doctor", optionB: "Nurse", deck: "random" },
    { id: "r90", optionA: "Police", optionB: "Firefighter", deck: "random" },
    { id: "r91", optionA: "Soldier", optionB: "Spy", deck: "random" },
    { id: "r92", optionA: "Pilot", optionB: "Captain", deck: "random" },
    { id: "r93", optionA: "Chef", optionB: "Waiter", deck: "random" },
    { id: "r94", optionA: "Artist", optionB: "Musician", deck: "random" },
    { id: "r95", optionA: "Writer", optionB: "Actor", deck: "random" },
    { id: "r96", optionA: "Scientist", optionB: "Engineer", deck: "random" },
    { id: "r97", optionA: "Math", optionB: "Science", deck: "random" },
    { id: "r98", optionA: "History", optionB: "Geography", deck: "random" },
    { id: "r99", optionA: "English", optionB: "Art", deck: "random" },
    { id: "r100", optionA: "PE", optionB: "Music", deck: "random" },
];

const deepQuestionsDeck: RapidFireCard[] = [
    { id: "d1", optionA: "Fame", optionB: "Wealth", deck: "deep" },
    { id: "d2", optionA: "Love", optionB: "Success", deck: "deep" },
    { id: "d3", optionA: "Past", optionB: "Future", deck: "deep" },
    { id: "d4", optionA: "Truth", optionB: "Happiness", deck: "deep" },
    { id: "d5", optionA: "Power", optionB: "Knowledge", deck: "deep" },
    { id: "d6", optionA: "Passion", optionB: "Stability", deck: "deep" },
    { id: "d7", optionA: "Freedom", optionB: "Security", deck: "deep" },
    { id: "d8", optionA: "Adventure", optionB: "Comfort", deck: "deep" },
    { id: "d9", optionA: "Alone", optionB: "With someone", deck: "deep" },
    { id: "d10", optionA: "Rich and sad", optionB: "Poor and happy", deck: "deep" },
    { id: "d11", optionA: "Forgive", optionB: "Forget", deck: "deep" },
    { id: "d12", optionA: "Loved", optionB: "Respected", deck: "deep" },
    { id: "d13", optionA: "Idealist", optionB: "Realist", deck: "deep" },
    { id: "d14", optionA: "Logic", optionB: "Emotion", deck: "deep" },
    { id: "d15", optionA: "Justice", optionB: "Mercy", deck: "deep" },
    { id: "d16", optionA: "Talent", optionB: "Hard work", deck: "deep" },
    { id: "d17", optionA: "Destiny", optionB: "Free will", deck: "deep" },
    { id: "d18", optionA: "Optimist", optionB: "Pessimist", deck: "deep" },
    { id: "d19", optionA: "Introvert", optionB: "Extrovert", deck: "deep" },
    { id: "d20", optionA: "Leader", optionB: "Follower", deck: "deep" },
    { id: "d21", optionA: "Head", optionB: "Heart", deck: "deep" },
    { id: "d22", optionA: "Plan", optionB: "Improvise", deck: "deep" },
    { id: "d23", optionA: "Quality", optionB: "Quantity", deck: "deep" },
    { id: "d24", optionA: "Time", optionB: "Money", deck: "deep" },
    { id: "d25", optionA: "Speak", optionB: "Listen", deck: "deep" },
    { id: "d26", optionA: "Create", optionB: "Explore", deck: "deep" },
    { id: "d27", optionA: "Teach", optionB: "Learn", deck: "deep" },
    { id: "d28", optionA: "Give", optionB: "Receive", deck: "deep" },
    { id: "d29", optionA: "Start", optionB: "Finish", deck: "deep" },
    { id: "d30", optionA: "Process", optionB: "Result", deck: "deep" },
    { id: "d31", optionA: "Dream", optionB: "Do", deck: "deep" },
    { id: "d32", optionA: "Ask", optionB: "Guess", deck: "deep" },
    { id: "d33", optionA: "Lead", optionB: "Follow", deck: "deep" },
    { id: "d34", optionA: "Fight", optionB: "Flight", deck: "deep" },
    { id: "d35", optionA: "Save", optionB: "Spend", deck: "deep" },
    { id: "d36", optionA: "Hold on", optionB: "Let go", deck: "deep" },
    { id: "d37", optionA: "Remember", optionB: "Forget", deck: "deep" },
    { id: "d38", optionA: "Change", optionB: "Stay same", deck: "deep" },
    { id: "d39", optionA: "Travel", optionB: "Settle", deck: "deep" },
    { id: "d40", optionA: "City", optionB: "Nature", deck: "deep" },
    { id: "d41", optionA: "Modern", optionB: "Traditional", deck: "deep" },
    { id: "d42", optionA: "Simple", optionB: "Complex", deck: "deep" },
    { id: "d43", optionA: "Fast", optionB: "Slow", deck: "deep" },
    { id: "d44", optionA: "Loud", optionB: "Quiet", deck: "deep" },
    { id: "d45", optionA: "Public", optionB: "Private", deck: "deep" },
    { id: "d46", optionA: "Digital", optionB: "Analog", deck: "deep" },
    { id: "d47", optionA: "Online", optionB: "Offline", deck: "deep" },
    { id: "d48", optionA: "Virtual", optionB: "Real", deck: "deep" },
    { id: "d49", optionA: "Global", optionB: "Local", deck: "deep" },
    { id: "d50", optionA: "Individual", optionB: "Community", deck: "deep" },
    { id: "d51", optionA: "Competition", optionB: "Collaboration", deck: "deep" },
    { id: "d52", optionA: "Win", optionB: "Participate", deck: "deep" },
    { id: "d53", optionA: "Goal", optionB: "Journey", deck: "deep" },
    { id: "d54", optionA: "Fact", optionB: "Opinion", deck: "deep" },
    { id: "d55", optionA: "Science", optionB: "Faith", deck: "deep" },
    { id: "d56", optionA: "Mind", optionB: "Soul", deck: "deep" },
    { id: "d57", optionA: "Physical", optionB: "Mental", deck: "deep" },
    { id: "d58", optionA: "Nature", optionB: "Nurture", deck: "deep" },
    { id: "d59", optionA: "Fate", optionB: "Chance", deck: "deep" },
    { id: "d60", optionA: "Absolute", optionB: "Relative", deck: "deep" },
    { id: "d61", optionA: "Objective", optionB: "Subjective", deck: "deep" },
    { id: "d62", optionA: "Order", optionB: "Chaos", deck: "deep" },
    { id: "d63", optionA: "Control", optionB: "Trust", deck: "deep" },
    { id: "d64", optionA: "Safety", optionB: "Risk", deck: "deep" },
    { id: "d65", optionA: "Peace", optionB: "Excitement", deck: "deep" },
    { id: "d66", optionA: "Growth", optionB: "Sustainability", deck: "deep" },
    { id: "d67", optionA: "Innovation", optionB: "Tradition", deck: "deep" },
    { id: "d68", optionA: "Experience", optionB: "Education", deck: "deep" },
    { id: "d69", optionA: "Wisdom", optionB: "Intelligence", deck: "deep" },
    { id: "d70", optionA: "Book smart", optionB: "Street smart", deck: "deep" },
    { id: "d71", optionA: "Art", optionB: "Science", deck: "deep" },
    { id: "d72", optionA: "Music", optionB: "Lyrics", deck: "deep" },
    { id: "d73", optionA: "Form", optionB: "Function", deck: "deep" },
    { id: "d74", optionA: "Quality", optionB: "Value", deck: "deep" },
    { id: "d75", optionA: "Luxury", optionB: "Necessity", deck: "deep" },
    { id: "d76", optionA: "Want", optionB: "Need", deck: "deep" },
    { id: "d77", optionA: "Give", optionB: "Take", deck: "deep" },
    { id: "d78", optionA: "Forgive", optionB: "Revenge", deck: "deep" },
    { id: "d79", optionA: "Kindness", optionB: "Honesty", deck: "deep" },
    { id: "d80", optionA: "Loyalty", optionB: "Integrity", deck: "deep" },
    { id: "d81", optionA: "Courage", optionB: "Caution", deck: "deep" },
    { id: "d82", optionA: "Modesty", optionB: "Pride", deck: "deep" },
    { id: "d83", optionA: "Humility", optionB: "Confidence", deck: "deep" },
    { id: "d84", optionA: "Generosity", optionB: "Thrift", deck: "deep" },
    { id: "d85", optionA: "Patience", optionB: "Action", deck: "deep" },
    { id: "d86", optionA: "Tolerance", optionB: "Conviction", deck: "deep" },
    { id: "d87", optionA: "Curiosity", optionB: "Certainty", deck: "deep" },
    { id: "d88", optionA: "Skepticism", optionB: "Belief", deck: "deep" },
    { id: "d89", optionA: "Solitude", optionB: "Company", deck: "deep" },
    { id: "d90", optionA: "Silence", optionB: "Noise", deck: "deep" },
    { id: "d91", optionA: "Day", optionB: "Night", deck: "deep" },
    { id: "d92", optionA: "Sun", optionB: "Rain", deck: "deep" },
    { id: "d93", optionA: "Spring", optionB: "Fall", deck: "deep" },
    { id: "d94", optionA: "Summer", optionB: "Winter", deck: "deep" },
    { id: "d95", optionA: "Hot", optionB: "Cold", deck: "deep" },
    { id: "d96", optionA: "Dry", optionB: "Wet", deck: "deep" },
    { id: "d97", optionA: "High", optionB: "Low", deck: "deep" },
    { id: "d98", optionA: "Soft", optionB: "Hard", deck: "deep" },
    { id: "d99", optionA: "Sweet", optionB: "Bitter", deck: "deep" },
    { id: "d100", optionA: "Life", optionB: "Art", deck: "deep" },
];

const funDeck: RapidFireCard[] = [
    { id: "fn1", optionA: "Invisibility", optionB: "Flying", deck: "fun" },
    { id: "fn2", optionA: "Time travel", optionB: "Teleportation", deck: "fun" },
    { id: "fn3", optionA: "Read minds", optionB: "See future", deck: "fun" },
    { id: "fn4", optionA: "Superhero", optionB: "Wizard", deck: "fun" },
    { id: "fn5", optionA: "Dinosaur", optionB: "Dragon", deck: "fun" },
    { id: "fn6", optionA: "Vampire", optionB: "Werewolf", deck: "fun" },
    { id: "fn7", optionA: "Zombie apocalypse", optionB: "Alien invasion", deck: "fun" },
    { id: "fn8", optionA: "Robot", optionB: "Cyborg", deck: "fun" },
    { id: "fn9", optionA: "Pirate", optionB: "Ninja", deck: "fun" },
    { id: "fn10", optionA: "Millionaire", optionB: "Famous", deck: "fun" },
    { id: "fn11", optionA: "Hogwarts", optionB: "Narnia", deck: "fun" },
    { id: "fn12", optionA: "Star Wars", optionB: "Marvel", deck: "fun" },
    { id: "fn13", optionA: "Batman", optionB: "Superman", deck: "fun" },
    { id: "fn14", optionA: "Coke", optionB: "Pepsi", deck: "fun" },
    { id: "fn15", optionA: "McDonalds", optionB: "Burger King", deck: "fun" },
    { id: "fn16", optionA: "Pizza", optionB: "Tacos", deck: "fun" },
    { id: "fn17", optionA: "Cake", optionB: "Pie", deck: "fun" },
    { id: "fn18", optionA: "Ice Cream", optionB: "Donuts", deck: "fun" },
    { id: "fn19", optionA: "Coffee", optionB: "Tea", deck: "fun" },
    { id: "fn20", optionA: "Beer", optionB: "Wine", deck: "fun" },
    { id: "fn21", optionA: "Summer", optionB: "Winter", deck: "fun" },
    { id: "fn22", optionA: "Beach", optionB: "Snow", deck: "fun" },
    { id: "fn23", optionA: "Shower", optionB: "Bath", deck: "fun" },
    { id: "fn24", optionA: "Morning", optionB: "Night", deck: "fun" },
    { id: "fn25", optionA: "Dog", optionB: "Cat", deck: "fun" },
    { id: "fn26", optionA: "Netflix", optionB: "YouTube", deck: "fun" },
    { id: "fn27", optionA: "Instagram", optionB: "TikTok", deck: "fun" },
    { id: "fn28", optionA: "Call", optionB: "Text", deck: "fun" },
    { id: "fn29", optionA: "iOS", optionB: "Android", deck: "fun" },
    { id: "fn30", optionA: "Mac", optionB: "PC", deck: "fun" },
    { id: "fn31", optionA: "Xbox", optionB: "Playstation", deck: "fun" },
    { id: "fn32", optionA: "Car", optionB: "Motorcycle", deck: "fun" },
    { id: "fn33", optionA: "Driver", optionB: "Passenger", deck: "fun" },
    { id: "fn34", optionA: "Fast", optionB: "Slow", deck: "fun" },
    { id: "fn35", optionA: "Loud", optionB: "Quiet", deck: "fun" },
    { id: "fn36", optionA: "Big", optionB: "Small", deck: "fun" },
    { id: "fn37", optionA: "Rich", optionB: "Famous", deck: "fun" },
    { id: "fn38", optionA: "Smart", optionB: "Funny", deck: "fun" },
    { id: "fn39", optionA: "Strong", optionB: "Fast", deck: "fun" },
    { id: "fn40", optionA: "Tall", optionB: "Short", deck: "fun" },
    { id: "fn41", optionA: "Young", optionB: "Old", deck: "fun" },
    { id: "fn42", optionA: "Past", optionB: "Future", deck: "fun" },
    { id: "fn43", optionA: "Space", optionB: "Ocean", deck: "fun" },
    { id: "fn44", optionA: "Fire", optionB: "Ice", deck: "fun" },
    { id: "fn45", optionA: "Sun", optionB: "Moon", deck: "fun" },
    { id: "fn46", optionA: "Sing", optionB: "Dance", deck: "fun" },
    { id: "fn47", optionA: "Read", optionB: "Write", deck: "fun" },
    { id: "fn48", optionA: "Draw", optionB: "Paint", deck: "fun" },
    { id: "fn49", optionA: "Cook", optionB: "Eat", deck: "fun" },
    { id: "fn50", optionA: "Sleep", optionB: "Play", deck: "fun" },
    { id: "fn51", optionA: "Work", optionB: "School", deck: "fun" },
    { id: "fn52", optionA: "Boss", optionB: "Worker", deck: "fun" },
    { id: "fn53", optionA: "Leader", optionB: "Follower", deck: "fun" },
    { id: "fn54", optionA: "Save", optionB: "Spend", deck: "fun" },
    { id: "fn55", optionA: "Give", optionB: "Receive", deck: "fun" },
    { id: "fn56", optionA: "Love", optionB: "Money", deck: "fun" },
    { id: "fn57", optionA: "Family", optionB: "Friends", deck: "fun" },
    { id: "fn58", optionA: "Home", optionB: "Travel", deck: "fun" },
    { id: "fn59", optionA: "City", optionB: "Nature", deck: "fun" },
    { id: "fn60", optionA: "Hot", optionB: "Cold", deck: "fun" },
    { id: "fn61", optionA: "Wet", optionB: "Dry", deck: "fun" },
    { id: "fn62", optionA: "Clean", optionB: "Dirty", deck: "fun" },
    { id: "fn63", optionA: "Messy", optionB: "Neat", deck: "fun" },
    { id: "fn64", optionA: "Early", optionB: "Late", deck: "fun" },
    { id: "fn65", optionA: "Fast food", optionB: "Healthy food", deck: "fun" },
    { id: "fn66", optionA: "Sweet", optionB: "Salty", deck: "fun" },
    { id: "fn67", optionA: "Sour", optionB: "Spicy", deck: "fun" },
    { id: "fn68", optionA: "Meat", optionB: "Veggie", deck: "fun" },
    { id: "fn69", optionA: "Fruit", optionB: "Vegetable", deck: "fun" },
    { id: "fn70", optionA: "Chocolate", optionB: "Vanilla", deck: "fun" },
    { id: "fn71", optionA: "Pancakes", optionB: "Waffles", deck: "fun" },
    { id: "fn72", optionA: "Bacon", optionB: "Sausage", deck: "fun" },
    { id: "fn73", optionA: "Eggs", optionB: "Toast", deck: "fun" },
    { id: "fn74", optionA: "Juice", optionB: "Soda", deck: "fun" },
    { id: "fn75", optionA: "Water", optionB: "Milk", deck: "fun" },
    { id: "fn76", optionA: "Red", optionB: "Blue", deck: "fun" },
    { id: "fn77", optionA: "Green", optionB: "Yellow", deck: "fun" },
    { id: "fn78", optionA: "Black", optionB: "White", deck: "fun" },
    { id: "fn79", optionA: "Gold", optionB: "Silver", deck: "fun" },
    { id: "fn80", optionA: "Circle", optionB: "Square", deck: "fun" },
    { id: "fn81", optionA: "Pen", optionB: "Pencil", deck: "fun" },
    { id: "fn82", optionA: "Paper", optionB: "Plastic", deck: "fun" },
    { id: "fn83", optionA: "Rock", optionB: "Scissors", deck: "fun" },
    { id: "fn84", optionA: "Hammer", optionB: "Screwdriver", deck: "fun" },
    { id: "fn85", optionA: "Nail", optionB: "Screw", deck: "fun" },
    { id: "fn86", optionA: "Carpet", optionB: "Wood", deck: "fun" },
    { id: "fn87", optionA: "Curtains", optionB: "Blinds", deck: "fun" },
    { id: "fn88", optionA: "Bed", optionB: "Couch", deck: "fun" },
    { id: "fn89", optionA: "Table", optionB: "Desk", deck: "fun" },
    { id: "fn90", optionA: "Chair", optionB: "Stool", deck: "fun" },
    { id: "fn91", optionA: "Door", optionB: "Window", deck: "fun" },
    { id: "fn92", optionA: "Roof", optionB: "Floor", deck: "fun" },
    { id: "fn93", optionA: "Wall", optionB: "Ceiling", deck: "fun" },
    { id: "fn94", optionA: "Stairs", optionB: "Elevator", deck: "fun" },
    { id: "fn95", optionA: "Up", optionB: "Down", deck: "fun" },
    { id: "fn96", optionA: "Left", optionB: "Right", deck: "fun" },
    { id: "fn97", optionA: "Front", optionB: "Back", deck: "fun" },
    { id: "fn98", optionA: "In", optionB: "Out", deck: "fun" },
    { id: "fn99", optionA: "Happy", optionB: "Sad", deck: "fun" },
    { id: "fn100", optionA: "Good", optionB: "Bad", deck: "fun" },
];

export const DECKS = {
    couples: { name: "Couples ❤️", cards: couplesDeck, emoji: "❤️" },
    food: { name: "Food 🍕", cards: foodDeck, emoji: "🍕" },
    travel: { name: "Travel ✈️", cards: travelDeck, emoji: "✈️" },
    entertainment: { name: "Entertainment 🎬", cards: entertainmentDeck, emoji: "🎬" },
    lifestyle: { name: "Lifestyle 🏠", cards: lifestyleDeck, emoji: "🏠" },
    random: { name: "Random 🎲", cards: randomDeck, emoji: "🎲" },
    deep: { name: "Deep Questions 🤔", cards: deepQuestionsDeck, emoji: "🤔" },
    fun: { name: "Fun 🎉", cards: funDeck, emoji: "🎉" },
} as const;

export type DeckType = keyof typeof DECKS;

export function getDeckCards(deckType: DeckType, count: number, seed?: number): RapidFireCard[] {
    // Safety check: default to couples if deckType is invalid
    const validDeckType = deckType && DECKS[deckType] ? deckType : 'couples';
    const deck = DECKS[validDeckType].cards;

    // Seeded random number generator for consistent shuffle across clients
    const seededRandom = (s: number) => {
        const x = Math.sin(s) * 10000;
        return x - Math.floor(x);
    };

    // Shuffle the deck - use seed if provided for consistent results
    const shuffled = [...deck];
    let currentSeed = seed ?? Math.random() * 10000;

    for (let i = shuffled.length - 1; i > 0; i--) {
        currentSeed = seededRandom(currentSeed * (i + 1));
        const j = Math.floor(currentSeed * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }

    // Return the requested number of cards
    return shuffled.slice(0, count);
}

